// Script boundary: js/market.js (classic JavaScript)
(function(){'use strict';
if(!globalThis.__capitalismTycoonModules)throw new Error('Capitalism Tycoon runtime.js must be loaded before market.js.');
var __modules=globalThis.__capitalismTycoonModules;
if(!__modules.data)throw new Error('Capitalism Tycoon data module must be loaded before market.js.');
if(__modules.market)throw new Error('Capitalism Tycoon market module is already registered.');
(function(exports,data){
const TARGET_BUSINESS_IDS=['ramen'];
const SEGMENTS=[
{id:'value',name:'低価格重視',marketWeight:.24,priceSensitivity:1.55,qualitySensitivity:.45,brandSensitivity:.35,convenienceSensitivity:.65,noveltySensitivity:.25,loyaltySensitivity:.35},
{id:'standard',name:'一般顧客',marketWeight:.30,priceSensitivity:1.00,qualitySensitivity:.85,brandSensitivity:.70,convenienceSensitivity:.85,noveltySensitivity:.40,loyaltySensitivity:.55},
{id:'quality',name:'品質重視',marketWeight:.18,priceSensitivity:.55,qualitySensitivity:1.55,brandSensitivity:.75,convenienceSensitivity:.55,noveltySensitivity:.55,loyaltySensitivity:.65},
{id:'convenience',name:'利便性重視',marketWeight:.16,priceSensitivity:.75,qualitySensitivity:.65,brandSensitivity:.50,convenienceSensitivity:1.55,noveltySensitivity:.35,loyaltySensitivity:.45},
{id:'trend',name:'ブランド・流行重視',marketWeight:.12,priceSensitivity:.65,qualitySensitivity:.80,brandSensitivity:1.45,convenienceSensitivity:.55,noveltySensitivity:1.20,loyaltySensitivity:.75}
];
const COMPETITOR_STRATEGIES={lowPrice:{label:'低価格型',price:.88,quality:44,brand:38,convenience:55},quality:{label:'品質型',price:1.12,quality:68,brand:50,convenience:50},brand:{label:'ブランド型',price:1.18,quality:58,brand:72,convenience:52},convenience:{label:'利便性型',price:1.03,quality:50,brand:46,convenience:72},balanced:{label:'バランス型',price:1.00,quality:54,brand:54,convenience:56}};
const finite=(n,f=0)=>Number.isFinite(Number(n))?Number(n):f;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:min));
const sum=(a,f)=>a.reduce((x,y)=>x+f(y),0);
function isTargetBusiness(id){return TARGET_BUSINESS_IDS.includes(id);}
function validateSegments(){const w=sum(SEGMENTS,s=>s.marketWeight);return Math.abs(w-1)<.0001&&SEGMENTS.length>=5;}
function safeExp(x){return Math.exp(clamp(x,-20,20));}
function getPref(g,id){return (g.prefs||[]).find(p=>p.id===id)||{id,traffic:1,rent:0,areaID:g.selectedArea||'kanto'};}
function getArea(g,id){return (g.areas||[]).find(a=>a.id===id)||{id,traffic:1,competition:.35,growth:.02};}
function oldDemand(g,b,store){const p=getPref(g,store.prefID),a=getArea(g,p.areaID);let localCompetition=finite(a.competition,.35);let d=finite(b.demand,1)*finite(p.traffic,1)*finite(a.traffic,1)*finite(g.economy,1)*finite(g.season,1)*(1+finite(b.quality)/100)*(1+finite(b.brand)/90)*(1+finite(b.dx)/140)*(1-localCompetition*.55);d*=[0,.45,.75,1,1.17][store.operatingHours||3]||1;if(g.macroCrisis)d*=g.macroCrisis.salesMultiplier;return Math.max(0,d);}
function effectiveCapacity(g,b,store){if(store&&store.capacity!==undefined&&store.capacity!==null&&store.capacity!=='auto'){return Math.max(0,finite(store.capacity,0));}const hours=[0,.45,.75,1,1.17][store.operatingHours||3]||1;const condition=clamp(finite(store.condition,100)/100,.4,1.05);return Math.max(1,finite(b.demand,1)*hours*(1+finite(b.efficiency)/100)*condition*4.0);}
function storeOffer(g,b,store){const p=getPref(g,store.prefID),hours=[0,.45,.75,1,1.17][store.operatingHours||3]||1;const deptM=g.departments?.marketing?.established?1:0;const deptO=g.departments?.operations?.established?1:0;const supplier=(g.supplierContracts||[]).find(x=>x.businessID===b.id&&x.active);const quality=clamp(finite(b.quality)+finite(store.quality)*.25+deptO*3+finite(supplier?.quality),0,100);const brand=clamp(finite(b.brand)+finite(store.brand)*.25+finite(g.companyReputation)*.1+deptM*4,0,100);const convenience=clamp(45+finite(p.traffic,1)*18+hours*10+finite(b.dx)*.18,0,100);const service=clamp(45+finite(g.employeeAbility,50)*.35+finite(g.employeeSatisfaction,55)*.20+finite(b.efficiency)*.25,0,100);const capacity=effectiveCapacity(g,b,store);const vc=Math.max(0,finite(b.unitCost)*finite(g.inflation,1)*(1-Math.min(.22,finite(b.efficiency)/260))/(1+deptO*.04))*(1+quality/650);return {id:store.id,type:'player',name:store.name,price:Math.max(1,finite(b.price)*finite(g.inflation,1)),quality,brandAwareness:brand,brandTrust:clamp(brand*.8+finite(store.customerSatisfaction,55)*.2,0,100),convenience,serviceQuality:service,novelty:clamp(20+finite(b.dx)*.4+Math.max(0,12-(finite(g.week)-finite(store.openedWeek||store.openingWeek,g.week)))*2,0,100),capacity,variableCostPerUnit:vc,customerSatisfaction:clamp(finite(store.customerSatisfaction,55),0,100),repeatRate:clamp(finite(store.repeatRate,.22),0,1),storeID:store.id};}
function competitorOffers(g,b,prefID){const p=getPref(g,prefID),areaID=p.areaID;let comps=(g.competitors||[]).filter(c=>c.businessID===b.id&&c.areaID===areaID).slice(0,5);if(!comps.length)comps=[{id:`market-average-${b.id}-${areaID}`,name:'市場平均',strategy:'balanced',stores:3,quality:50,brand:45,areaID,businessID:b.id}];const keys=['lowPrice','quality','brand','convenience','balanced'];return comps.map((c,i)=>{const key=COMPETITOR_STRATEGIES[c.strategy] ? c.strategy : keys[i%keys.length],s=COMPETITOR_STRATEGIES[key];return {id:c.id||`competitor-${i}`,type:'competitor',strategy:s.label,name:c.name||s.label,price:Math.max(1,finite((data.MASTER.businesses||[]).find(x=>x.id===b.id)?.price,b.price)*s.price),quality:clamp(s.quality+finite(c.quality)*.25,0,100),brandAwareness:clamp(s.brand+finite(c.brand)*.3,0,100),brandTrust:clamp(s.brand+finite(c.brand)*.25,0,100),convenience:s.convenience,serviceQuality:s.quality*.85,novelty:35+i*3,capacity:Math.max(1,finite(b.demand)*Math.max(1,finite(c.stores,1))*.9),variableCostPerUnit:finite(b.unitCost),customerSatisfaction:55,repeatRate:.24};});}
function utility(seg,o,avgPrice){const priceRatio=o.price/Math.max(1,avgPrice);return -seg.priceSensitivity*Math.log(priceRatio)+seg.qualitySensitivity*(o.quality-50)/100+seg.brandSensitivity*((o.brandAwareness+o.brandTrust)/2-50)/100+seg.convenienceSensitivity*(o.convenience-50)/40+.35*(o.serviceQuality-50)/45+seg.noveltySensitivity*(o.novelty-35)/55+seg.loyaltySensitivity*((o.customerSatisfaction-50)/80+o.repeatRate*.5);}
function emptyResult(g,b,store,marketPotential=0){const offer=storeOffer(g,b,store);return {businessID:b.id,storeID:store.id,marketKey:`${b.id}:${store.prefID}`,potentialDemand:0,marketPotential,unitsSold:0,capacity:offer.capacity,capacityUtilization:0,lostDemand:0,sales:0,variableCost:0,marginalProfit:0,marginalProfitRate:0,profit:0,fixedCost:0,repairCost:0,marketShare:0,customerSatisfaction:offer.customerSatisfaction,repeatRate:offer.repeatRate,weekOverWeekChange:0,segments:SEGMENTS.map(s=>({id:s.id,name:s.name,marketWeight:s.marketWeight,potentialDemand:0,playerShare:0,playerDemand:0,competitorShare:0,outsideShare:1})),offer,competitors:[],reasons:[],valid:true};}
function calculateLocalMarket(g,b,stores){stores=(stores||[]).filter(s=>s&&s.status==='open'&&s.businessID===b.id);if(!stores.length)return {marketKey:'',marketPotential:0,results:[]};const prefID=stores[0].prefID,marketKey=`${b.id}:${prefID}`,players=stores.map(s=>storeOffer(g,b,s)),competitors=competitorOffers(g,b,prefID),offers=[...players,...competitors],avgPrice=sum(offers,o=>o.price)/Math.max(1,offers.length);const avgLegacy=sum(stores,s=>oldDemand(g,b,s))/Math.max(1,stores.length);const marketPotential=Math.min(250000,Math.max(0,avgLegacy*2.2*(1+Math.min(.35,(stores.length-1)*.18))));const byStore=new Map(stores.map(s=>[s.id,emptyResult(g,b,s,marketPotential)]));for(const r of byStore.values()){r.competitors=competitors;r.marketKey=marketKey;r.marketPotential=marketPotential;r.segments=[];}for(const seg of SEGMENTS){const outside=safeExp(-.15+seg.priceSensitivity*Math.max(0,Math.min(...players.map(p=>p.price))/avgPrice-1.15));const scores=offers.map(o=>safeExp(utility(seg,o,avgPrice)));const denom=sum(scores,x=>x)+outside||1;const segmentPotential=marketPotential*seg.marketWeight;for(const p of players){const share=clamp(scores[offers.indexOf(p)]/denom,0,1),demand=segmentPotential*share;const r=byStore.get(p.id);r.potentialDemand+=demand;r.segments.push({id:seg.id,name:seg.name,marketWeight:seg.marketWeight,potentialDemand:segmentPotential,playerShare:share,playerDemand:demand,competitorShare:clamp(sum(competitors,(c)=>scores[offers.indexOf(c)]/denom),0,1),outsideShare:clamp(outside/denom,0,1)});}}
for(const store of stores){const r=byStore.get(store.id),player=players.find(p=>p.id===store.id);const units=Math.min(r.potentialDemand,player.capacity);const sales=units*player.price,variable=units*player.variableCostPerUnit,margin=sales-variable;const fixed=(finite(b.fixedCost)+finite(getPref(g,store.prefID).rent)+finite(b.wage))*finite(g.inflation,1)*([0,.55,.8,1,1.24][store.operatingHours||3]||1)*(g.macroCrisis?.costMultiplier||1);const repair=Math.max(0,100-finite(store.condition,100))*650;const prior=finite(store.lastSales,0);Object.assign(r,{unitsSold:units,capacity:player.capacity,capacityUtilization:player.capacity>0?clamp(units/player.capacity,0,1):0,lostDemand:Math.max(0,r.potentialDemand-units),sales,variableCost:variable,marginalProfit:margin,marginalProfitRate:sales>0?margin/sales:0,profit:margin-fixed-repair,fixedCost:fixed,repairCost:repair,marketShare:marketPotential>0?clamp(units/marketPotential,0,1):0,customerSatisfaction:clamp(52+(marketPotential>0?units/marketPotential:0)*80+player.quality*.08-Math.max(0,player.price/avgPrice-1)*18,0,100),repeatRate:clamp(.15+(marketPotential>0?units/marketPotential:0)*.45+player.brandTrust/500,0,1),weekOverWeekChange:prior>0?(sales-prior)/prior:0,reasons:[{label:'市場需要',value:clamp((marketPotential/Math.max(1,finite(b.demand))-1)*.02,-.2,.2)},{label:'価格競争力',value:clamp((avgPrice/player.price-1)*.25,-.25,.25)},{label:'品質',value:clamp((player.quality-50)/500,-.12,.12)},{label:'ブランド・広告',value:clamp((player.brandAwareness-50)/550,-.10,.10)},{label:'競合',value:clamp(-sum(r.segments,s=>s.competitorShare*s.marketWeight)*.08,-.15,0)},{label:'販売能力不足',value:r.potentialDemand>player.capacity?clamp(-(r.potentialDemand-player.capacity)/Math.max(1,r.potentialDemand),-.5,0):0},{label:'顧客満足度・リピート',value:clamp((player.customerSatisfaction-55)/800+player.repeatRate*.03,-.08,.08)},{label:'景気',value:clamp((finite(g.economy,1)-1)*.5,-.2,.2)}].filter(x=>Number.isFinite(x.value))});}
return {marketKey,marketPotential,results:[...byStore.values()]};}
function calculateStoreMarket(g,b,store){return calculateLocalMarket(g,b,[store]).results[0]||emptyResult(g,b,store,0);}
function calculateMarketGroups(g,businesses,stores){const results={},markets={};const groups=new Map();for(const store of stores||[]){if(!store||store.status!=='open'||!isTargetBusiness(store.businessID))continue;const key=`${store.businessID}:${store.prefID}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(store);}for(const groupStores of groups.values()){const b=(businesses||[]).find(x=>x.id===groupStores[0].businessID);if(!b)continue;const marketResult=calculateLocalMarket(g,b,groupStores);markets[marketResult.marketKey]={marketKey:marketResult.marketKey,businessID:b.id,prefID:groupStores[0].prefID,marketPotential:marketResult.marketPotential,storeIDs:groupStores.map(s=>s.id)};for(const r of marketResult.results)results[r.storeID]=r;}return {results,markets};}
function applyResultToStore(store,result){store.marketMetrics=result;store.lastMarketResult=result;store.lastSales=result.sales;store.lastProfit=result.profit;store.customerSatisfaction=result.customerSatisfaction;store.repeatRate=result.repeatRate;store.capacity=result.capacity===0&&store.capacity===0?0:(store.capacity??null);store.effectiveCapacity=result.capacity;}
function validateResult(r){return !!r&&['potentialDemand','unitsSold','capacity','sales','variableCost','marginalProfit','marketShare','marketPotential'].every(k=>Number.isFinite(r[k])&&r[k]>=0)&&r.marketShare<=1;}
Object.assign(exports,{TARGET_BUSINESS_IDS,SEGMENTS,COMPETITOR_STRATEGIES,isTargetBusiness,validateSegments,effectiveCapacity,competitorOffers,calculateLocalMarket,calculateStoreMarket,calculateMarketGroups,applyResultToStore,validateResult});
})(__modules.market={},__modules.data);
})();
