// Script boundary: js/market.js (classic JavaScript)
(function(){'use strict';
if(!globalThis.__capitalismTycoonModules)throw new Error('Capitalism Tycoon runtime.js must be loaded before market.js.');
var __modules=globalThis.__capitalismTycoonModules;
if(!__modules.data)throw new Error('Capitalism Tycoon data module must be loaded before market.js.');
if(__modules.market)throw new Error('Capitalism Tycoon market module is already registered.');
(function(exports){
const TARGET_BUSINESS_IDS = Object.freeze(['ramen']);
const SEGMENTS = Object.freeze([
 {id:'price',name:'価格重視',marketWeight:.26,priceSensitivity:1.55,qualitySensitivity:.45,brandSensitivity:.30,convenienceSensitivity:.70,serviceSensitivity:.45,noveltySensitivity:.20,loyaltySensitivity:.35},
 {id:'standard',name:'日常利用',marketWeight:.28,priceSensitivity:.95,qualitySensitivity:.80,brandSensitivity:.60,convenienceSensitivity:.85,serviceSensitivity:.70,noveltySensitivity:.35,loyaltySensitivity:.65},
 {id:'quality',name:'味・品質重視',marketWeight:.18,priceSensitivity:.55,qualitySensitivity:1.55,brandSensitivity:.75,convenienceSensitivity:.45,serviceSensitivity:.95,noveltySensitivity:.55,loyaltySensitivity:.75},
 {id:'convenience',name:'利便性重視',marketWeight:.16,priceSensitivity:.75,qualitySensitivity:.55,brandSensitivity:.45,convenienceSensitivity:1.55,serviceSensitivity:.80,noveltySensitivity:.30,loyaltySensitivity:.55},
 {id:'brand',name:'ブランド・流行重視',marketWeight:.12,priceSensitivity:.50,qualitySensitivity:.85,brandSensitivity:1.55,convenienceSensitivity:.45,serviceSensitivity:.70,noveltySensitivity:1.25,loyaltySensitivity:.85}
]);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const sum=a=>a.reduce((x,y)=>x+y,0);
function isTargetBusinessID(id){return TARGET_BUSINESS_IDS.indexOf(id)>=0;}
function validateSegments(){const total=sum(SEGMENTS.map(s=>s.marketWeight));return Math.abs(total-1)<.000001&&new Set(SEGMENTS.map(s=>`${s.priceSensitivity}/${s.qualitySensitivity}/${s.brandSensitivity}/${s.convenienceSensitivity}`)).size===SEGMENTS.length;}
function prefAreaID(state,prefID){return (state.prefs||[]).find(p=>p.id===prefID)?.areaID||state.selectedArea||null;}
function marketKey(store){return `${store.businessID}::${store.prefID}`;}
function groupTargetStores(stores){const groups={};for(const s of stores||[]){if(s.status==='open'&&isTargetBusinessID(s.businessID)){const k=marketKey(s);(groups[k]||(groups[k]=[])).push(s);}}return groups;}
function effectiveCapacity(store,business,pref){if(Object.prototype.hasOwnProperty.call(store,'capacity')&&store.capacity!==null&&store.capacity!==undefined){return Math.max(0,finite(store.capacity,0));}
 const hours=[0,.45,.75,1,1.17][store.operatingHours||3]||1;const level=1+Math.max(0,finite(store.level,1)-1)*.08;const condition=clamp(finite(store.condition,100)/100,.4,1);const traffic=clamp(finite(pref?.traffic,1),.5,2.5);const eff=1+clamp(finite(business?.efficiency,0),0,100)/250;return Math.max(1,Math.round(finite(business?.demand,1)*hours*level*condition*traffic*eff*4.0));}
function storeOffer(state,store){const b=(state.businesses||[]).find(x=>x.id===store.businessID)||{};const p=(state.prefs||[]).find(x=>x.id===store.prefID)||{};const tenant=(state.tenants||[]).find(t=>t.id===store.tenantID)||{};const dept=id=>state.departments&&state.departments[id]?(.35+finite(state.departmentStaff?.[id],1)*.08):0;const cmo=finite(state.executives?.CMO?.skill,0),coo=finite(state.executives?.COO?.skill,0);const ads=dept('marketing')*.04+cmo/2200;const ops=dept('operations')*.03+coo/2400;const convenience=clamp(40+finite(p.traffic,1)*18+finite(tenant.traffic,1)*14+finite(store.operatingHours,3)*7,0,100);const quality=clamp(finite(b.quality)+finite(store.quality)*.35+ops*100,0,100);const brandAwareness=clamp(finite(b.brand)+finite(store.brand)*.35+finite(state.companyReputation,0)*.18+ads*100,0,100);const brandTrust=clamp(brandAwareness*.65+quality*.25+finite(state.companyReputation,0)*.10,0,100);const wf=globalThis.__capitalismTycoonModules?.workforce;let baseCap=effectiveCapacity(store,b,p);let wfAdj=wf&&wf.TARGET_BUSINESS_IDS.indexOf(store.businessID)>=0?wf.storeAdjustment(state,store,baseCap):null;const serviceQuality=clamp(45+finite(state.employeeAbility,50)*.30+finite(state.employeeSatisfaction,55)*.18+ops*100+(wfAdj?wfAdj.serviceQualityAdjustment*100:0),0,100);const novelty=clamp(finite(b.dx,0)*.65+finite(b.quality,0)*.2+ads*25,0,100);const satisfaction=clamp(35+quality*.32+serviceQuality*.25+brandTrust*.16,0,100);const repeatRate=clamp(.12+satisfaction/180+brandTrust/380,0, .88);const variableCostPerUnit=finite(b.unitCost)*(1+quality/1000)*(1-Math.min(.22,finite(b.efficiency)/260))/(1+dept('operations')*.04);return {id:store.id,kind:'player',store,business:b,pref:p,price:Math.max(1,finite(b.price,1)),quality,brandAwareness,brandTrust,convenience,serviceQuality,novelty,capacity:(wfAdj?wfAdj.staffLimitedCapacity:baseCap),workforceAdjustment:wfAdj,variableCostPerUnit,customerSatisfaction:satisfaction,repeatRate};}
function competitorOffers(state,businessID,prefID){const ai=globalThis.__capitalismTycoonModules?.competitor;if(ai&&businessID==='ramen'){const detailed=ai.offers(state,businessID,prefID);if(detailed&&detailed.length)return detailed;}const areaID=prefAreaID(state,prefID);let rows=(state.competitors||[]).filter(c=>c.businessID===businessID&&c.areaID===areaID);if(!rows.length)rows=[{id:'market-average',name:'市場平均',businessID,areaID,stores:1,brand:18,quality:20,strategy:'balanced'}];const base=(state.businesses||[]).find(b=>b.id===businessID)||{};const referencePrice=businessID==='ramen'?920:finite(base.price,1);const strat={low:[.90,-4,-2,0],quality:[1.08,12,3,1],brand:[1.12,4,16,2],convenience:[1.02,1,2,16],balanced:[1,4,4,4]};return rows.map((c,i)=>{const key=c.strategy==='低価格型'?'low':c.strategy==='品質型'?'quality':c.strategy==='ブランド型'?'brand':c.strategy==='利便性型'?'convenience':'balanced';const s=strat[key]||strat.balanced;return {id:`competitor-${c.id||i}`,kind:'competitor',name:c.name||'競合',price:Math.max(1,referencePrice*s[0]*(1+(i%3-1)*.025)),quality:clamp(finite(c.quality)+s[1],0,100),brandAwareness:clamp(finite(c.brand)+s[2],0,100),brandTrust:clamp(finite(c.brand)*.7+finite(c.quality)*.25+s[2],0,100),convenience:clamp(55+s[3]+finite(c.stores,1)*1.8,0,100),serviceQuality:clamp(50+finite(c.quality)*.25,0,100),novelty:clamp(25+s[2],0,100),customerSatisfaction:clamp(45+finite(c.quality)*.35+finite(c.brand)*.15,0,100),repeatRate:clamp(.25+finite(c.brand)/350,0,.8),stores:Math.max(1,finite(c.stores,1)),capacity:Math.max(0,finite(c.stores,1)*525),variableCostPerUnit:finite(base.unitCost,1)};});}
function marketPotential(state,businessID,prefID){const b=(state.businesses||[]).find(x=>x.id===businessID)||{},p=(state.prefs||[]).find(x=>x.id===prefID)||{},a=(state.areas||[]).find(x=>x.id===p.areaID)||{};let v=finite(b.demand,1)*finite(p.traffic,1)*finite(a.traffic,1)*finite(state.economy,1)*finite(state.season,1);v*=businessID==='ramen'?finite(a.ramenFit,1):1;if(state.macroCrisis)v*=finite(state.macroCrisis.salesMultiplier,1);return clamp(v*2.05,0,10000000);}
function utility(o,seg,avgPrice){const rel=(avgPrice-o.price)/Math.max(1,avgPrice);return rel*seg.priceSensitivity*1.8+(o.quality-50)/50*seg.qualitySensitivity+(o.brandTrust-45)/55*seg.brandSensitivity+(o.convenience-50)/50*seg.convenienceSensitivity+(o.serviceQuality-50)/50*seg.serviceSensitivity+(o.novelty-35)/65*seg.noveltySensitivity+(o.customerSatisfaction-50)/50*seg.loyaltySensitivity+o.repeatRate*seg.loyaltySensitivity;}
function campaignUtility(state,o,segmentID){if(o.kind!=='player')return 0;const ads=globalThis.__capitalismTycoonModules?.playerMediaAdvertising;if(!ads)return 0;return ads.utilityBoost(state,o.business?.id,segmentID);}
function softShares(items){const max=Math.max(...items.map(x=>x.u));const ex=items.map(x=>Math.exp(clamp(x.u-max,-50,50)));const den=Math.max(1e-12,sum(ex));return items.map((x,i)=>({...x,share:clamp(ex[i]/den,0,1)}));}
function calculateMarket(state,stores){const businessID=stores[0]?.businessID,prefID=stores[0]?.prefID;const players=stores.map(s=>storeOffer(state,s));const comps=competitorOffers(state,businessID,prefID);const offers=players.concat(comps);const avgPrice=sum(comps.map(o=>o.price))/Math.max(1,comps.length);const potential=marketPotential(state,businessID,prefID);const results={marketKey:`${businessID}::${prefID}`,businessID,prefID,areaID:prefAreaID(state,prefID),marketPotential:potential,stores:{},competitors:comps,segments:[],ownUnitsSold:0,ownPotentialDemand:0,ownMarketShare:0,competitorResults:{},competitorSummary:{}};for(const seg of SEGMENTS){const demand=potential*seg.marketWeight;const referencePrice=businessID==='ramen'?920:avgPrice;const noBuy={id:'no-purchase',kind:'none',u:-.15+(avgPrice/Math.max(1,referencePrice)-1)*1.2};const scored=offers.map(o=>{const base=utility(o,seg,avgPrice),boost=campaignUtility(state,o,seg.id);return{id:o.id,kind:o.kind,offer:o,u:boost?base+boost:base};}).concat(noBuy);const shares=softShares(scored);for(const row of shares){if(row.kind==='player'){const r=results.stores[row.id]||(results.stores[row.id]={storeID:row.id,potentialDemand:0,segmentShares:{},segmentUnits:{},offer:row.offer});const units=demand*row.share;r.potentialDemand+=units;r.segmentShares[seg.id]=row.share;r.segmentUnits[seg.id]=units;}else if(row.kind==='competitor'){const r=results.competitorResults[row.id]||(results.competitorResults[row.id]={presenceID:row.offer.presenceID||row.id,competitorID:row.offer.competitorID||row.id,name:row.offer.name,potentialDemand:0,segmentShares:{},segmentUnits:{},offer:row.offer});const units=demand*row.share;r.potentialDemand+=units;r.segmentShares[seg.id]=row.share;r.segmentUnits[seg.id]=units;}}results.segments.push({id:seg.id,name:seg.name,demand,shares:Object.fromEntries(shares.map(x=>[x.id,x.share]))});}
 for(const r of Object.values(results.competitorResults)){const o=r.offer;const cap=finite(o.capacity,finite(o.stores,1)*525);const units=Math.min(r.potentialDemand,cap);const revenue=units*o.price*finite(state.inflation,1);const variableCost=units*finite(o.variableCostPerUnit,300)*finite(state.inflation,1);r.demandAllocatedUnits=r.potentialDemand;r.capacityLimitedUnits=Math.max(0,r.potentialDemand-cap);r.fulfilledUnits=units;r.lostDemand=Math.max(0,r.potentialDemand-units);r.revenue=revenue;r.variableCost=variableCost;r.contributionMargin=revenue-variableCost;r.contributionMarginRate=revenue>0?r.contributionMargin/revenue:0;r.demandMarketShare=potential>0?clamp(r.potentialDemand/potential,0,1):0;r.realizedMarketShare=potential>0?clamp(units/potential,0,1):0;r.marketShare=r.realizedMarketShare;r.customerSatisfaction=o.customerSatisfaction;r.repeatRate=o.repeatRate;r.price=o.price;r.quality=o.quality;r.brandAwareness=o.brandAwareness;r.storeCount=o.storeCount||o.stores||1;delete r.offer;const cs=results.competitorSummary[r.competitorID]||(results.competitorSummary[r.competitorID]={competitorID:r.competitorID,name:r.name,fulfilledUnits:0,revenue:0,marketShare:0});cs.fulfilledUnits+=units;cs.revenue+=revenue;cs.marketShare+=r.realizedMarketShare;} for(const r of Object.values(results.stores)){const o=r.offer;const units=Math.min(r.potentialDemand,o.capacity);const revenue=units*o.price*finite(state.inflation,1);const variableCost=units*o.variableCostPerUnit*finite(state.inflation,1);r.unitsSold=units;r.effectiveCapacity=o.capacity;r.capacityUtilization=o.capacity>0?clamp(units/o.capacity,0,1):0;r.lostDemand=Math.max(0,r.potentialDemand-units);r.revenue=revenue;r.variableCost=variableCost;r.contributionMargin=revenue-variableCost;r.contributionMarginRate=revenue>0?r.contributionMargin/revenue:0;r.marketShare=potential>0?clamp(units/potential,0,1):0;r.customerSatisfaction=o.customerSatisfaction;r.repeatRate=o.repeatRate;r.price=o.price;r.quality=o.quality;r.brandAwareness=o.brandAwareness;r.brandTrust=o.brandTrust;r.convenience=o.convenience;r.serviceQuality=o.serviceQuality;r.novelty=o.novelty;if(o.workforceAdjustment)Object.assign(r,o.workforceAdjustment);r.reasons=buildReasons(state,r,results,avgPrice);delete r.offer;results.ownUnitsSold+=units;results.ownPotentialDemand+=r.potentialDemand;}results.ownMarketShare=potential>0?clamp(results.ownUnitsSold/potential,0,1):0;return validateMarketResult(results);}
function buildReasons(state,r,m,avgPrice){const out=[];out.push({label:'市場規模',value:m.marketPotential});out.push({label:'価格競争力',value:(avgPrice-r.price)/Math.max(1,avgPrice)});out.push({label:'品質',value:(r.quality-50)/50});out.push({label:'ブランド・広告認知',value:(r.brandAwareness-40)/60});out.push({label:'競合',value:-Math.min(.35,m.competitors.length*.03)});out.push({label:'販売能力不足',value:r.potentialDemand>0?-r.lostDemand/r.potentialDemand:0});out.push({label:'顧客満足度',value:(r.customerSatisfaction-50)/50});out.push({label:'リピート',value:r.repeatRate});out.push({label:'景気',value:finite(state.economy,1)-1});return out.filter(x=>Number.isFinite(x.value));}
function calculateMarkets(state){const groups=groupTargetStores(state.stores);const result={byMarket:{},byStore:{},businessSummary:{},calculationCount:0};for(const stores of Object.values(groups)){const m=calculateMarket(state,stores);result.byMarket[m.marketKey]=m;result.calculationCount++;for(const [id,r] of Object.entries(m.stores))result.byStore[id]=r;}const seen={};for(const m of Object.values(result.byMarket)){const b=result.businessSummary[m.businessID]||(result.businessSummary[m.businessID]={businessID:m.businessID,unitsSold:0,marketPotential:0,marketShare:0});b.unitsSold+=m.ownUnitsSold;if(!seen[m.marketKey]){b.marketPotential+=m.marketPotential;seen[m.marketKey]=true;}}for(const b of Object.values(result.businessSummary))b.marketShare=b.marketPotential>0?clamp(b.unitsSold/b.marketPotential,0,1):0;return result;}
function validateMarketResult(result){function walk(v){if(typeof v==='number'&&!Number.isFinite(v))throw new Error('Invalid market number');if(v&&typeof v==='object')for(const x of Object.values(v))walk(x);}walk(result);return result;}
Object.assign(exports,{TARGET_BUSINESS_IDS,SEGMENTS,isTargetBusinessID,validateSegments,prefAreaID,marketKey,effectiveCapacity,storeOffer,competitorOffers,marketPotential,utility,calculateMarket,calculateMarkets,validateMarketResult});
})(__modules.market={});
})();
