// PE mode Phase 1 components. Production internals are intentionally hidden by peUIAdapter.
(function(){'use strict';
const adapter=globalThis.CapitalismTycoonPEUIAdapter;if(!adapter)throw new Error('pe-ui-adapter.js must load before pe-ui.js.');
let view='fund',selectedDealId=null,draftTerm=false,draftPrice=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>`${(Number(v||0)/100000000).toLocaleString('ja-JP',{maximumFractionDigits:2})}億円`;
function navButton(row){return `<button type="button" class="d-nav-button${view===row[0]?' active':''}" data-pe-view="${row[0]}" aria-current="${view===row[0]?'page':'false'}"><span>${row[1]}</span><b>${row[2]}</b><i aria-hidden="true"></i></button>`;}
function installNavigation(model){const sidebar=document.querySelector('#d-ui-sidebar nav'),dock=document.getElementById('d-ui-dock');if(sidebar)sidebar.innerHTML=model.navigation.map(navButton).join('');if(dock)dock.innerHTML=model.navigation.map(navButton).join('');const grid=document.querySelector('#d-ui-command-menu .d-command-grid');if(grid&&!grid.querySelector('[data-pe-pillars]'))grid.insertAdjacentHTML('afterbegin',`<section class="d-command-group" data-pe-pillars><h3>既存事業</h3>${[['business','▣','ラーメン・コンビニ・ジム'],['venture','◆','プロダクト事業'],['business','⌂','不動産仲介']].map(row=>`<button type="button" class="d-nav-button" data-d-ui-tab="${row[0]}"><span>${row[1]}</span><b>${row[2]}</b></button>`).join('')}</section>`);}
function deadline(m){return `<aside class="pe-deadline ${esc(m.investmentPeriod.severity)}" aria-label="投資期間の締め切り"><span>投資期間終了まで</span><strong>あと ${m.investmentPeriod.weeksRemaining}週</strong><span>未投資 ${esc(m.capital.undeployedLabel)}</span></aside>`;}
function decisionCard(item){return `<article class="pe-decision ${esc(item.urgency)}"><div><small>${esc(item.eyebrow)}</small><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p></div>${item.action?`<button class="btn ${item.priority<=2?'primary':'secondary'}" type="button" data-pe-decision="${esc(item.action.id)}" data-pe-deal="${esc(item.action.dealId||'')}">${esc(item.action.label)}</button>`:''}</article>`;}
function fundView(model){const m=model.dashboard;if(!m?.fund)return `<div class="pe-page"><section class="pe-empty"><strong>ファンドはまだ組成されていません</strong><p>実績をもとにFund Iを組成すると資本配分画面が始まります。</p></section></div>`;return `<div class="pe-page" data-pe-view-root="fund">${deadline(m)}<header class="pe-fund-identity"><div><small>ACTIVE FUND</small><h2>Fund ${m.fund.ordinal}</h2><p>${esc(m.fund.name)}</p></div><strong>${esc(m.fund.sizeLabel)}</strong><button class="pe-menu-access" type="button" data-d-ui-action="toggle-menu" aria-label="既存事業メニューを開く">☰</button></header><section class="pe-kpi-grid" aria-label="ファンド主要指標">${[['未投資資金',m.capital.undeployedLabel,`残り${m.investmentPeriod.weeksRemaining}週`],['残りスロット',`${m.slots.remaining}件`,`最大${m.slots.total}件`],['残りDD',`${m.diligence.remaining}件`,`${m.diligence.used}/${m.diligence.total}使用`],['DPI',`${m.performance.dpi.toFixed(2)}x`,`次号条件 ${m.performance.nextFundDpiGate.toFixed(2)}x`]].map(x=>`<article class="pe-kpi"><span>${x[0]}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></article>`).join('')}</section><section class="pe-war-room"><div class="pe-section-head"><div><small>FUND WAR ROOM</small><h2>今週の判断</h2></div><span class="pe-status ${m.performance.nextFundEligible?'good':'risk'}">${m.performance.nextFundEligible?'次号条件を達成':'次号条件まで実績が必要'}</span></div><p class="pe-gate">次号条件：DPI ${m.performance.nextFundDpiGate.toFixed(2)}x以上 ＋ 資金消化 ${(m.performance.deploymentGate*100).toFixed(0)}%以上（現在 ${(m.capital.deploymentRatio*100).toFixed(0)}%）</p>${m.decisions.length?`<div class="pe-decisions">${m.decisions.map(decisionCard).join('')}</div>`:`<div class="pe-empty compact"><strong>今週の重要な判断はありません</strong><p>次の案件機会を待っています。</p></div>`}<button class="btn primary pe-main-cta" type="button" data-pe-view="deals">案件を見る</button></section></div>`;}
function dealCard(d){const action=d.availableActions[0],range=d.valuation;return `<article class="pe-deal-card" data-deal-id="${esc(d.id)}"><header><span class="pe-status">${esc(d.stage.label)}</span><strong class="pe-countdown">残り${d.deadline.weeksRemaining}週</strong></header><h2>${esc(d.title)}</h2><p>${esc(d.industry)} · ${esc(d.sellerType.label)}</p><section class="pe-seller-wants"><b>★ 売り手が重視</b><strong>${esc(d.sellerPriorities[0].label)}</strong></section><div class="pe-participants"><b>参加者</b>${d.participants.length?`<ul>${d.participants.map(p=>`<li>● ${esc(p.name)}</li>`).join('')}</ul>`:'<span>競合参加者なし</span>'}</div><footer><span>${range?`推奨 ${money(range.minimum)}〜${money(range.maximum)}`:'DD開始前'}</span><button class="btn primary" type="button" data-pe-deal-action="${esc(action.id)}" data-pe-deal="${esc(d.id)}">${esc(action.label)}</button></footer></article>`;}
function dealsView(model){return `<div class="pe-page" data-pe-view-root="deals"><header class="pe-page-head"><div><small>LIMITED PIPELINE · 年4件</small><h1>案件ボード</h1><p>期限が近い案件から表示しています。見送る判断にも次の機会というコストがあります。</p></div><button class="pe-menu-access" type="button" data-d-ui-action="toggle-menu" aria-label="既存事業メニューを開く">☰</button></header>${model.deals.length?`<div class="pe-deal-grid">${model.deals.map(dealCard).join('')}</div>`:`<section class="pe-empty"><strong>現在検討できる案件はありません</strong><p>次の案件機会を待っています。</p></section>`}</div>`;}
function bidView(model){const d=model.bid;if(!d?.valuation){view='deals';return dealsView(model);}if(draftPrice===null)draftPrice=d.valuation.minimum;return `<div class="pe-bid-screen" data-pe-view-root="bid"><header><button type="button" class="pe-back" data-pe-view="deals" aria-label="案件ボードへ戻る">‹</button><div><small>${esc(d.title)}</small><h1>最終入札</h1></div><span class="pe-countdown">残り${d.deadline.weeksRemaining}週</span></header><section class="pe-seller-wants primary"><b>★ 売り手が最も重視</b><strong>${esc(d.sellerPriorities[0].label)}</strong></section><section class="pe-range"><span>評価 / 推奨レンジ</span><strong>${money(d.valuation.minimum)} 〜 ${money(d.valuation.maximum)}</strong>${d.valuation.termDiscount>0?`<em>条件効果 −${money(d.valuation.termDiscount)}</em>`:'<small>DDの進捗を反映</small>'}</section><label class="pe-term${d.availableTerms.length?'':' unavailable'}"><input type="checkbox" data-pe-term ${draftTerm?'checked':''} ${d.availableTerms.length?'':'disabled'}><span><b>${d.availableTerms.length?esc(d.availableTerms[0].label):'適用できる付帯条件はありません'}</b><small>${d.availableTerms.length?'同じ競争力を、より低い価格で提示':'価格による判断が必要です'}</small></span></label><label class="pe-price"><span>入札価格</span><output>${money(draftPrice)}</output><input type="range" data-pe-price min="${Math.max(0,Math.round(d.valuation.minimum*.8))}" max="${Math.max(1,Math.round(d.valuation.maximum*1.2))}" step="1000000" value="${Math.round(draftPrice)}"></label><div class="pe-decision-row"><button class="btn primary" type="button" data-pe-submit>入札する</button><button class="btn secondary" type="button" data-pe-drop>降りる</button></div></div>`;}
function neutral(label){return `<div class="pe-page"><section class="pe-empty"><strong>${label}</strong><p>この画面は次のUIフェーズで実装します。現在のproduction stateは変更されません。</p></section></div>`;}
function render(){const model=adapter.getPEUIData({dealId:selectedDealId,acceptSellerTerm:draftTerm});if(!model.unlocked)return false;installNavigation(model);const screen=document.getElementById('screen');if(!screen)return false;screen.classList.add('pe-active');screen.innerHTML=view==='fund'?fundView(model):view==='deals'?dealsView(model):view==='bid'?bidView(model):neutral({portfolio:'保有',network:'人脈',record:'記録'}[view]);return true;}
function selectView(next){view=next;selectedDealId=next==='deals'?null:selectedDealId;draftTerm=false;draftPrice=null;render();}
document.addEventListener('click',event=>{const v=event.target.closest('[data-pe-view]');if(v){event.preventDefault();selectView(v.dataset.peView);return;}const decision=event.target.closest('[data-pe-decision]');if(decision){event.preventDefault();const action=decision.dataset.peDecision,id=decision.dataset.peDeal;if(action==='deals')selectView('deals');else if(action==='bid'){selectedDealId=id;view='bid';render();}else{adapter.perform(action,{dealId:id});render();}return;}const deal=event.target.closest('[data-pe-deal-action]');if(deal){event.preventDefault();const action=deal.dataset.peDealAction,id=deal.dataset.peDeal;if(action==='bid'){selectedDealId=id;view='bid';draftTerm=false;draftPrice=null;}else adapter.perform(action,{dealId:id});render();return;}if(event.target.closest('[data-pe-submit]')){event.preventDefault();if(adapter.perform('bid',{dealId:selectedDealId,price:draftPrice,acceptSellerTerm:draftTerm})!==false)selectView('deals');else render();return;}if(event.target.closest('[data-pe-drop]')){event.preventDefault();if(adapter.perform('drop',{dealId:selectedDealId})!==false)selectView('deals');else render();}},true);
document.addEventListener('input',event=>{if(event.target.matches('[data-pe-term]')){draftTerm=event.target.checked;draftPrice=null;render();}else if(event.target.matches('[data-pe-price]')){draftPrice=Number(event.target.value);const output=document.querySelector('.pe-price output');if(output)output.textContent=money(draftPrice);}});
globalThis.CapitalismTycoonPEUI=Object.freeze({render});
})();
