// PE mode Phase 1 UI: read-only adapters plus D UI shell integration.
(function(){'use strict';
const modules=globalThis.__capitalismTycoonModules;if(!modules?.peFund||!modules?.maDealRoom)throw new Error('PE production modules must load before pe-ui.js.');
const pf=modules.peFund,ma=modules.maDealRoom,bridge=modules.playerEngineBridge,ACTIVE=new Set([...ma.activeStatuses()]);
const NAV=[['fund','◫','ファンド'],['deals','◇','案件'],['portfolio','▦','保有'],['network','◎','人脈'],['record','▤','記録']];
let view='fund',selectedDealID=null,draftTerm=false,draftPrice=null;
const finite=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>modules.dUIShell?.money?.(v)||`${Math.round(finite(v)).toLocaleString('ja-JP')}円`;
function isUnlocked(state){return Boolean(state?.peFirm?.unlocked);}
function activeFund(state){const funds=state?.peFirm?.funds||[];return [...funds].reverse().find(f=>f.status!=='closed')||funds[funds.length-1]||null;}
function targetFor(state,deal){return state.acquisitionTargets?.find(t=>t.id===deal?.targetID)||null;}
function seller(state,deal){const target=targetFor(state,deal),type=ma.SELLER_TYPES[target?.sellerType];return {target,type,wants:type?.wants||'価格条件',term:type?.termLabel||null};}
function liveDeals(state){const rooms=(state.maDealRooms||[]).filter(d=>ACTIVE.has(d.status)&&targetFor(state,d)?.peTierID),opened=new Set(rooms.map(d=>d.targetID)),available=(state.acquisitionTargets||[]).filter(t=>t.peTierID&&!opened.has(t.id)&&t.dealStatus!=='withdrawn'&&finite(t.expiresWeek)>=finite(state.week)).map(t=>({id:`target:${t.id}`,targetID:t.id,status:'available',deadlineWeek:t.expiresWeek,competingBids:[]}));return rooms.concat(available).sort((a,b)=>finite(a.deadlineWeek)-finite(b.deadlineWeek)||String(a.id).localeCompare(String(b.id)));}
function buildFundModel(state){const fund=activeFund(state);if(!fund)return {fund:null,deals:liveDeals(state)};const remaining=Math.max(0,finite(fund.investmentDeadlineWeek)-finite(state.week)),deployed=pf.fundDeployed(fund),dpi=pf.fundDPI(fund),deployment=pf.fundDeploymentRate(fund),requiredDeployment=pf.requiredDeploymentRate(fund);return {fund,remaining,undeployed:Math.max(0,finite(fund.cash)),slots:Math.max(0,pf.slotCapacity(fund)-pf.activeDealCount(fund)),dd:pf.ddSlotsRemaining(state,state.week),dpi,deployed,deployment,requiredDeployment,canAdvance:dpi>=pf.NEXT_FUND_MIN_DPI&&deployment>=requiredDeployment,deals:liveDeals(state)};}
function buildDealModel(state,deal){const s=seller(state,deal),range=s.target?ma.recommendedOfferRange(state,s.target,deal,{acceptSellerTerm:false}):null;return {deal,...s,range,remaining:Math.max(0,finite(deal.deadlineWeek)-finite(state.week)),participants:(deal.competingBids||[]).filter(b=>b.status==='active').map(b=>({id:b.bidderID,name:b.bidderName}))};}
function buildBidModel(state,dealID,{acceptSellerTerm=false}={}){const deal=(state.maDealRooms||[]).find(d=>d.id===dealID),base=deal&&buildDealModel(state,deal);if(!base?.target)return null;return {...base,acceptSellerTerm:Boolean(acceptSellerTerm&&base.term),range:ma.recommendedOfferRange(state,base.target,deal,{acceptSellerTerm:Boolean(acceptSellerTerm&&base.term)})};}
function navButton(row){return `<button type="button" class="d-nav-button${view===row[0]?' active':''}" data-pe-view="${row[0]}" aria-current="${view===row[0]?'page':'false'}"><span>${row[1]}</span><b>${row[2]}</b><i aria-hidden="true"></i></button>`;}
function installNavigation(state){if(!isUnlocked(state))return;const sidebar=document.querySelector('#d-ui-sidebar nav'),dock=document.getElementById('d-ui-dock');if(sidebar)sidebar.innerHTML=NAV.map(navButton).join('');if(dock)dock.innerHTML=NAV.map(navButton).join('');const grid=document.querySelector('#d-ui-command-menu .d-command-grid');if(grid&&!grid.querySelector('[data-pe-pillars]'))grid.insertAdjacentHTML('afterbegin',`<section class="d-command-group" data-pe-pillars><h3>既存事業</h3>${[['business','▣','ラーメン・コンビニ・ジム'],['venture','◆','プロダクト事業'],['business','⌂','不動産仲介']].map(row=>`<button type="button" class="d-nav-button" data-d-ui-tab="${row[0]}"><span>${row[1]}</span><b>${row[2]}</b></button>`).join('')}</section>`);}
function deadline(model){const level=model.remaining<=26?'critical':model.remaining<=52?'warning':'normal';return `<aside class="pe-deadline ${level}" aria-label="投資期間の締め切り"><span>投資期間終了まで</span><strong>あと ${model.remaining}週</strong><span>未投資 ${money(model.undeployed)}</span></aside>`;}
function fundView(state){const m=buildFundModel(state);if(!m.fund)return `<div class="pe-page"><section class="pe-empty"><strong>ファンドはまだ組成されていません</strong><p>実績をもとにFund Iを組成すると資本配分画面が始まります。</p></section></div>`;const index=(state.peFirm.funds||[]).indexOf(m.fund)+1,actions=m.deals.slice(0,2);return `<div class="pe-page" data-pe-view-root="fund">${deadline(m)}<header class="pe-fund-identity"><div><small>ACTIVE FUND</small><h2>Fund ${index}</h2><p>${esc(m.fund.name||'Japan Growth Buyout Fund')}</p></div><strong>${money(m.fund.size)}</strong><button class="pe-menu-access" type="button" data-d-ui-action="toggle-menu" aria-label="既存事業メニューを開く">☰</button></header><section class="pe-kpi-grid" aria-label="ファンド主要指標">${[['未投資資金',money(m.undeployed),`残り${m.remaining}週`],['残りスロット',`${m.slots}件`,`最大${pf.slotCapacity(m.fund)}件`],['残りDD',`${m.dd}件`,'今年利用可能'],['DPI',`${m.dpi.toFixed(2)}x`,`次号条件 ${pf.NEXT_FUND_MIN_DPI.toFixed(2)}x`]].map(x=>`<article class="pe-kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}</section><section class="pe-war-room"><div class="pe-section-head"><div><small>FUND WAR ROOM</small><h2>今週の判断</h2></div><span class="pe-status ${m.canAdvance?'good':'risk'}">${m.canAdvance?'次号条件を達成':'次号条件まで実績が必要'}</span></div><p class="pe-gate">次号条件：DPI ${pf.NEXT_FUND_MIN_DPI.toFixed(2)}x以上 ＋ 資金消化 ${(m.requiredDeployment*100).toFixed(0)}%以上（現在 ${(m.deployment*100).toFixed(0)}%）</p>${actions.length?actions.map(d=>{const x=buildDealModel(state,d);return `<button class="pe-action-row" data-pe-view="deals"><span><b>${esc(x.target.name)}</b><small>${x.remaining}週 · ${esc(ma.STATUS_LABELS[d.status]||d.status)}</small></span><strong>判断する ›</strong></button>`;}).join(''):`<div class="pe-empty compact"><strong>今週判断できる案件はありません</strong><p>次の案件機会を待っています。</p></div>`}<button class="btn primary pe-main-cta" type="button" data-pe-view="deals">案件を見る</button></section></div>`;}
function dealAction(deal){return deal.status==='available'?['open','詳細を見る']:deal.status==='screening'?['advance','意向表明へ']:deal.status==='indication'?['dd','DDへ']:deal.status==='ready'?['advance','最終入札へ']:['bid','最終入札'];}
function dealCard(state,deal){const x=buildDealModel(state,deal),action=dealAction(deal);return `<article class="pe-deal-card" data-deal-id="${esc(deal.id)}"><header><span class="pe-status">${esc(ma.STATUS_LABELS[deal.status]||deal.status)}</span><strong class="pe-countdown">残り${x.remaining}週</strong></header><h2>${esc(x.target.name)}</h2><p>${esc(x.target.industry||x.target.type||x.target.peTierID||'事業会社')} · ${esc(x.type?.name||'売り手')}</p><section class="pe-seller-wants"><b>★ 売り手が重視</b><strong>${esc(x.wants)}</strong></section><div class="pe-participants"><b>参加者</b>${x.participants.length?`<ul>${x.participants.map(p=>`<li>● ${esc(p.name)}</li>`).join('')}</ul>`:'<span>競合参加者なし</span>'}</div><footer><span>${x.range?`推奨 ${money(x.range.recommendedMinimumPrice)}〜${money(x.range.recommendedMaximumPrice)}`:'DD開始前'}</span><button class="btn primary" type="button" data-pe-deal="${esc(deal.id)}" data-pe-deal-action="${action[0]}">${action[1]}</button></footer></article>`;}
function dealsView(state){const deals=liveDeals(state);return `<div class="pe-page" data-pe-view-root="deals"><header class="pe-page-head"><small>LIMITED PIPELINE · 年4件</small><h1>案件ボード</h1><p>期限が近い案件から表示しています。見送る判断にも次の機会というコストがあります。</p></header>${deals.length?`<div class="pe-deal-grid">${deals.map(d=>dealCard(state,d)).join('')}</div>`:`<section class="pe-empty"><strong>現在検討できる案件はありません</strong><p>次の案件機会を待っています。</p></section>`}</div>`;}
function bidView(state){const m=buildBidModel(state,selectedDealID,{acceptSellerTerm:draftTerm});if(!m){view='deals';return dealsView(state);}if(draftPrice===null)draftPrice=m.range.recommendedMinimumPrice;const base=ma.recommendedOfferRange(state,m.target,m.deal,{acceptSellerTerm:false}),delta=base.recommendedMinimumPrice-m.range.recommendedMinimumPrice;return `<div class="pe-bid-screen" data-pe-view-root="bid"><header><button type="button" class="pe-back" data-pe-view="deals" aria-label="案件ボードへ戻る">‹</button><div><small>${esc(m.target.name)}</small><h1>最終入札</h1></div><span class="pe-countdown">残り${m.remaining}週</span></header><section class="pe-seller-wants primary"><b>★ 売り手が最も重視</b><strong>${esc(m.wants)}</strong></section><section class="pe-range"><span>評価 / 推奨レンジ</span><strong>${money(m.range.recommendedMinimumPrice)} 〜 ${money(m.range.recommendedMaximumPrice)}</strong>${delta>0?`<em>条件効果 −${money(delta)}</em>`:'<small>DDの進捗を反映</small>'}</section><label class="pe-term${m.term?'':' unavailable'}"><input type="checkbox" data-pe-term ${draftTerm?'checked':''} ${m.term?'':'disabled'}><span><b>${m.term?esc(m.term):'適用できる付帯条件はありません'}</b><small>${m.term?'同じ競争力を、より低い価格で提示':'価格による判断が必要です'}</small></span></label><label class="pe-price"><span>入札価格</span><output>${money(draftPrice)}</output><input type="range" data-pe-price min="${Math.max(0,Math.round(m.range.recommendedMinimumPrice*.8))}" max="${Math.max(1,Math.round(m.range.recommendedMaximumPrice*1.2))}" step="1000000" value="${Math.round(draftPrice)}"></label><div class="pe-decision-row"><button class="btn primary" type="button" data-pe-submit>入札する</button><button class="btn secondary" type="button" data-pe-drop>降りる</button></div></div>`;}
function neutral(label){return `<div class="pe-page"><section class="pe-empty"><strong>${label}</strong><p>この画面は次のUIフェーズで実装します。現在のproduction stateは変更されません。</p></section></div>`;}
function render(state){installNavigation(state);if(!isUnlocked(state))return false;const screen=document.getElementById('screen');if(!screen)return false;screen.classList.add('pe-active');screen.innerHTML=view==='fund'?fundView(state):view==='deals'?dealsView(state):view==='bid'?bidView(state):neutral({portfolio:'保有',network:'人脈',record:'記録'}[view]);return true;}
function refresh(){const e=bridge?.getEngine?.();if(e?.g)render(e.g);}
function chooseDeal(id){selectedDealID=id;draftTerm=false;draftPrice=null;view='bid';refresh();}
document.addEventListener('click',event=>{const e=bridge?.getEngine?.(),state=e?.g;if(!isUnlocked(state))return;const v=event.target.closest('[data-pe-view]');if(v){event.preventDefault();view=v.dataset.peView;selectedDealID=view==='deals'?null:selectedDealID;draftTerm=false;draftPrice=null;refresh();return;}const deal=event.target.closest('[data-pe-deal]');if(deal){event.preventDefault();const id=deal.dataset.peDeal,action=deal.dataset.peDealAction||'bid';if(action==='open'){const targetID=id.replace(/^target:/,'');if(e.openMADealRoom(targetID)!==false)refresh();}else if(action==='advance'){e.advanceMADealRound(id);refresh();}else if(action==='dd'){e.startMADueDiligence(id,'financial');refresh();}else chooseDeal(id);return;}if(event.target.closest('[data-pe-submit]')){event.preventDefault();if(e.submitMAOffer(selectedDealID,{method:'friendly',offerPrice:draftPrice,acceptSellerTerm:draftTerm})!==false){view='deals';selectedDealID=null;}refresh();return;}if(event.target.closest('[data-pe-drop]')){event.preventDefault();if(e.withdrawMADeal(selectedDealID)!==false){view='deals';selectedDealID=null;}refresh();}},true);
document.addEventListener('input',event=>{if(event.target.matches('[data-pe-term]')){draftTerm=event.target.checked;const e=bridge.getEngine(),m=buildBidModel(e.g,selectedDealID,{acceptSellerTerm:draftTerm});draftPrice=m?.range.recommendedMinimumPrice??draftPrice;refresh();}else if(event.target.matches('[data-pe-price]')){draftPrice=finite(event.target.value);const output=document.querySelector('.pe-price output');if(output)output.textContent=money(draftPrice);}});
modules.uiEnhancerRegistry.registerUIEnhancer({id:'pe-ui-phase1',enhance:({engine})=>render(engine.g)});
modules.peUI=Object.freeze({NAV,isUnlocked,activeFund,liveDeals,buildFundModel,buildDealModel,buildBidModel,render,__installed:true});
})();
