// Real estate management: rental operation, regional markets, vacancy, repairs, events and collateral financing.
(function(){'use strict';
const modules=globalThis.__capitalismTycoonModules;
if(!modules?.engine?.TycoonEngine)throw new Error('engine.js must be loaded before real-estate.js.');
if(modules.realEstate)throw new Error('real estate module is already registered.');
const Engine=modules.engine.TycoonEngine,finance=modules.finance;
const VERSION=3,HISTORY_LIMIT=300;
const REGIONS=Object.freeze({urban_core:{label:'都心中核',demand:1.12,rent:1.16,land:1.18,volatility:1.15,risk:.8},suburban:{label:'郊外住宅地',demand:1.02,rent:1,land:1.01,volatility:.75,risk:.7},regional_city:{label:'地方都市',demand:.9,rent:.88,land:.86,volatility:.8,risk:.9},resort:{label:'観光・リゾート',demand:.96,rent:1.08,land:1.03,volatility:1.4,risk:1.15},logistics_hub:{label:'物流結節点',demand:1.06,rent:1.04,land:1.08,volatility:.85,risk:.75}});
const PROPERTY_TYPES=Object.freeze({apartment:{label:'賃貸住宅',demand:1.04,rent:.98,maintenance:.9,shock:.8},office:{label:'オフィス',demand:.96,rent:1.1,maintenance:1.05,shock:1.1},retail:{label:'商業施設',demand:1,rent:1.08,maintenance:1.12,shock:1.2},logistics:{label:'物流施設',demand:1.06,rent:1.02,maintenance:.92,shock:.75},hotel:{label:'宿泊施設',demand:.92,rent:1.18,maintenance:1.2,shock:1.35},headquarters:{label:'本社・自社利用',demand:0,rent:0,maintenance:1,shock:.9},land:{label:'土地',demand:0,rent:0,maintenance:.3,shock:.4}});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const round=v=>Math.round(n(v)*100)/100;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,n(v,min)));
function hash01(id,week,salt=''){let h=2166136261;for(const c of `${id}:${week}:${salt}`){h^=c.codePointAt(0);h=Math.imul(h,16777619);}return (h>>>0)/4294967295;}
function inferType(p){const text=String(p?.buildingType||p?.kind||p?.name||'');if(/本社/.test(text))return'headquarters';if(/マンション|アパート|住宅/.test(text))return'apartment';if(/ホテル|旅館|宿泊/.test(text))return'hotel';if(/物流|倉庫/.test(text))return'logistics';if(/商業|店舗|モール/.test(text))return'retail';if(/ビル|オフィス/.test(text))return'office';return p?.buildingType?'office':'land';}
function inferRegion(p){const text=String(p?.region||p?.area||p?.location||p?.name||'');if(/都心|東京|大阪|中心/.test(text))return'urban_core';if(/観光|リゾート|温泉/.test(text))return'resort';if(/物流|港|空港|工業/.test(text))return'logistics_hub';if(/地方|田舎/.test(text))return'regional_city';return'suburban';}
function splitBase(p){const total=Math.max(1,n(p.purchasePrice,p.price||p.value)),existingLand=n(p.landPurchasePrice,p.landValue),existingBuilding=n(p.buildingPurchasePrice,p.buildingValue||p.buildingCost);if(existingLand>0||existingBuilding>0){const sum=Math.max(1,existingLand+existingBuilding);return {land:round(total*existingLand/sum),building:round(total*existingBuilding/sum)};}const buildingShare=p.buildingType?clamp(n(p.buildingShare,.55),.2,.8):0;return {land:round(total*(1-buildingShare)),building:round(total*buildingShare)};}
function ensureProperty(p){if(!p.realEstate||typeof p.realEstate!=='object')p.realEstate={};const x=p.realEstate,base=splitBase(p);x.rentalEnabled=Boolean(x.rentalEnabled);x.monthlyRent=Math.max(0,n(x.monthlyRent));x.targetOccupancy=clamp(x.targetOccupancy,.2,1);x.occupancy=clamp(x.occupancy,0,1);x.condition=clamp(x.condition,.2,1);x.repairReserve=Math.max(0,n(x.repairReserve));x.landBookValue=Math.max(0,n(x.landBookValue,base.land));x.buildingBookValue=Math.max(0,n(x.buildingBookValue,base.building));x.landValue=Math.max(0,n(x.landValue,x.landBookValue));x.buildingValue=Math.max(0,n(x.buildingValue,x.buildingBookValue));x.lastIncome=n(x.lastIncome);x.lastExpense=n(x.lastExpense);x.lastNetIncome=n(x.lastNetIncome);x.lastValuation=Math.max(0,n(x.lastValuation,x.landValue+x.buildingValue));if(!REGIONS[x.regionID])x.regionID=inferRegion(p);if(!PROPERTY_TYPES[x.propertyTypeID])x.propertyTypeID=inferType(p);if(!Array.isArray(x.marketEffects))x.marketEffects=[];x.marketEffects=x.marketEffects.filter(e=>e&&Number.isFinite(e.untilWeek)&&e.untilWeek>=0).slice(-12);x.marketDemandMultiplier=clamp(x.marketDemandMultiplier,0.4,1.8);x.marketRentMultiplier=clamp(x.marketRentMultiplier,0.4,2);x.marketLandMultiplier=clamp(x.marketLandMultiplier,0.4,2);return x;}
function ensure(state){if(!state.realEstate||typeof state.realEstate!=='object')state.realEstate={};const r=state.realEstate;if(!Array.isArray(r.ledger))r.ledger=[];if(!Array.isArray(r.loans))r.loans=[];if(!Array.isArray(r.sales))r.sales=[];if(!Array.isArray(r.marketEvents))r.marketEvents=[];r.marketEvents=r.marketEvents.slice(-HISTORY_LIMIT);if(!Number.isFinite(r.lastProcessedWeek))r.lastProcessedWeek=0;if(!Number.isFinite(r.lastMarketProcessedWeek))r.lastMarketProcessedWeek=0;r.schemaVersion=VERSION;r.marketSchemaVersion=1;for(const p of Array.isArray(state.properties)?state.properties:[])ensureProperty(p);for(const loan of r.loans){loan.principal=Math.max(0,n(loan.principal));loan.outstandingPrincipal=Math.max(0,n(loan.outstandingPrincipal,loan.principal));loan.interestRate=clamp(loan.interestRate,0,.25);loan.remainingWeeks=Math.max(0,Math.floor(n(loan.remainingWeeks)));loan.status=loan.outstandingPrincipal>0&&loan.status!=='defaulted'?'active':loan.status||'paid';}return r;}
function activeEffect(p,week){const x=ensureProperty(p),effects=x.marketEffects.filter(e=>e.untilWeek>=week);x.marketEffects=effects;return effects.reduce((a,e)=>({demand:a.demand*n(e.demand,1),rent:a.rent*n(e.rent,1),land:a.land*n(e.land,1)}),{demand:1,rent:1,land:1});}
function marketProfile(p,week=1){const x=ensureProperty(p),region=REGIONS[x.regionID],type=PROPERTY_TYPES[x.propertyTypeID],effect=activeEffect(p,week);return {regionID:x.regionID,regionLabel:region.label,propertyTypeID:x.propertyTypeID,propertyTypeLabel:type.label,demandMultiplier:round(region.demand*type.demand*effect.demand),rentMultiplier:round(region.rent*type.rent*effect.rent),landMultiplier:round(region.land*effect.land),maintenanceMultiplier:type.maintenance,shockMultiplier:region.risk*type.shock,volatility:region.volatility,activeEffects:x.marketEffects.map(e=>({...e}))};}
function rentable(p){return Boolean(p?.owner&&p?.buildingType&&p.buildingType!=='本社ビル'&&ensureProperty(p).propertyTypeID!=='headquarters');}
function valuationParts(p,week){const x=ensureProperty(p),location=clamp(n(p.locationScore,p.demandScore||1),.4,1.8),landCycle=(hash01(p.id,Math.floor(week/13),'land')-.5)*.05,buildingCycle=(hash01(p.id,Math.floor(week/13),'building')-.5)*.025,land=round(Math.max(0,x.landBookValue*(.94+location*.06)*(1+landCycle))),building=round(Math.max(0,x.buildingBookValue*(1+buildingCycle)*(.55+x.condition*.45)));return {land,building,total:round(land+building)};}
function securedOutstanding(state,propertyID){return (state.realEstate?.loans||[]).filter(l=>l.propertyID===propertyID&&l.status==='active').reduce((a,l)=>a+n(l.outstandingPrincipal),0);}
function collateralCapacity(state,p){const x=ensureProperty(p),gross=round((x.landValue+x.buildingValue)*.7),used=securedOutstanding(state,p.id);return {gross,used,available:Math.max(0,round(gross-used))};}
function record(state,p,row){state.realEstate.ledger.push(row);if(state.realEstate.ledger.length>2000)state.realEstate.ledger=state.realEstate.ledger.slice(-2000);p.realEstate.lastIncome=row.grossRent;p.realEstate.lastExpense=row.expense;p.realEstate.lastNetIncome=row.netIncome;p.realEstate.lastValuation=row.valuation;}
function processLoans(engine,week){const g=engine.g,r=ensure(g),rows=[];for(const loan of r.loans){if(loan.status!=='active'||loan.lastPaymentWeek===week)continue;const interest=round(n(loan.outstandingPrincipal)*n(loan.interestRate)/52),principal=loan.remainingWeeks>0?round(Math.min(loan.outstandingPrincipal,n(loan.outstandingPrincipal)/loan.remainingWeeks)):0,payment=round(interest+principal),cashKey=loan.owner==='company'?'companyCash':'personalCash';if(n(g[cashKey])<payment){loan.missedPayments=Math.floor(n(loan.missedPayments))+1;if(loan.missedPayments>=4)loan.status='defaulted';rows.push({loanID:loan.loanID,owner:loan.owner,interest,principal:0,payment:0,status:loan.status});continue;}g[cashKey]=round(n(g[cashKey])-payment);loan.outstandingPrincipal=round(Math.max(0,n(loan.outstandingPrincipal)-principal));loan.remainingWeeks=Math.max(0,loan.remainingWeeks-1);loan.lastPaymentWeek=week;loan.missedPayments=0;if(loan.outstandingPrincipal<=0)loan.status='paid';if(loan.owner==='company'){g.companyDebt=round(Math.max(0,n(g.companyDebt)-principal));if(interest>0)finance?.event?.(g,'interestExpense',interest,{cashEffect:-interest,profitEffect:-interest,sourceType:'property-collateral-interest',sourceID:loan.loanID,idempotencyKey:`property-loan-interest-${loan.loanID}-w${week}`,description:'不動産担保融資 利息'});if(principal>0)finance?.event?.(g,'debtRepayment',principal,{cashEffect:-principal,liabilityEffect:-principal,sourceType:'property-collateral-principal',sourceID:loan.loanID,idempotencyKey:`property-loan-principal-${loan.loanID}-w${week}`,description:'不動産担保融資 元本返済'});}else g.personalDebt=round(Math.max(0,n(g.personalDebt)-principal));rows.push({loanID:loan.loanID,owner:loan.owner,interest,principal,payment,status:loan.status});}return rows;}
function processWeek(engine){const g=engine.g,r=ensure(g),week=Math.floor(n(g.week,1));if(r.lastProcessedWeek===week)return[];const rows=[];for(const p of g.properties||[]){const x=ensureProperty(p),parts=valuationParts(p,week);x.landValue=parts.land;x.buildingValue=parts.building;p.value=parts.total;if(!rentable(p)||!x.rentalEnabled)continue;const profile=marketProfile(p,week),demand=.78+hash01(p.id,week,'occupancy')*.22,target=clamp(x.targetOccupancy*profile.demandMultiplier*demand,.2,1);x.occupancy=round(x.occupancy*.7+target*.3);const weeklyRent=round(x.monthlyRent*profile.rentMultiplier/4.345*x.occupancy),maintenance=round(Math.max(1000,parts.total*.00035*profile.maintenanceMultiplier)),repairChance=.025*profile.shockMultiplier,repairShock=hash01(p.id,week,'repair')<repairChance?round(Math.max(50000,parts.total*(.003+hash01(p.id,week,'repair-cost')*.007)*profile.shockMultiplier)):0,reserveUse=Math.min(x.repairReserve,repairShock);x.repairReserve=round(x.repairReserve+weeklyRent*.03-reserveUse);const cashRepair=round(repairShock-reserveUse),expense=round(maintenance+cashRepair),net=round(weeklyRent-expense);x.condition=clamp(x.condition-maintenance/Math.max(1,parts.total)*.01-repairShock/Math.max(1,parts.total)*.08+.0005,.2,1);const row={week,propertyID:p.id,owner:p.owner,regionID:x.regionID,propertyTypeID:x.propertyTypeID,grossRent:weeklyRent,maintenance,cashRepair,expense,netIncome:net,occupancy:x.occupancy,condition:x.condition,landValue:parts.land,buildingValue:parts.building,valuation:parts.total};record(g,p,row);rows.push(row);if(p.owner==='company'){g.companyCash=round(n(g.companyCash)+net);finance?.event?.(g,'revenue',weeklyRent,{cashEffect:weeklyRent,profitEffect:weeklyRent,sourceType:'property-rent',sourceID:p.id,idempotencyKey:`property-rent-${p.id}-w${week}`,description:`${p.name||p.id} 賃料収入`});if(expense>0)finance?.event?.(g,'maintenance',expense,{cashEffect:-expense,profitEffect:-expense,sourceType:'property-maintenance',sourceID:p.id,idempotencyKey:`property-maintenance-${p.id}-w${week}`,description:`${p.name||p.id} 維持修繕費`});}else if(p.owner==='personal')g.personalCash=round(n(g.personalCash)+net);}processLoans(engine,week);r.lastProcessedWeek=week;return rows;}
function eventDefinition(p,week){const profile=marketProfile(p,week),roll=hash01(p.id,week,'market-event');if(roll>.08*profile.volatility)return null;const choice=hash01(p.id,week,'market-event-kind');if(choice<.2)return{id:'transit_opening',title:'交通インフラ開通',demand:1.08,rent:1.04,land:1.1,duration:52};if(choice<.4)return{id:'redevelopment',title:'周辺再開発',demand:1.05,rent:1.05,land:1.08,duration:39};if(choice<.6)return{id:'major_employer_exit',title:'大口雇用流出',demand:.88,rent:.92,land:.9,duration:52};if(choice<.8&&profile.propertyTypeID==='hotel')return{id:'tourism_boom',title:'観光需要急増',demand:1.15,rent:1.12,land:1.03,duration:26};return{id:'storm_damage',title:'風水害による修繕',demand:.95,rent:1,land:.98,duration:13,damageRate:.004+.006*hash01(p.id,week,'damage')};}
function applyMarketEvent(engine,p,week,def){const g=engine.g,x=ensureProperty(p),value=Math.max(0,n(p.value,x.landValue+x.buildingValue)),cost=def.damageRate?round(Math.max(50000,value*def.damageRate)):0,effect={eventID:`re-${def.id}-${p.id}-w${week}`,kind:def.id,title:def.title,propertyID:p.id,week,untilWeek:week+def.duration,demand:def.demand,rent:def.rent,land:def.land,cost};x.marketEffects.push(effect);x.marketEffects=x.marketEffects.slice(-12);if(cost>0){x.condition=clamp(x.condition-cost/Math.max(1,value)*4,.2,1);const key=p.owner==='personal'?'personalCash':'companyCash';g[key]=round(n(g[key])-cost);if(p.owner==='company')finance?.event?.(g,'maintenance',cost,{cashEffect:-cost,profitEffect:-cost,sourceType:'property-market-event',sourceID:effect.eventID,idempotencyKey:effect.eventID,description:`${p.name||p.id} ${def.title}`});}g.realEstate.marketEvents.push(effect);g.realEstate.marketEvents=g.realEstate.marketEvents.slice(-HISTORY_LIMIT);return effect;}
function processMarketWeek(engine){const g=engine.g,r=ensure(g),week=Math.floor(n(g.week,1));if(r.lastMarketProcessedWeek===week)return[];const events=[];for(const p of g.properties||[]){if(!p.owner)continue;const def=eventDefinition(p,week);if(def)events.push(applyMarketEvent(engine,p,week,def));}r.lastMarketProcessedWeek=week;return events;}
Engine.prototype.enablePropertyRental=function(propertyID,options={}){const p=(this.g.properties||[]).find(x=>x.id===propertyID);if(!rentable(p))return false;ensure(this.g);p.realEstate.rentalEnabled=true;p.realEstate.monthlyRent=Math.max(10000,n(options.monthlyRent,p.realEstate.monthlyRent||n(p.value,p.price)*.004));p.realEstate.targetOccupancy=clamp(options.targetOccupancy??p.realEstate.targetOccupancy,.2,1);p.realEstate.occupancy=Math.max(p.realEstate.occupancy,.5);this.save?.();this.emit?.();return true;};
Engine.prototype.disablePropertyRental=function(propertyID){const p=(this.g.properties||[]).find(x=>x.id===propertyID);if(!p?.realEstate)return false;p.realEstate.rentalEnabled=false;this.save?.();this.emit?.();return true;};
Engine.prototype.getPropertyInvestmentMetrics=function(propertyID){const p=(this.g.properties||[]).find(x=>x.id===propertyID);if(!p)return null;ensure(this.g);const x=p.realEstate,price=Math.max(1,n(p.purchasePrice,p.price||p.value)),profile=marketProfile(p,Math.floor(n(this.g.week,1))),annualGross=x.monthlyRent*profile.rentMultiplier*12*x.targetOccupancy*profile.demandMultiplier,annualNet=annualGross-price*.0042*profile.maintenanceMultiplier,capacity=collateralCapacity(this.g,p);return {propertyID,owner:p.owner,valuation:n(p.value,price),landValue:x.landValue,buildingValue:x.buildingValue,occupancy:x.occupancy,condition:x.condition,grossYield:annualGross/price,netYield:annualNet/price,collateralValue:capacity.gross,collateralUsed:capacity.used,collateralAvailable:capacity.available,repairReserve:x.repairReserve,lastNetIncome:x.lastNetIncome,regionID:x.regionID,propertyTypeID:x.propertyTypeID,marketProfile:profile};};
Engine.prototype.getPropertyMarketProfile=function(propertyID){const p=(this.g.properties||[]).find(x=>x.id===propertyID);return p?marketProfile(p,Math.floor(n(this.g.week,1))):null;};
Engine.prototype.setPropertyMarketSegment=function(propertyID,regionID,propertyTypeID){return this.runTransaction(()=>{const p=(this.g.properties||[]).find(x=>x.id===propertyID);if(!p||!REGIONS[regionID]||!PROPERTY_TYPES[propertyTypeID])return false;const x=ensureProperty(p);x.regionID=regionID;x.propertyTypeID=propertyTypeID;return true;});};
Engine.prototype.borrowAgainstProperty=function(propertyID,amount,options={}){return this.runTransaction(()=>{const g=this.g,p=(g.properties||[]).find(x=>x.id===propertyID);if(!p?.owner)return false;ensure(g);const capacity=collateralCapacity(g,p),principal=round(Math.max(0,n(amount)));if(principal<=0||principal>capacity.available)return false;const owner=p.owner==='personal'?'personal':'company',termWeeks=Math.max(13,Math.floor(n(options.termWeeks,260))),interestRate=clamp(options.interestRate??(owner==='company'?.045:.055),.005,.25),loanID=`property-loan-${propertyID}-w${Math.floor(n(g.week,1))}-${g.realEstate.loans.length+1}`;g.realEstate.loans.push({loanID,propertyID,owner,principal,outstandingPrincipal:principal,interestRate,termWeeks,remainingWeeks:termWeeks,status:'active',originatedWeek:Math.floor(n(g.week,1)),lastPaymentWeek:0,missedPayments:0});if(owner==='company'){g.companyCash=round(n(g.companyCash)+principal);g.companyDebt=round(n(g.companyDebt)+principal);finance?.event?.(g,'debtBorrowing',principal,{cashEffect:principal,liabilityEffect:principal,sourceType:'property-collateral-borrowing',sourceID:loanID,idempotencyKey:`property-loan-origination-${loanID}`,description:`${p.name||propertyID} 担保融資`});}else{g.personalCash=round(n(g.personalCash)+principal);g.personalDebt=round(n(g.personalDebt)+principal);}return loanID;});};
Engine.prototype.repayPropertyLoan=function(loanID,amount=Infinity){return this.runTransaction(()=>{const g=this.g;ensure(g);const loan=g.realEstate.loans.find(x=>x.loanID===loanID&&x.status==='active');if(!loan)return false;const owner=loan.owner,cashKey=owner==='company'?'companyCash':'personalCash',pay=round(Math.min(n(loan.outstandingPrincipal),n(amount,loan.outstandingPrincipal),n(g[cashKey])));if(pay<=0)return false;g[cashKey]=round(n(g[cashKey])-pay);loan.outstandingPrincipal=round(n(loan.outstandingPrincipal)-pay);if(owner==='company'){g.companyDebt=round(Math.max(0,n(g.companyDebt)-pay));finance?.event?.(g,'debtRepayment',pay,{cashEffect:-pay,liabilityEffect:-pay,sourceType:'property-collateral-prepayment',sourceID:loanID,description:'不動産担保融資 繰上返済'});}else g.personalDebt=round(Math.max(0,n(g.personalDebt)-pay));if(loan.outstandingPrincipal<=0)loan.status='paid';return pay;});};
Engine.prototype.sellPropertyInvestment=function(propertyID){return this.runTransaction(()=>{const g=this.g,p=(g.properties||[]).find(x=>x.id===propertyID);if(!p?.owner||securedOutstanding(g,propertyID)>0)return false;ensure(g);const x=ensureProperty(p),owner=p.owner,landBook=x.landBookValue,buildingBook=x.buildingBookValue,book=round(landBook+buildingBook),valuation=round(x.landValue+x.buildingValue),proceeds=round(valuation*.97),ratio=valuation>0?x.landValue/valuation:(book>0?landBook/book:1),landProceeds=round(proceeds*ratio),buildingProceeds=round(proceeds-landProceeds),landGain=round(landProceeds-landBook),buildingGain=round(buildingProceeds-buildingBook);const sold=typeof this.sellProperty==='function'?this.sellProperty(propertyID):false;if(!sold)return false;const row={saleID:`property-sale-${propertyID}-w${Math.floor(n(g.week,1))}`,week:Math.floor(n(g.week,1)),propertyID,owner,landBookValue:landBook,buildingBookValue:buildingBook,landProceeds,buildingProceeds,totalProceeds:proceeds,landGain,buildingGain,totalGain:round(landGain+buildingGain)};g.realEstate.sales.push(row);g.realEstate.sales=g.realEstate.sales.slice(-500);return row;});};
const baseNormalize=Engine.prototype.normalize;Engine.prototype.normalize=function(){const result=baseNormalize.call(this);ensure(this.g);return result;};
function wrapParityWeekly(base){if(typeof base!=='function')return base;const wrapped=function(){let result;try{result=base.apply(this,arguments);}catch(error){throw error;}processWeek(this);processMarketWeek(this);return result;};Object.defineProperty(wrapped,'__realEstateWrapped',{value:true});return wrapped;}
const existingParityWeekly=Engine.prototype.updateParityWeekly;if(typeof existingParityWeekly==='function'){if(!existingParityWeekly.__realEstateWrapped)Engine.prototype.updateParityWeekly=wrapParityWeekly(existingParityWeekly);}else{Object.defineProperty(Engine.prototype,'updateParityWeekly',{configurable:true,get(){return undefined;},set(fn){Object.defineProperty(Engine.prototype,'updateParityWeekly',{value:fn?.__realEstateWrapped?fn:wrapParityWeekly(fn),writable:true,configurable:true});}});}
modules.realEstate=Object.freeze({VERSION,HISTORY_LIMIT,REGIONS,PROPERTY_TYPES,ensure,ensureProperty,processWeek,processLoans,processMarketWeek,eventDefinition,marketProfile,valuationParts,collateralCapacity,rentable});

})();
