// Phase 8C-1/8C-14: shareholder returns discipline with mutation-free read paths.
(function(){'use strict';
const modules=globalThis.__capitalismTycoonModules;
if(!modules?.engine?.TycoonEngine)throw new Error('engine.js must load before shareholder-returns.js.');
if(!modules.finance?.buildStatements)throw new Error('finance.js must load before shareholder-returns.js.');
if(modules.shareholderReturns)throw new Error('shareholder returns module is already registered.');
const EngineClass=modules.engine.TycoonEngine,finance=modules.finance;
const baseAdvanceWeek=EngineClass.prototype.advanceWeek;
const MIN_CASH=5_000_000,HISTORY_LIMIT=52,TAX_RATE=.306;
const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,finite(value,min)));
const yen=modules.engine.yen||((value)=>`${Math.round(finite(value)).toLocaleString('ja-JP')}円`);
const compactYen=modules.engine.compactYen||yen;
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function renderKey(value){let hash=2166136261;const text=String(value||'');for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(36);}
function normalizedState(raw){const result={lastActualDividend:0,lastDeclaredDividend:0,lastPaymentWeek:-1,history:[],...(raw&&typeof raw==='object'?raw:{})};result.lastActualDividend=Math.max(0,finite(result.lastActualDividend));result.lastDeclaredDividend=Math.max(0,finite(result.lastDeclaredDividend));result.lastPaymentWeek=Math.floor(finite(result.lastPaymentWeek,-1));result.history=Array.isArray(result.history)?result.history.filter(Boolean).slice(-HISTORY_LIMIT):[];return result;}
function readStateFor(instance){const state=instance?.g||instance||{};return normalizedState(state.finance?.shareholderReturns);}
function stateFor(instance){const state=instance?.g||instance||{},book=finance.ensureFinance(state),result=normalizedState(book.shareholderReturns);book.shareholderReturns=result;return result;}
function outstandingShares(state){return Math.max(0,Math.floor(finite(state?.sharesOut)-finite(state?.treasuryBuybackShares)));}
function capacity(instance){const state=instance?.g||instance||{},statements=finance.buildStatements(state,'52'),financialSafe=Math.max(0,finite(statements?.dividendCapacity?.safeDistributable)),cashSafe=Math.max(0,finite(state.companyCash)-MIN_CASH),safeAmount=Math.max(0,Math.min(financialSafe,cashSafe)),shares=outstandingShares(state);return{safeAmount,financialSafe,cashSafe,minCash:MIN_CASH,outstandingShares:shares,maxDividendPerShare:shares>0?safeAmount/shares:0};}
function record(instance,row){const returns=stateFor(instance);returns.history.push({week:Math.max(1,Math.floor(finite(instance?.g?.week,1))),...row});returns.history=returns.history.slice(-HISTORY_LIMIT);return returns;}
function setDividend(instance,amount){const state=instance.g||instance;amount=Math.max(0,finite(amount));if(!state.publicCompany)return instance.fail?.('未上場です。')??false;const cap=capacity(instance),plannedTotal=amount*cap.outstandingShares;if(plannedTotal>cap.safeAmount+.5)return instance.fail?.(`安全配当可能額は${compactYen(cap.safeAmount)}です。1株配当は最大${yen(cap.maxDividendPerShare)}まで設定できます。`)??false;return instance.runTransaction(()=>{state.dividendPerShare=amount;const own=instance.stock?.(state.ticker);if(own){own.dividendPerShare=amount;own.dividendYield=own.price>0?amount*4/own.price:0;}const returns=record(instance,{type:'declaration',dividendPerShare:amount,plannedTotal,safeCapacity:cap.safeAmount});returns.lastDeclaredDividend=amount;instance.notify?.(`四半期配当を1株${yen(amount)}に設定しました。予定総額は${compactYen(plannedTotal)}です。`,'success');return true;});}
function buyback(instance,requested){const state=instance.g||instance,amount=Math.floor(Math.max(0,finite(requested)));if(!state.publicCompany)return instance.fail?.('未上場です。')??false;if(amount<=0)return instance.fail?.('自社株買い金額を指定してください。')??false;const cap=capacity(instance);if(amount>cap.safeAmount+.5)return instance.fail?.(`安全な自社株買い上限は${compactYen(cap.safeAmount)}です。最低運転資金${compactYen(MIN_CASH)}と返済余力を確保してください。`)??false;const own=instance.stock?.(state.ticker),price=Math.max(1,finite(state.stockPrice,finite(own?.price,1))),externalShares=Math.max(0,Math.floor(finite(state.sharesOut)-finite(state.founderShares)-finite(state.treasuryBuybackShares))),qty=Math.min(externalShares,Math.floor(amount/price));if(qty<=0)return instance.fail?.('買い戻せる株式がありません。')??false;const cost=qty*price;return instance.runTransaction(()=>{const week=Math.max(1,Math.floor(finite(state.week,1))),book=finance.ensureFinance(state);state.companyCash=Math.max(0,finite(state.companyCash)-cost);state.treasuryBuybackShares=Math.max(0,Math.floor(finite(state.treasuryBuybackShares)+qty));book.balances.treasuryStock=Math.max(0,finite(book.balances.treasuryStock)+cost);finance.event(state,'otherFinancing',cost,{cashEffect:-cost,profitEffect:0,equityEffect:-cost,sourceType:'shareholderReturns',sourceID:`buyback-${week}-${state.treasuryBuybackShares}`,idempotencyKey:`shareholder-buyback-${week}-${state.treasuryBuybackShares}`,description:'自社株式取得'});state.stockPrice=price*(1+Math.min(.08,qty/Math.max(1,finite(state.sharesOut))*.8));if(own){own.price=state.stockPrice;own.marketCap=own.price*Math.max(1,finite(state.sharesOut));own.issuedShares=state.sharesOut;}instance.updateOwnershipRatios?.();record(instance,{type:'buyback',amount:cost,shares:qty,price,safeCapacity:cap.safeAmount});finance.rebuildSnapshotForWeek(state,week);instance.notify?.(`自社株${qty.toLocaleString('ja-JP')}株を${compactYen(cost)}で取得しました。`,'success');return true;});}
function correctQuarterlyDividend(instance,declaredPerShare,declaredTotal,actualCap,showSummary){const state=instance.g,report=state.lastReport;if(!report||report.week!==state.week)return;const paid=Math.max(0,finite(report.dividend)),originalProfit=finite(report.profit),originalTax=Math.max(0,finite(report.tax)),pretaxBeforeDividend=originalProfit+originalTax+paid,correctTax=Math.max(0,pretaxBeforeDividend)*TAX_RATE,taxDelta=Math.max(0,correctTax-originalTax);if(taxDelta>.005){state.companyCash-=taxDelta;finance.event(state,'taxExpense',taxDelta,{cashEffect:0,profitEffect:-taxDelta,sourceType:'shareholderReturns',sourceID:`dividend-tax-${state.week}`,idempotencyKey:`shareholder-dividend-tax-expense-${state.week}`,description:'配当を費用扱いしない法人税補正'});finance.event(state,'taxPayment',taxDelta,{cashEffect:-taxDelta,profitEffect:0,sourceType:'shareholderReturns',sourceID:`dividend-tax-payment-${state.week}`,idempotencyKey:`shareholder-dividend-tax-payment-${state.week}`,description:'配当会計補正に伴う法人税支払'});}const correctedProfit=originalProfit+paid-taxDelta,correctedExpenses=Math.max(0,finite(report.expenses)-paid+taxDelta);report.profit=correctedProfit;report.expenses=correctedExpenses;report.tax=originalTax+taxDelta;const stored=[...(state.reports||[])].reverse().find(row=>row?.week===state.week);if(stored){stored.profit=correctedProfit;stored.expenses=correctedExpenses;stored.tax=report.tax;}if(Array.isArray(state.weeklyProfitHistory)&&state.weeklyProfitHistory.length)state.weeklyProfitHistory[state.weeklyProfitHistory.length-1]=correctedProfit;const historyIndex=Array.isArray(state.history)?state.history.findIndex(row=>String(row).startsWith(`第${state.week}週 売上`)):-1;if(historyIndex>=0)state.history[historyIndex]=`第${state.week}週 売上${yen(report.sales)} 利益${yen(correctedProfit)} 会社現金${yen(state.companyCash)}`;if(originalProfit<0&&correctedProfit>=0)state.companyCredit=clamp(finite(state.companyCredit)+.45,0,100);if(originalProfit<=0&&correctedProfit>0)state.companyReputation=clamp(finite(state.companyReputation)+.12,0,100);if(state.lastWeeklySummary?.week===state.week){state.lastWeeklySummary.expenses=correctedExpenses;state.lastWeeklySummary.profit=correctedProfit;state.lastWeeklySummary.companyCash=state.companyCash;}const returns=record(instance,{type:'dividendPayment',declaredPerShare,declaredTotal,paid,capped:paid+1<declaredTotal,safeCapacity:actualCap,corporateTaxCorrection:taxDelta});returns.lastActualDividend=paid;returns.lastPaymentWeek=state.week;if(paid+1<declaredTotal){state.news.unshift(`第${state.week}週：配当予定${compactYen(declaredTotal)}のうち、安全余力に基づき${compactYen(paid)}を支払いました。`);state.news=state.news.slice(0,300);}finance.rebuildSnapshotForWeek(state,state.week);finance.buildStatements(state,'13');instance.save?.();if(showSummary)instance.emit?.('week',{summary:state.lastWeeklySummary});}
EngineClass.prototype.shareholderReturnCapacity=function(){return capacity(this);};
EngineClass.prototype.setDividend=function(amount){return setDividend(this,amount);};
EngineClass.prototype.buybackOwnShares=function(amount){return buyback(this,amount);};
EngineClass.prototype.advanceWeek=function(showSummary=true,...args){const state=this.g,declaredPerShare=Math.max(0,finite(state?.dividendPerShare)),paymentWeek=Boolean(state?.publicCompany&&declaredPerShare>0&&((Math.max(1,Math.floor(finite(state.week,1)))+1)%13===0));if(!paymentWeek)return baseAdvanceWeek.call(this,showSummary,...args);const cap=capacity(this),shares=outstandingShares(state),declaredTotal=declaredPerShare*shares,actualTotal=Math.min(declaredTotal,cap.safeAmount),actualPerShare=shares>0?actualTotal/shares:0,own=this.stock?.(state.ticker),ownDeclared=finite(own?.dividendPerShare,declaredPerShare);state.dividendPerShare=actualPerShare;if(own)own.dividendPerShare=actualPerShare;let result;try{result=baseAdvanceWeek.call(this,false,...args);}finally{state.dividendPerShare=declaredPerShare;if(own)own.dividendPerShare=ownDeclared;}if(result!==false)correctQuarterlyDividend(this,declaredPerShare,declaredTotal,cap.safeAmount,showSummary);return result;};
Object.defineProperty(EngineClass.prototype,'__shareholderReturnsInstalled',{value:true});
function render(instance=modules.playerEngineBridge?.getEngine?.()){if(!instance?.g?.configured||instance.g.selectedTab!=='market'||!instance.g.publicCompany)return'';const state=instance.g,cap=capacity(instance),returns=readStateFor(instance),planned=finite(state.dividendPerShare)*cap.outstandingShares,treasuryBook=finite(state.finance?.balances?.treasuryStock),key=renderKey(`${state.week}|${state.companyCash}|${state.dividendPerShare}|${planned}|${cap.safeAmount}|${state.treasuryBuybackShares}|${treasuryBook}|${returns.lastActualDividend}`);return `<section class="card" data-shareholder-returns-ui="1" data-shareholder-returns-render-key="${key}"><div class="card-head"><div><h2>株主還元・資本配分</h2><p>配当と自社株買いを、最低運転資金・返済余力・利益剰余金の範囲で実行します。配当は利益を減らさず財務CFとして処理されます。</p></div><span class="badge good">Phase 8C-1</span></div><div class="card-body"><div class="kpi-grid mini"><div class="stat"><span>安全還元可能額</span><strong>${esc(compactYen(cap.safeAmount))}</strong></div><div class="stat"><span>設定配当</span><strong>1株 ${esc(yen(state.dividendPerShare))}</strong></div><div class="stat"><span>次回予定総額</span><strong>${esc(compactYen(planned))}</strong></div><div class="stat"><span>直近実支払</span><strong>${esc(compactYen(returns.lastActualDividend))}</strong></div><div class="stat"><span>自己株式</span><strong>${Math.floor(finite(state.treasuryBuybackShares)).toLocaleString('ja-JP')}株</strong></div><div class="stat"><span>自己株式簿価</span><strong>${esc(compactYen(treasuryBook))}</strong></div></div><div class="button-row"><button class="btn secondary" data-action="set-dividend">配当を設定</button><button class="btn primary" data-action="buyback" ${cap.safeAmount<Math.max(1,finite(state.stockPrice))?'disabled':''}>自社株買い</button></div></div></section>`;}
let scheduled=false,observer=null;
function enhance(){if(typeof document==='undefined')return false;const screen=document.getElementById('screen');if(!screen)return false;const old=screen.querySelector?.('[data-shareholder-returns-ui]'),html=render();if(!html){old?.remove?.();return false;}const desired=(html.match(/data-shareholder-returns-render-key="([^"]+)"/)||[])[1]||'',current=String(old?.getAttribute?.('data-shareholder-returns-render-key')||old?.dataset?.shareholderReturnsRenderKey||'');if(old&&current===desired)return false;if(old){old.outerHTML=html;return true;}screen.insertAdjacentHTML?.('beforeend',html);return true;}
function schedule(){if(scheduled)return;scheduled=true;(typeof queueMicrotask==='function'?queueMicrotask:setTimeout)(()=>{scheduled=false;enhance();},0);}
function installUI(){if(typeof document==='undefined')return;const root=document.getElementById('app');if(root&&!observer&&typeof MutationObserver==='function'){observer=new MutationObserver(schedule);observer.observe(root,{childList:true,subtree:true});}schedule();}
modules.shareholderReturns=Object.freeze({MIN_CASH,HISTORY_LIMIT,TAX_RATE,normalizedState,readStateFor,stateFor,outstandingShares,capacity,setDividend,buyback,correctQuarterlyDividend,renderKey,render,enhance,installUI,__installed:true});
installUI();
})();
