// Script boundary: js/supply.js (classic JavaScript)
(function(){'use strict';
if(!globalThis.__capitalismTycoonModules)throw new Error('Capitalism Tycoon runtime.js must be loaded before supply.js.');
var __modules=globalThis.__capitalismTycoonModules;if(__modules.supply)throw new Error('Capitalism Tycoon supply module is already registered.');
(function(exports){
const TARGET_BUSINESS_IDS=Object.freeze(['ramen']);
const MATERIALS=Object.freeze([
{id:'ramen_noodles',name:'麺',category:'core',unitsPerSale:1,baseUnitCost:92,baseQuality:50,shelfLifeWeeks:5,standardLeadTimeWeeks:1,priceVolatility:.05,supplyRisk:.08,criticality:'critical',substitutable:false,wasteRate:.015},
{id:'ramen_soup',name:'スープ原料',category:'core',unitsPerSale:1,baseUnitCost:86,baseQuality:52,shelfLifeWeeks:8,standardLeadTimeWeeks:2,priceVolatility:.08,supplyRisk:.10,criticality:'critical',substitutable:false,wasteRate:.012},
{id:'ramen_toppings',name:'肉・主具材',category:'fresh',unitsPerSale:.7,baseUnitCost:78,baseQuality:50,shelfLifeWeeks:3,standardLeadTimeWeeks:1,priceVolatility:.12,supplyRisk:.13,criticality:'important',substitutable:true,wasteRate:.025},
{id:'ramen_vegetables',name:'野菜・トッピング',category:'fresh',unitsPerSale:.45,baseUnitCost:32,baseQuality:48,shelfLifeWeeks:2,standardLeadTimeWeeks:1,priceVolatility:.15,supplyRisk:.14,criticality:'optional',substitutable:true,wasteRate:.04},
{id:'ramen_packaging',name:'容器・消耗品',category:'packaging',unitsPerSale:1,baseUnitCost:12,baseQuality:50,shelfLifeWeeks:26,standardLeadTimeWeeks:2,priceVolatility:.03,supplyRisk:.04,criticality:'optional',substitutable:true,wasteRate:.002}
]);
const SUPPLIERS=Object.freeze([
{id:'low_cost',name:'低価格卸',supportedMaterialIDs:MATERIALS.map(m=>m.id),priceMultiplier:.90,quality:45,leadTimeWeeks:2,reliability:.88,minimumOrderQuantity:80,maximumWeeklySupply:9000,paymentTermsWeeks:2,contractFee:8000,spotPurchasePremium:.28,disruptionRisk:.08,regionID:'all',active:true},
{id:'quality_farm',name:'高品質産地便',supportedMaterialIDs:['ramen_soup','ramen_toppings','ramen_vegetables'],priceMultiplier:1.18,quality:68,leadTimeWeeks:2,reliability:.91,minimumOrderQuantity:45,maximumWeeklySupply:4200,paymentTermsWeeks:1,contractFee:12000,spotPurchasePremium:.34,disruptionRisk:.06,regionID:'all',active:true},
{id:'quick_local',name:'短納期ローカル',supportedMaterialIDs:MATERIALS.map(m=>m.id),priceMultiplier:1.10,quality:49,leadTimeWeeks:1,reliability:.84,minimumOrderQuantity:30,maximumWeeklySupply:2600,paymentTermsWeeks:0,contractFee:6000,spotPurchasePremium:.22,disruptionRisk:.10,regionID:'all',active:true},
{id:'reliable_national',name:'高信頼ナショナル',supportedMaterialIDs:MATERIALS.map(m=>m.id),priceMultiplier:1.04,quality:54,leadTimeWeeks:2,reliability:.98,minimumOrderQuantity:70,maximumWeeklySupply:12000,paymentTermsWeeks:3,contractFee:15000,spotPurchasePremium:.25,disruptionRisk:.025,regionID:'all',active:true},
{id:'balanced_wholesale',name:'バランス問屋',supportedMaterialIDs:MATERIALS.map(m=>m.id),priceMultiplier:1.00,quality:52,leadTimeWeeks:2,reliability:.93,minimumOrderQuantity:50,maximumWeeklySupply:7000,paymentTermsWeeks:2,contractFee:9000,spotPurchasePremium:.25,disruptionRisk:.05,regionID:'all',active:true}
]);
const POLICIES={lean:{id:'lean',name:'リーン',safetyWeeks:.6,orderWeeks:1.1,emergencyLimitWeeks:.5},balanced:{id:'balanced',name:'バランス',safetyWeeks:1.2,orderWeeks:1.8,emergencyLimitWeeks:.8},stable:{id:'stable',name:'安定供給重視',safetyWeeks:2.4,orderWeeks:2.8,emergencyLimitWeeks:1.1}};
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d, r=v=>Math.round(n(v)*100)/100, clamp=(v,a,b)=>Math.max(a,Math.min(b,n(v,a))), sum=a=>a.reduce((x,y)=>x+y,0);
function mat(id){return MATERIALS.find(m=>m.id===id);}function sup(id){return SUPPLIERS.find(s=>s.id===id)||SUPPLIERS[4];}function isTargetBusinessID(id){return TARGET_BUSINESS_IDS.indexOf(id)>=0;}
function ensure(g){if(!g.inventoryByStoreID||typeof g.inventoryByStoreID!=='object')g.inventoryByStoreID={};if(!Array.isArray(g.purchaseOrders))g.purchaseOrders=[];if(!g.supplySettingsByStoreID||typeof g.supplySettingsByStoreID!=='object')g.supplySettingsByStoreID={};if(!g.supplyResultsByStoreID||typeof g.supplyResultsByStoreID!=='object')g.supplyResultsByStoreID={};if(!g.supplyResultsByBusinessID||typeof g.supplyResultsByBusinessID!=='object')g.supplyResultsByBusinessID={};if(!Array.isArray(g.supplierContracts))g.supplierContracts=[];if(!Array.isArray(g.supplyChainEvents))g.supplyChainEvents=[];if(!g.inventoryByBusinessID||typeof g.inventoryByBusinessID!=='object')g.inventoryByBusinessID={};if(!Number.isFinite(Number(g.nextPurchaseOrderSeq)))g.nextPurchaseOrderSeq=1;if(!Number.isFinite(Number(g.nextInventoryLotSeq)))g.nextInventoryLotSeq=1;if(!Number.isFinite(Number(g.nextSupplyEventSeq)))g.nextSupplyEventSeq=1;return g;}
function defaultSettings(store){return {storeID:store.id,businessID:store.businessID,autoPolicy:'balanced',safetyStockWeeks:1.2,emergencyProcurementEnabled:true,preferredSupplierID:'balanced_wholesale'};}
function ensureStore(g,store){ensure(g);if(!isTargetBusinessID(store.businessID))return null;if(!g.supplySettingsByStoreID[store.id])g.supplySettingsByStoreID[store.id]=defaultSettings(store);if(!g.inventoryByStoreID[store.id]){const inv={storeID:store.id,businessID:store.businessID,materials:{},lastUpdatedWeek:n(g.week,1),stockoutCount:0,spoilageTotal:0,emergencyPurchaseTotal:0};for(const m of MATERIALS)inv.materials[m.id]={quantity:0,reservedQuantity:0,averageUnitCost:m.baseUnitCost,averageQuality:m.baseQuality,lastReceivedWeek:null,lastConsumedWeek:null,lots:[]};g.inventoryByStoreID[store.id]=inv;}return g.inventoryByStoreID[store.id];}
function lotValue(l){return r(n(l.quantity)*n(l.unitCost));}function invValue(inv){return r(sum(Object.values(inv.materials||{}).map(x=>sum((x.lots||[]).filter(l=>l.status==='available').map(lotValue)))));}function recalcMaterial(x){const lots=(x.lots||[]).filter(l=>n(l.quantity)>0&&l.status==='available').sort((a,b)=>n(a.expiryWeek)-n(b.expiryWeek)||n(a.receivedWeek)-n(b.receivedWeek));x.lots=lots.slice(-40);x.quantity=r(sum(x.lots.map(l=>n(l.quantity))));const val=sum(x.lots.map(lotValue));x.averageUnitCost=x.quantity>0?r(val/x.quantity):r(n(x.averageUnitCost));x.averageQuality=x.quantity>0?r(sum(x.lots.map(l=>n(l.quantity)*n(l.quality)))/x.quantity):r(n(x.averageQuality,50));}
function addLot(g,storeID,materialID,qty,cost,quality,po){const store=(g.stores||[]).find(s=>s.id===storeID);const inv=ensureStore(g,store);const m=mat(materialID);const lot={lotID:`lot-${g.nextInventoryLotSeq++}`,materialID,quantity:r(qty),originalQuantity:r(qty),unitCost:r(cost),quality:r(quality),receivedWeek:n(g.week),expiryWeek:n(g.week)+n(m.shelfLifeWeeks),supplierContractID:po?.supplierContractID||null,purchaseOrderID:po?.orderID||null,status:'available'};inv.materials[materialID].lots.push(lot);inv.materials[materialID].lastReceivedWeek=n(g.week);recalcMaterial(inv.materials[materialID]);inv.lastUpdatedWeek=n(g.week);return lot;}
function hash01(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619);}return ((h>>>0)%10000)/10000;}
function activeContract(g,storeID,businessID,materialID){return (g.supplierContracts||[]).filter(c=>c.active&&c.status!=='terminated'&&c.businessID===businessID&&(!c.storeID||c.storeID===storeID)&&(c.materialIDs||[]).includes(materialID)).sort((a,b)=>n(a.priority,10)-n(b.priority,10))[0]||null;}
function makeContract(g,storeID,businessID,supplierID){ensure(g);const s=sup(supplierID), id=`contract-${g.nextSupplyEventSeq++}`;const c={contractID:id,supplierID:s.id,businessID,storeID,materialIDs:s.supportedMaterialIDs.slice(),active:true,startedWeek:n(g.week),minimumOrderQuantity:s.minimumOrderQuantity,agreedPriceMultiplier:s.priceMultiplier,agreedLeadTimeWeeks:s.leadTimeWeeks,agreedQuality:s.quality,paymentTermsWeeks:s.paymentTermsWeeks,weeklyCapacity:s.maximumWeeklySupply,terminationFee:Math.round(s.contractFee*.35),reliabilityModifier:0,status:'active',priority:5,name:s.name};g.supplierContracts.push(c);return c;}
function selectSupplier(g,storeID,supplierID){const st=(g.stores||[]).find(s=>s.id===storeID);if(!st||!isTargetBusinessID(st.businessID))return false;ensureStore(g,st);(g.supplierContracts||[]).forEach(c=>{if(c.storeID===storeID)c.active=false;});makeContract(g,storeID,st.businessID,supplierID);g.supplySettingsByStoreID[storeID].preferredSupplierID=supplierID;return true;}
function createOrder(g,storeID,materialID,qty,opts={}){ensure(g);const st=(g.stores||[]).find(s=>s.id===storeID);if(!st||st.status==='closed'||!isTargetBusinessID(st.businessID))return null;const m=mat(materialID);if(!m)return null;const c=activeContract(g,storeID,st.businessID,materialID);const s=sup(opts.supplierID||(c&&c.supplierID)||g.supplySettingsByStoreID[storeID]?.preferredSupplierID||'balanced_wholesale');if(!s.supportedMaterialIDs.includes(materialID))return null;const min=n(c?.minimumOrderQuantity,s.minimumOrderQuantity), cap=n(c?.weeklyCapacity,s.maximumWeeklySupply);qty=Math.min(Math.max(n(qty),min),cap);if(qty<=0)return null;const mult=n(c?.agreedPriceMultiplier,s.priceMultiplier)*(opts.isEmergency?s.spotPurchasePremium+1:1);const unit=r(m.baseUnitCost*mult*(1+(hash01(`${g.week}-${s.id}-${materialID}`)-.5)*m.priceVolatility));const total=r(unit*qty), terms=n(c?.paymentTermsWeeks,s.paymentTermsWeeks);if(terms===0&&n(g.companyCash)<total)return null;const lead=opts.isEmergency?0:n(c?.agreedLeadTimeWeeks,s.leadTimeWeeks);const po={orderID:`po-${g.nextPurchaseOrderSeq++}`,storeID,businessID:st.businessID,supplierID:s.id,supplierContractID:c?.contractID||null,materialID,orderedQuantity:r(qty),receivedQuantity:0,unitCost:unit,totalCost:total,quality:n(c?.agreedQuality,s.quality),orderWeek:n(g.week),expectedArrivalWeek:n(g.week)+lead,actualArrivalWeek:null,paymentDueWeek:n(g.week)+terms,paymentStatus:terms===0?'due':'unpaid',orderStatus:'ordered',isEmergency:!!opts.isEmergency,disruptionReason:null,operationID:opts.operationID||`supply-order-${g.week}-${storeID}-${materialID}-${g.nextPurchaseOrderSeq}`};g.purchaseOrders.push(po);return po;}
function receiveOrders(g,finance){ensure(g);let received=0;for(const po of g.purchaseOrders){if(!['ordered','delayed','partiallyReceived'].includes(po.orderStatus))continue;if(n(po.expectedArrivalWeek)>n(g.week))continue;if(po._lastProcessedWeek===g.week)continue;po._lastProcessedWeek=g.week;const store=(g.stores||[]).find(x=>x.id===po.storeID);if(!store||store.status==='closed'){po.orderStatus='cancelled';continue;}const s=sup(po.supplierID), risk=n(s.disruptionRisk)*(1-n(s.reliability))*2, h=hash01(`${po.orderID}-${po.expectedArrivalWeek}-${po.supplierID}`);if(!po.disruptionReason&&h<risk){po.orderStatus='delayed';po.expectedArrivalWeek++;po.disruptionReason='納期遅延';event(g,`第${g.week}週：${s.name}の${mat(po.materialID).name}が遅延しました。`);continue;}let qty=n(po.orderedQuantity)-n(po.receivedQuantity);if(h>risk&&h<risk+.025){qty=r(qty*.65);po.orderStatus='partiallyReceived';po.disruptionReason='部分納品';}else po.orderStatus='received';if(qty<=0)continue;addLot(g,po.storeID,po.materialID,qty,po.unitCost,po.quality,po);po.receivedQuantity=r(n(po.receivedQuantity)+qty);po.actualArrivalWeek=n(g.week);const amount=r(qty*n(po.unitCost));const f=finance&&finance.ensureFinance?finance.ensureFinance(g):null;if(f){if(n(po.paymentDueWeek)<=n(g.week)){g.companyCash-=amount;finance.event(g,'workingCapitalIncrease',amount,{cashEffect:-amount,profitEffect:0,assetEffect:amount,businessID:po.businessID,storeID:po.storeID,sourceType:'inventory-receipt-cash',sourceID:po.orderID,idempotencyKey:`${po.orderID}-receipt-cash`,operationID:`${po.orderID}-receipt-cash`,inventoryAmount:amount,description:'原材料入庫（現金払い）'});po.paymentStatus='paid';}else{finance.event(g,'workingCapitalIncrease',amount,{cashEffect:0,profitEffect:0,assetEffect:amount,liabilityEffect:amount,payableAmount:amount,businessID:po.businessID,storeID:po.storeID,sourceType:'inventory-receipt-ap',sourceID:po.orderID,idempotencyKey:`${po.orderID}-receipt-ap`,operationID:`${po.orderID}-receipt-ap`,inventoryAmount:amount,description:'原材料入庫（掛仕入）'});}}
received+=amount;event(g,`第${g.week}週：${s.name}から${mat(po.materialID).name} ${Math.round(qty)}単位を入庫しました。`);}return received;}
function payables(g,finance){let paid=0;if(!finance)return 0;for(const po of g.purchaseOrders||[]){if(po.paymentStatus==='unpaid'&&n(po.paymentDueWeek)<=n(g.week)&&po.receivedQuantity>0){const amount=r(n(po.receivedQuantity)*n(po.unitCost));if(n(g.companyCash)>=amount){g.companyCash-=amount;finance.event(g,'accountsPayablePayment',amount,{cashEffect:-amount,profitEffect:0,businessID:po.businessID,storeID:po.storeID,sourceType:'ap-payment',sourceID:po.orderID,idempotencyKey:`${po.orderID}-ap-pay`,operationID:`${po.orderID}-ap-pay`,description:'買掛金支払'});po.paymentStatus='paid';paid+=amount;}}}return paid;}
function spoil(g,finance){ensure(g);let cost=0, qty=0;for(const st of (g.stores||[])){if(!isTargetBusinessID(st.businessID))continue;const inv=ensureStore(g,st);for(const [mid,x] of Object.entries(inv.materials)){for(const l of x.lots||[]){if(l.status==='available'&&n(l.quantity)>0&&n(l.expiryWeek)<=n(g.week)){const c=lotValue(l);qty+=n(l.quantity);cost+=c;l.quantity=0;l.status='expired';}}recalcMaterial(x);}inv.spoilageTotal=r(n(inv.spoilageTotal)+cost);}if(cost>0&&finance){const f=finance.ensureFinance(g);f.balances.inventory=r(Math.max(0,n(f.balances.inventory)-cost));finance.event(g,'otherOperating',cost,{cashEffect:0,profitEffect:-cost,assetEffect:-cost,sourceType:'spoilage',sourceID:`week-${g.week}`,idempotencyKey:`week-${g.week}-spoilage`,operationID:`week-${g.week}-spoilage`,description:'期限切れ原材料廃棄'});event(g,`第${g.week}週：期限切れ在庫を${Math.round(qty)}単位、${Math.round(cost).toLocaleString()}円廃棄しました。`);}return {cost:r(cost),quantity:r(qty)};}
function availableUnits(g,storeID){const inv=g.inventoryByStoreID?.[storeID];if(!inv)return Infinity;let limit=Infinity, quality=0, weight=0, costPer=0;for(const m of MATERIALS){const x=inv.materials[m.id];const usable=sum((x?.lots||[]).filter(l=>l.status==='available'&&n(l.expiryWeek)>n(g.week)).map(l=>n(l.quantity)));if(m.criticality==='critical')limit=Math.min(limit,Math.floor(usable/m.unitsPerSale));quality+=n(x?.averageQuality,m.baseQuality)*m.unitsPerSale;weight+=m.unitsPerSale;costPer+=n(x?.averageUnitCost,m.baseUnitCost)*m.unitsPerSale;}return {units:Number.isFinite(limit)?Math.max(0,limit):Infinity,qualityScore:weight?quality/weight:50,costPerUnit:costPer};}
function applyConstraint(g,store,mr){ensureStore(g,store);const av=availableUnits(g,store.id), demandUnits=n(mr.unitsSold), fulfilled=Math.min(demandUnits,av.units), stockout=Math.max(0,demandUnits-fulfilled), ratio=demandUnits>0?fulfilled/demandUnits:1;let emergencyCost=0;if(stockout>0&&g.supplySettingsByStoreID[store.id]?.emergencyProcurementEnabled){const max=n(g.supplySettingsByStoreID[store.id].safetyStockWeeks,1)*Math.max(10,demandUnits)*.6;const add=Math.min(stockout,max);for(const m of MATERIALS.filter(x=>x.criticality==='critical')){const po=createOrder(g,store.id,m.id,add*m.unitsPerSale,{isEmergency:true,supplierID:'quick_local'});if(po){addLot(g,store.id,m.id,po.orderedQuantity,po.unitCost,Math.min(50,po.quality),po);po.receivedQuantity=po.orderedQuantity;po.actualArrivalWeek=n(g.week);po.orderStatus='received';po.paymentStatus='paid';g.companyCash-=po.totalCost;emergencyCost+=po.totalCost;}}const av2=availableUnits(g,store.id);return finalizeConstraint(g,store,mr,Math.min(demandUnits,av2.units),emergencyCost,av2);}return finalizeConstraint(g,store,mr,fulfilled,0,av);}
function consume(g,storeID,units){const inv=g.inventoryByStoreID[storeID], consumed=[];let total=0;for(const m of MATERIALS){let need=r(units*m.unitsPerSale), materialCost=0;const x=inv.materials[m.id];x.lots.sort((a,b)=>n(a.expiryWeek)-n(b.expiryWeek)||n(a.receivedWeek)-n(b.receivedWeek));for(const l of x.lots){if(need<=0)break;if(l.status!=='available'||n(l.expiryWeek)<=n(g.week)||n(l.quantity)<=0)continue;const take=Math.min(need,n(l.quantity));l.quantity=r(n(l.quantity)-take);need=r(need-take);const c=r(take*n(l.unitCost));materialCost+=c;total+=c;if(l.quantity<=0)l.status='consumed';}x.lastConsumedWeek=n(g.week);recalcMaterial(x);consumed.push({materialID:m.id,quantity:r(units*m.unitsPerSale-need),cost:r(materialCost),shortage:r(Math.max(0,need))});}return {totalCost:r(total),materials:consumed};}
function finalizeConstraint(g,store,mr,fulfilled,emergencyCost,av){const demandUnits=n(mr.unitsSold), ratio=demandUnits>0?fulfilled/demandUnits:1;const c=consume(g,store.id,fulfilled);const revenue=n(mr.revenue)*ratio, variable=c.totalCost, result={...mr,demandAllocatedUnits:n(mr.potentialDemand),capacityLimitedUnits:demandUnits,inventoryAvailableUnits:av.units,inventoryLimitedUnits:fulfilled,fulfilledUnits:fulfilled,unitsSold:fulfilled,demandMarketShare:n(mr.marketShare),realizedMarketShare:n(mr.marketShare)*ratio,stockoutLostDemand:Math.max(0,demandUnits-fulfilled),capacityLostDemand:n(mr.lostDemand),totalLostDemand:n(mr.lostDemand)+Math.max(0,demandUnits-fulfilled),fillRate:demandUnits>0?fulfilled/demandUnits:1,materialQualityScore:r(av.qualityScore),procurementCostPerUnit:fulfilled>0?r(variable/fulfilled):r(av.costPerUnit),revenue:r(revenue),variableCost:r(variable),materialCost:r(variable),packagingCost:r((c.materials.find(x=>x.materialID==='ramen_packaging')||{}).cost||0),emergencyProcurementCost:r(emergencyCost),spoilageExpense:0,totalCostOfSales:r(variable),actualVariableCostPerUnit:fulfilled>0?r(variable/fulfilled):0,grossProfit:r(revenue-variable),contributionMargin:r(revenue-variable),contributionMarginRate:revenue>0?(revenue-variable)/revenue:0};g.supplyResultsByStoreID[store.id]=result;if(result.stockoutLostDemand>0){g.inventoryByStoreID[store.id].stockoutCount++;event(g,`第${g.week}週：${store.name}で欠品により${Math.round(result.stockoutLostDemand)}食の機会損失が発生しました。`);}return result;}
function autoOrder(g){for(const st of (g.stores||[])){if(st.status!=='open'||!isTargetBusinessID(st.businessID))continue;ensureStore(g,st);const set=g.supplySettingsByStoreID[st.id], pol=POLICIES[set.autoPolicy]||POLICIES.balanced, weekly=Math.max(0,n(g.supplyResultsByStoreID[st.id]?.demandAllocatedUnits,n(g.marketResultsByStoreID?.[st.id]?.unitsSold,0)));if(weekly<=0)continue;for(const m of MATERIALS){const x=g.inventoryByStoreID[st.id].materials[m.id], onHand=n(x.quantity), onOrder=sum((g.purchaseOrders||[]).filter(po=>po.storeID===st.id&&po.materialID===m.id&&['ordered','delayed','partiallyReceived'].includes(po.orderStatus)).map(po=>n(po.orderedQuantity)-n(po.receivedQuantity)));const s=sup(set.preferredSupplierID), reorder=weekly*m.unitsPerSale*(s.leadTimeWeeks+pol.safetyWeeks)/(Math.max(.5,s.reliability));const target=weekly*m.unitsPerSale*(s.leadTimeWeeks+pol.orderWeeks+pol.safetyWeeks);if(onHand+onOrder<reorder)createOrder(g,st.id,m.id,Math.max(0,target-onHand-onOrder),{supplierID:s.id,operationID:`auto-${g.week}-${st.id}-${m.id}`});}}
aggregate(g);}
function aggregate(g){const by={};let totalValue=0;for(const inv of Object.values(g.inventoryByStoreID||{})){const v=invValue(inv);totalValue+=v;const b=by[inv.businessID]||(by[inv.businessID]={units:0,value:0,targetWeeks:0,lastDemandUnits:0,lastProcurementCost:0,disruptionWeeks:0});b.units+=sum(Object.values(inv.materials).map(x=>n(x.quantity)));b.value+=v;}for(const [k,v] of Object.entries(by)){v.units=r(v.units);v.value=r(v.value);g.inventoryByBusinessID[k]={...(g.inventoryByBusinessID[k]||{}),...v};}return r(totalValue);}
function event(g,msg){g.supplyChainEvents.unshift(msg);g.supplyChainEvents=g.supplyChainEvents.slice(0,100);}
function initializeStoreInventory(g,store){const inv=ensureStore(g,store);if(inv.initialized)return;const b=(g.businesses||[]).find(x=>x.id===store.businessID)||{};const weekly=Math.max(20,n(store.lastSales,0)/Math.max(1,n(b.price,900))||n(b.demand,100));for(const m of MATERIALS)addLot(g,store.id,m.id,weekly*m.unitsPerSale*2,m.baseUnitCost,m.baseQuality,{orderID:'initial-v6'});inv.initialized=true;aggregate(g);}
function migrateV6(g){ensure(g);for(const st of (g.stores||[]).filter(s=>isTargetBusinessID(s.businessID)))initializeStoreInventory(g,st);g.saveVersion=6;return g;}
function validate(g){ensure(g);const errors=[];for(const inv of Object.values(g.inventoryByStoreID)){for(const x of Object.values(inv.materials||{})){recalcMaterial(x);if(n(x.quantity)<-.0001)errors.push('negative inventory');for(const l of x.lots||[])for(const v of ['quantity','unitCost','quality'])if(!Number.isFinite(Number(l[v])))errors.push('non finite lot');}}return {ok:!errors.length,errors};}
Object.assign(exports,{TARGET_BUSINESS_IDS,MATERIALS,SUPPLIERS,POLICIES,isTargetBusinessID,ensure,ensureStore,initializeStoreInventory,migrateV6,selectSupplier,makeContract,createOrder,receiveOrders,payables,spoil,availableUnits,applyConstraint,autoOrder,aggregate,validate});
})(__modules.supply={});
})();
