// Script boundary: js/workforce.js (classic JavaScript)
(function(){'use strict';
if(!globalThis.__capitalismTycoonModules)throw new Error('Capitalism Tycoon runtime.js must be loaded before workforce.js.');
var __modules=globalThis.__capitalismTycoonModules;
if(!__modules.data)throw new Error('Capitalism Tycoon data module must be loaded before workforce.js.');
if(__modules.workforce)throw new Error('Capitalism Tycoon workforce module is already registered.');
(function(exports,data){
const MASTER=data.MASTER;
const TARGET_BUSINESS_IDS=Object.freeze(['ramen']);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const r=v=>Math.round(n(v)*100)/100;
const roleRows=[
 ['store-ops','店舗運営',null,'store',17500,95,45,.8,9,.15,.9,1.1,.7,.35,true,false],
 ['operations','オペレーション','operations','corporate',65000,115,52,1.0,8,.45,1.0,1.0,.45,.55,false,true],
 ['marketing','マーケティング','marketing','corporate',70000,105,55,1.1,7,.7,1.0,.9,.35,.7,false,true],
 ['hr','人事','hr','corporate',62000,100,50,1.0,8,.75,.9,1.2,.25,.55,false,true],
 ['finance','財務','accounting','corporate',76000,98,58,1.2,7,.8,.8,.8,.2,.6,false,true],
 ['dx','DX・IT','dx','corporate',85000,110,62,1.35,6,.85,1.1,.75,.45,.85,false,true],
 ['product','商品・R&D','product','corporate',82000,104,60,1.3,6,.65,1.0,.85,.75,.9,false,true],
 ['investment','投資・M&A','investment','corporate',90000,94,64,1.45,6,.75,.9,.9,.2,.75,false,true],
 ['procurement','調達・物流','operations','corporate',68000,112,54,1.05,8,.5,1.05,1.0,.35,.65,false,true],
 ['manager','管理職',null,'management',95000,32,62,1.4,12,.65,.8,.7,.25,.5,true,true]
];
const ROLES=Object.freeze(roleRows.map(x=>({id:x[0],name:x[1],departmentID:x[2],category:x[3],baseWeeklySalary:x[4],baseCapacityPerPerson:x[5],requiredSkill:x[6],trainingDifficulty:x[7],managementSpan:x[8],remoteWorkCompatibility:x[9],fatigueSensitivity:x[10],turnoverSensitivity:x[11],qualityContribution:x[12],projectContribution:x[13],storeApplicable:x[14],corporateApplicable:x[15]})));
const roleByID=id=>ROLES.find(x=>x.id===id)||ROLES[0];
const deptRole=id=>ROLES.find(x=>x.departmentID===id)||ROLES.find(x=>x.id===id)||ROLES[1];
function stableHash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0)/4294967295;}
function ensure(g){if(!Array.isArray(g.workforceTeams))g.workforceTeams=[];if(!Array.isArray(g.workforceCandidates))g.workforceCandidates=[];if(!Array.isArray(g.workforceTrainings))g.workforceTrainings=[];if(!Array.isArray(g.workforceProjects))g.workforceProjects=[];if(!g.workforceResultsByDepartmentID||typeof g.workforceResultsByDepartmentID!=='object')g.workforceResultsByDepartmentID={};if(!g.workforceResultsByStoreID||typeof g.workforceResultsByStoreID!=='object')g.workforceResultsByStoreID={};if(!g.workforceSettings||typeof g.workforceSettings!=='object')g.workforceSettings={detailStoreBusinessIDs:['ramen']};g.nextWorkforceTeamSeq=Math.max(1,Math.floor(n(g.nextWorkforceTeamSeq,1)));g.nextCandidateSeq=Math.max(1,Math.floor(n(g.nextCandidateSeq,1)));g.nextTrainingSeq=Math.max(1,Math.floor(n(g.nextTrainingSeq,1)));g.nextProjectSeq=Math.max(1,Math.floor(n(g.nextProjectSeq,1)));g.nextWorkforceEventSeq=Math.max(1,Math.floor(n(g.nextWorkforceEventSeq,1)));return g;}
function makeTeam(g,o){ensure(g);const role=roleByID(o.roleID);return {teamID:o.teamID||`wf-team-${g.nextWorkforceTeamSeq++}`,departmentID:o.departmentID??role.departmentID??null,storeID:o.storeID??null,branchOfficeID:o.branchOfficeID??null,roleID:role.id,headcount:Math.max(0,Math.floor(n(o.headcount))),managerHeadcount:Math.max(0,Math.floor(n(o.managerHeadcount,Math.floor(n(o.headcount)/role.managementSpan)))),averageSkill:clamp(n(o.averageSkill,g.employeeAbility||50),1,100),averageExperience:clamp(n(o.averageExperience,20),0,100),averageWeeklySalary:Math.max(0,n(o.averageWeeklySalary,role.baseWeeklySalary)),morale:clamp(n(o.morale,g.organizationCulture?.morale||55),0,100),fatigue:clamp(n(o.fatigue,20),0,100),engagement:clamp(n(o.engagement,g.employeeSatisfaction||55),0,100),trainingLevel:clamp(n(o.trainingLevel,0),0,100),onboardingHeadcount:Math.max(0,Math.floor(n(o.onboardingHeadcount,0))),availableHeadcount:0,remoteRatio:clamp(n(o.remoteRatio,0),0,1),weeklyCapacity:0,requiredWorkload:0,utilization:0,overtimeHours:0,backlog:0,turnoverRisk:0,status:o.status||'active',createdWeek:Math.max(1,Math.floor(n(o.createdWeek,g.week||1))),lastUpdatedWeek:Math.max(1,Math.floor(n(o.lastUpdatedWeek,g.week||1)))};}
function syncDepartmentStaff(g){ensure(g);const mirror={};for(const d of Object.keys(g.departments||{}))mirror[d]=0;for(const t of g.workforceTeams){if(t.departmentID&&!t.storeID&&t.status!=='removed')mirror[t.departmentID]=(mirror[t.departmentID]||0)+Math.max(0,Math.floor(n(t.headcount)));}g.departmentStaff=Object.assign(g.departmentStaff||{},mirror);return mirror;}
function migrateV7(g){ensure(g);if(!g.workforceMigrationV7Applied){for(const [id,c] of Object.entries(g.departmentStaff||{})){const hc=Math.max(0,Math.floor(n(c)));if((g.departments||{})[id]&&hc>0&&!g.workforceTeams.some(t=>t.departmentID===id&&!t.storeID)){const role=deptRole(id);g.workforceTeams.push(makeTeam(g,{teamID:`wf-dept-${id}`,departmentID:id,roleID:role.id,headcount:hc,managerHeadcount:Math.floor(hc/role.managementSpan),averageWeeklySalary:role.baseWeeklySalary,morale:g.organizationCulture?.morale,engagement:g.employeeSatisfaction,averageSkill:g.employeeAbility,createdWeek:g.week||1,lastUpdatedWeek:g.week||1}));}}
 for(const st of (g.stores||[])){if(TARGET_BUSINESS_IDS.indexOf(st.businessID)>=0&&!g.workforceTeams.some(t=>t.storeID===st.id)){const b=(g.businesses||[]).find(x=>x.id===st.businessID)||{};const hc=Math.max(5,Math.round(n(b.wage,52500)/17500));g.workforceTeams.push(makeTeam(g,{teamID:`wf-store-${st.id}`,storeID:st.id,roleID:'store-ops',headcount:hc,managerHeadcount:hc>=3?1:0,averageWeeklySalary:hc? n(b.wage,52500)/hc:17500,averageSkill:g.employeeAbility,morale:g.organizationCulture?.morale,engagement:g.employeeSatisfaction,createdWeek:g.week||1,lastUpdatedWeek:g.week||1}));}}
 g.workforceMigrationV7Applied=true;}syncDepartmentStaff(g);g.saveVersion=7;return g;}
function officeMetrics(g){ensure(g);let office=0,remoteCompatible=0;for(const t of g.workforceTeams){if(!t.storeID){office+=n(t.headcount);remoteCompatible+=n(t.headcount)*roleByID(t.roleID).remoteWorkCompatibility;}}const remoteEnabled=!!g.remoteWorkEnabled,remoteSeats=remoteEnabled?remoteCompatible*.45:0,cap=n(g.officeCapacity,0)+(g.branchOffices||[]).reduce((a,b)=>a+n(b.capacity),0);const seated=Math.max(0,office-remoteSeats),over=Math.max(0,seated-cap);return {officeHeadcount:r(office),officeCapacity:r(cap),remoteCompatibleHeadcount:r(remoteCompatible),overCapacityHeadcount:r(over),seatUtilization:cap>0?r(seated/cap):0,officeConstraintPenalty:clamp(1-over/Math.max(1,office)*.25,.75,1)};}
function workload(g,dept){const stores=(g.stores||[]).filter(s=>s.status==='open');const ramen=stores.filter(s=>TARGET_BUSINESS_IDS.indexOf(s.businessID)>=0);const supplyOrders=(g.purchaseOrders||[]).filter(o=>o.orderStatus!=='paid'&&o.orderStatus!=='cancelled').length;const map={operations:stores.length*55+ramen.length*25,marketing:stores.length*30+Object.keys(g.marketResultsByBusinessID||{}).length*20,hr:(g.workforceTeams||[]).reduce((a,t)=>a+n(t.headcount),0)*4+(g.workforceCandidates||[]).filter(c=>c.status==='open').length*18,accounting:stores.length*20+(g.finance?.transactions?.length||0)*.08+Object.keys(g.executives||{}).length*8,dx:stores.length*18+n((g.businesses||[]).reduce((a,b)=>a+n(b.dx),0))*.5,product:(g.productVentures||[]).filter(p=>p.status==='developing').length*55,investment:(g.startups||[]).filter(s=>s.ownedCompany>0).length*20+(g.acquisitionTargets||[]).length*25};map.procurement=ramen.length*50+supplyOrders*14+(g.supplyChainEvents||[]).length*.02;return r(map[dept]||0);}
function recompute(g){ensure(g);const office=officeMetrics(g),deptResults={};for(const t of g.workforceTeams){const role=roleByID(t.roleID);t.headcount=Math.max(0,Math.floor(n(t.headcount)));t.managerHeadcount=clamp(Math.floor(n(t.managerHeadcount)),0,t.headcount);t.onboardingHeadcount=clamp(Math.floor(n(t.onboardingHeadcount)),0,t.headcount);t.availableHeadcount=clamp(t.headcount-t.onboardingHeadcount,0,t.headcount);const reqManagers=Math.ceil(Math.max(0,t.headcount-t.managerHeadcount)/Math.max(1,role.managementSpan));const coverage=reqManagers?clamp(t.managerHeadcount/reqManagers,0,1):1;const skill=clamp(.75+n(t.averageSkill,50)/100*.5,.6,1.35),exp=clamp(.85+n(t.averageExperience,20)/200,.75,1.25),training=clamp(1+n(t.trainingLevel,0)/250,.9,1.25),fat=clamp(1-n(t.fatigue,0)/180*role.fatigueSensitivity,.55,1.05),mor=clamp(.75+n(t.morale,55)/220,.7,1.18),mgmt=clamp(.72+coverage*.33,.65,1.05),officeMult=t.storeID?1:office.officeConstraintPenalty;let cap=t.availableHeadcount*role.baseCapacityPerPerson*skill*exp*training*fat*mor*mgmt*officeMult;if(t.managerHeadcount>reqManagers+1)cap*=clamp(1-(t.managerHeadcount-reqManagers-1)*.03,.82,1);t.weeklyCapacity=r(cap);t.managementCoverage=r(coverage);t.requiredManagers=reqManagers;t.availableManagers=t.managerHeadcount;t.spanOfControl=role.managementSpan;t.managementPenalty=r(mgmt);t.lastUpdatedWeek=g.week||1;if(t.departmentID&&!t.storeID){const d=deptResults[t.departmentID]||(deptResults[t.departmentID]={departmentID:t.departmentID,headcount:0,managerHeadcount:0,availableCapacity:0,requiredWorkload:workload(g,t.departmentID),backlog:0,utilization:0,bottleneckLevel:0,managementCoverage:0,fatigue:0,morale:0,effectMultiplier:1,projectCapacity:0});d.headcount+=t.headcount;d.managerHeadcount+=t.managerHeadcount;d.availableCapacity+=t.weeklyCapacity;d.managementCoverage+=coverage*t.headcount;d.fatigue+=t.fatigue*t.headcount;d.morale+=t.morale*t.headcount;}}
 for(const d of Object.values(deptResults)){d.managementCoverage=r(d.headcount?d.managementCoverage/d.headcount:1);d.fatigue=r(d.headcount?d.fatigue/d.headcount:0);d.morale=r(d.headcount?d.morale/d.headcount:55);d.utilization=r(d.requiredWorkload/Math.max(1,d.availableCapacity));d.backlog=r(Math.max(0,d.requiredWorkload-d.availableCapacity));d.bottleneckLevel=r(clamp(d.utilization-1,0,2));d.projectCapacity=r(Math.max(0,d.availableCapacity-d.requiredWorkload)*.45);d.effectMultiplier=r(clamp((.96+(1-d.bottleneckLevel)*.04)*(.9+d.managementCoverage*.1)*(1-d.fatigue/500)*(0.85+d.morale/350),.55,1.12));}
 g.workforceResultsByDepartmentID=deptResults;g.workforceOfficeMetrics=office;syncDepartmentStaff(g);aggregate(g);return {departments:deptResults,office};}
function aggregate(g){const teams=g.workforceTeams||[];const total=teams.reduce((a,t)=>a+n(t.headcount),0);const w=(key,fb)=>total?teams.reduce((a,t)=>a+n(t[key],fb)*n(t.headcount),0)/total:fb;g.employeeSatisfaction=clamp(w('engagement',55),0,100);g.employeeAbility=clamp(w('averageSkill',50),0,100);g.organizationCulture=g.organizationCulture||{};g.organizationCulture.morale=clamp(w('morale',55),0,100);g.organizationCulture.turnoverRate=clamp(w('turnoverRisk',.08),0,.8);g.overtimeRisk=clamp(w('overtimeHours',0)/16,0,1);g.workforceKPI={totalHeadcount:r(total),storeHeadcount:r(teams.filter(t=>t.storeID).reduce((a,t)=>a+n(t.headcount),0)),officeHeadcount:r(teams.filter(t=>!t.storeID).reduce((a,t)=>a+n(t.headcount),0)),managerHeadcount:r(teams.reduce((a,t)=>a+n(t.managerHeadcount),0)),trainingHeadcount:r(teams.reduce((a,t)=>a+n(t.onboardingHeadcount),0)),weeklyPayroll:r(weeklyPayroll(g)),averageFatigue:r(w('fatigue',0)),averageMorale:r(w('morale',55)),turnoverRisk:r(g.organizationCulture.turnoverRate)};}
function weeklyPayroll(g){ensure(g);return (g.workforceTeams||[]).filter(t=>!t.storeID).reduce((a,t)=>a+n(t.averageWeeklySalary)*n(t.headcount),0);}
function departmentEffectMultiplier(g,id){ensure(g);const r=(g.workforceResultsByDepartmentID||{})[id];if(!r)return 1;return clamp(n(r.effectMultiplier,1),.55,1.12);}
function storeAdjustment(g,store,baseCapacity){ensure(g);const explicit=Object.prototype.hasOwnProperty.call(store,'capacity')&&store.capacity!==null&&store.capacity!==undefined;let t=(g.workforceTeams||[]).find(x=>x.storeID===store.id);if(!t){const b=(g.businesses||[]).find(x=>x.id===store.businessID)||{};t=makeTeam(g,{teamID:`wf-store-${store.id}`,storeID:store.id,roleID:'store-ops',headcount:Math.max(5,Math.round(n(b.wage,52500)/17500)),managerHeadcount:1,averageWeeklySalary:17500});g.workforceTeams.push(t);recompute(g);}const role=roleByID(t.roleID),needed=Math.max(1,Math.ceil(n(baseCapacity,1)/700));const mgmt=t.headcount>=3&&t.managerHeadcount<1?.92:1,staffRatio=clamp(t.availableHeadcount/needed,.35,1.05),fatigueAdj=clamp(1-n(t.fatigue)/250,.65,1.02),skillAdj=clamp(.9+n(t.averageSkill,50)/500,.85,1.08);const cap=explicit?Math.max(0,n(baseCapacity)):Math.max(0,Math.floor(n(baseCapacity)*staffRatio*mgmt*fatigueAdj));const res={storeID:store.id,requiredStaff:needed,actualStaff:t.headcount,managerHeadcount:t.managerHeadcount,staffLimitedCapacity:cap,staffingUtilization:r(needed/Math.max(1,t.availableHeadcount)),staffLostDemand:Math.max(0,n(baseCapacity)-cap),serviceQualityAdjustment:r((staffRatio>=1&&n(t.fatigue)<=30&&mgmt>=1)?0:(skillAdj*fatigueAdj*mgmt)-1),managementAdjustment:r(mgmt-1),fatigueAdjustment:r(fatigueAdj-1)};g.workforceResultsByStoreID[store.id]=res;return res;}
function updateEndOfWeek(g){ensure(g);recompute(g);const complaints=(g.employeeComplaintLog||[]).filter(x=>!x.resolved).length;for(const t of g.workforceTeams){const util=n(t.requiredWorkload)/Math.max(1,n(t.weeklyCapacity));t.utilization=r(util);t.backlog=r(Math.max(0,n(t.requiredWorkload)-n(t.weeklyCapacity)));t.overtimeHours=r(clamp((util-1)*12+complaints*.2+(1-n(t.managementCoverage,1))*4,0,18));const fatigueDelta=clamp((util-1)*7+t.overtimeHours*.25+(1-n(t.managementCoverage,1))*2-(g.benefitLevel||1)*.6-(util<.8?1.4:0),-4,8);t.fatigue=clamp(n(t.fatigue)+fatigueDelta,0,100);t.morale=clamp(n(t.morale)+(util<1?.25:-.7)-(t.fatigue>70?.9:0)+(g.remoteWorkEnabled?roleByID(t.roleID).remoteWorkCompatibility*.25:0),0,100);t.engagement=clamp(n(t.engagement)+(t.morale-50)/200-t.fatigue/500,0,100);t.turnoverRisk=clamp(.02+t.fatigue/260+(55-t.morale)/220+(1-n(t.managementCoverage,1))*.08+complaints*.005,0,.35);}processTurnover(g);recompute(g);}
function processTurnover(g){for(const t of g.workforceTeams){if(t.headcount<=0)continue;const risk=n(t.turnoverRisk),seed=stableHash(`${g.week}:${t.teamID}:turnover`);let leave=Math.floor(t.headcount*risk*.18+seed*.7);leave=Math.min(leave,Math.max(1,Math.ceil(t.headcount*.08)),t.headcount);if(leave>0&&risk>.12){t.headcount-=leave;t.availableHeadcount=Math.min(t.availableHeadcount,t.headcount);t.lastTurnoverHeadcount=leave;t.lastTurnoverCost=r(leave*n(t.averageWeeklySalary)*.5);}else t.lastTurnoverHeadcount=0;}}
function generateCandidates(g){ensure(g);g.workforceCandidates=g.workforceCandidates.filter(c=>c.status==='hired'||c.status==='rejected'||n(c.expiresWeek)>=n(g.week)-4).slice(-24);const open=g.workforceCandidates.filter(c=>c.status==='open'&&n(c.expiresWeek)>=n(g.week)).length;if(open>=6)return g.workforceCandidates;const roles=ROLES.filter(x=>x.corporateApplicable&&x.departmentID&&(g.departments||{})[x.departmentID]).concat(ROLES.filter(x=>x.storeApplicable).slice(0,1));for(let i=open;i<6;i++){const role=roles[i%Math.max(1,roles.length)]||ROLES[0],seed=stableHash(`${g.week}:${i}:${role.id}:candidate`),hc=role.category==='management'?1:1+Math.floor(seed*4);g.workforceCandidates.push({candidateID:`wf-cand-${g.nextCandidateSeq++}`,roleID:role.id,departmentID:role.departmentID,headcount:hc,averageSkill:r(clamp(role.requiredSkill-8+seed*22,20,92)),averageExperience:r(clamp(seed*55,0,85)),weeklySalaryPerPerson:r(role.baseWeeklySalary*(.9+seed*.35)),recruitmentFee:r(hc*role.baseWeeklySalary*(1.2+seed)),onboardingWeeks:1+Math.floor(role.trainingDifficulty),expectedMorale:r(50+seed*30),remoteCompatibility:role.remoteWorkCompatibility,expiresWeek:(g.week||1)+8,status:'open'});}return g.workforceCandidates;}
function hireCandidate(g,id){ensure(g);const c=g.workforceCandidates.find(x=>x.candidateID===id);if(!c||c.status!=='open')return {ok:false,error:'候補がありません'};if(n(g.companyCash)<n(c.recruitmentFee))return {ok:false,error:'会社資金が不足しています'};g.companyCash-=n(c.recruitmentFee);c.status='hired';const managers=c.roleID==='manager'?c.headcount:0;g.workforceTeams.push(makeTeam(g,{departmentID:c.departmentID,roleID:c.roleID,headcount:c.headcount,managerHeadcount:managers,averageSkill:c.averageSkill,averageExperience:c.averageExperience,averageWeeklySalary:c.weeklySalaryPerPerson,morale:c.expectedMorale,engagement:c.expectedMorale,onboardingHeadcount:c.headcount,createdWeek:g.week,lastUpdatedWeek:g.week}));syncDepartmentStaff(g);return {ok:true,cost:c.recruitmentFee};}
function startTraining(g,teamID,type){ensure(g);const t=g.workforceTeams.find(x=>x.teamID===teamID);if(!t)return {ok:false,error:'チームがありません'};if(g.workforceTrainings.some(x=>x.teamID===teamID&&x.trainingType===type&&x.status==='active'))return {ok:false,error:'研修中です'};const def={basic:[1,50000,3,.08],specialist:[2,120000,6,.15],management:[3,180000,5,.12]}[type]||[1,50000,3,.08];const tr={trainingID:`wf-train-${g.nextTrainingSeq++}`,teamID,trainingType:type,startWeek:g.week,endWeek:g.week+def[0],cost:def[1],skillGain:def[2],capacityReductionDuringTraining:def[3],status:'active'};g.workforceTrainings.push(tr);return {ok:true,training:tr};}
function advanceProjects(g){ensure(g);recompute(g);for(const p of g.workforceProjects){if(p.status==='completed'||p.status==='cancelled'||p.status==='failed')continue;if(p.status==='planned')p.status='active';if((p.dependencies||[]).some(id=>!g.workforceProjects.some(x=>x.projectID===id&&x.status==='completed'))){p.status='blocked';p.blockedReason='依存プロジェクト未完了';continue;}const d=g.workforceResultsByDepartmentID[p.ownerDepartmentID];if(!d){p.status='blocked';p.blockedReason='担当部門なし';continue;}if(n(g.companyCash)<n(p.weeklyBudget)){p.status='paused';p.blockedReason='予算不足';continue;}p.status='active';p.blockedReason='';const progress=clamp(n(d.projectCapacity)*(.8+n(d.managementCoverage)*.2)*(1-n(d.fatigue)/220),0,n(p.requiredEffort)-n(p.completedEffort));p.completedEffort=r(n(p.completedEffort)+progress);p.spentBudget=r(n(p.spentBudget)+n(p.weeklyBudget));g.companyCash-=n(p.weeklyBudget);if(p.completedEffort>=p.requiredEffort&&!p.benefitApplied){p.status='completed';p.completedWeek=g.week;p.benefitApplied=true;applyProjectBenefit(g,p);}}}
function applyProjectBenefit(g,p){if(p.benefitType==='departmentEffect'&&g.departments[p.ownerDepartmentID])g.departments[p.ownerDepartmentID].phase4ABonus=clamp(n(g.departments[p.ownerDepartmentID].phase4ABonus)+n(p.benefitValue,.02),0,.15);}
function validate(g){ensure(g);const errors=[],seen={teamID:new Set(),candidateID:new Set(),trainingID:new Set(),projectID:new Set()};function checkID(kind,obj){const id=obj[kind];if(!id)errors.push(`${kind}なし`);else if(seen[kind].has(id))errors.push(`${kind}重複 ${id}`);seen[kind].add(id);}for(const t of g.workforceTeams){checkID('teamID',t);for(const k of ['headcount','managerHeadcount','averageWeeklySalary','fatigue','morale','engagement','weeklyCapacity','requiredWorkload','utilization','backlog'])if(!Number.isFinite(n(t[k])))errors.push(`非有限 ${t.teamID}.${k}`);if(t.headcount<0)errors.push(`負の人数 ${t.teamID}`);if(t.availableHeadcount>t.headcount)errors.push(`available超過 ${t.teamID}`);if(t.managerHeadcount>t.headcount)errors.push(`管理職超過 ${t.teamID}`);if(t.departmentID&&!(g.departments||{})[t.departmentID])errors.push(`存在しない部門 ${t.departmentID}`);if(t.storeID&&!(g.stores||[]).some(s=>s.id===t.storeID))errors.push(`存在しない店舗 ${t.storeID}`);}for(const c of g.workforceCandidates)checkID('candidateID',c);for(const tr of g.workforceTrainings)checkID('trainingID',tr);for(const p of g.workforceProjects)checkID('projectID',p);const mirror={};for(const t of g.workforceTeams)if(t.departmentID&&!t.storeID)mirror[t.departmentID]=(mirror[t.departmentID]||0)+t.headcount;for(const [id,v] of Object.entries(mirror))if(Math.abs(n(g.departmentStaff?.[id])-v)>.001)errors.push(`departmentStaff不一致 ${id}`);return {ok:errors.length===0,errors,checkedWeek:g.week};}
Object.assign(exports,{ROLES,TARGET_BUSINESS_IDS,ensure,migrateV7,recompute,aggregate,syncDepartmentStaff,weeklyPayroll,departmentEffectMultiplier,storeAdjustment,updateEndOfWeek,generateCandidates,hireCandidate,startTraining,advanceProjects,validate,officeMetrics,workload});
})(__modules.workforce={},__modules.data);
})();
