// Script boundary: js/workforce.js (classic JavaScript)
(function(){'use strict';
if(!globalThis.__capitalismTycoonModules)throw new Error('Capitalism Tycoon runtime.js must be loaded before workforce.js.');
var __modules=globalThis.__capitalismTycoonModules;
if(!__modules.data)throw new Error('Capitalism Tycoon data module must be loaded before workforce.js.');
if(__modules.workforce)throw new Error('Capitalism Tycoon workforce module is already registered.');
(function(exports,data){
const MASTER=data.MASTER;
const TARGET_BUSINESS_IDS=Object.freeze(['ramen']);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):min));
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const r=v=>Math.round(n(v)*100)/100;
const roleRows=[
 ['store-ops','店舗運営',null,'store',17500,95,45,.8,9,.15,.9,1.1,.7,.35,true,false],
 ['operations','オペレーション','operations','corporate',65000,115,52,1.0,8,.45,1.0,1.0,.45,.55,false,true],
 ['marketing','マーケティング','marketing','corporate',70000,105,55,1.1,7,.7,1.0,.9,.35,.7,false,true],
 ['hr','人事','hr','corporate',62000,100,50,1.0,8,.75,.9,1.2,.25,.55,false,true],
 ['finance','財務','accounting','corporate',76000,98,58,1.2,7,.8,.8,.8,.2,.6,false,true],
 ['dx','DX・IT','dx','corporate',85000,110,62,1.35,6,.85,1.1,.75,.45,.85,false,true],
 ['product','商品・R&D','product','corporate',82000,104,60,1.3,6,.65,1.0,.85,.75,.9,false,true],
 ['investment','投資・M&A','investment','corporate',90000,94,64,1.45,6,.75,.9,.9,.2,.75,false,true],
 ['procurement','調達・物流','operations','corporate',68000,112,54,1.05,8,.5,1.05,1.0,.35,.65,false,true],
 ['manager','管理職',null,'management',95000,32,62,1.4,12,.65,.8,.7,.25,.5,true,true]
];
const ROLES=Object.freeze(roleRows.map(x=>({id:x[0],name:x[1],departmentID:x[2],category:x[3],baseWeeklySalary:x[4],baseCapacityPerPerson:x[5],requiredSkill:x[6],trainingDifficulty:x[7],managementSpan:x[8],remoteWorkCompatibility:x[9],fatigueSensitivity:x[10],turnoverSensitivity:x[11],qualityContribution:x[12],projectContribution:x[13],storeApplicable:x[14],corporateApplicable:x[15]})));
const TRAINING_TYPES=Object.freeze({basic:{id:'basic',name:'基礎研修',weeks:1,cost:50000,skillGain:3,trainingGain:2,capacityReduction:.08},specialist:{id:'specialist',name:'専門研修',weeks:2,cost:120000,skillGain:6,trainingGain:4,capacityReduction:.15},management:{id:'management',name:'管理職研修',weeks:3,cost:180000,skillGain:4,trainingGain:6,capacityReduction:.12,managerGain:1}});
const PROJECT_TEMPLATES=Object.freeze([
 {templateID:'store-standardization',name:'店舗運営標準化',ownerDepartmentID:'operations',requiredEffort:45,weeklyBudget:120000,totalBudget:720000,requiredSkill:50,dependencies:[],benefitType:'departmentEffect',benefitValue:.025},
 {templateID:'training-program',name:'社員研修プログラム',ownerDepartmentID:'hr',requiredEffort:40,weeklyBudget:100000,totalBudget:600000,requiredSkill:50,dependencies:[],benefitType:'morale',benefitValue:2},
 {templateID:'dx-rollout',name:'DX導入',ownerDepartmentID:'dx',requiredEffort:55,weeklyBudget:180000,totalBudget:1080000,requiredSkill:58,dependencies:[],benefitType:'departmentEffect',benefitValue:.03},
 {templateID:'procurement-improvement',name:'調達・在庫改善',ownerDepartmentID:'operations',requiredEffort:42,weeklyBudget:130000,totalBudget:780000,requiredSkill:52,dependencies:[],benefitType:'supplyBacklog',benefitValue:.03},
 {templateID:'quality-improvement',name:'品質改善',ownerDepartmentID:'product',requiredEffort:48,weeklyBudget:160000,totalBudget:960000,requiredSkill:56,dependencies:[],benefitType:'departmentEffect',benefitValue:.025}
]);
const roleByID=id=>ROLES.find(x=>x.id===id)||ROLES[0];
const deptRole=id=>ROLES.find(x=>x.departmentID===id)||ROLES.find(x=>x.id===id)||ROLES[1];
const deptMaster=id=>(MASTER.departments||[]).find(d=>d.id===id)||null;
function stableHash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0)/4294967295;}
function ensure(g){if(!Array.isArray(g.workforceTeams))g.workforceTeams=[];if(!Array.isArray(g.workforceCandidates))g.workforceCandidates=[];if(!Array.isArray(g.workforceTrainings))g.workforceTrainings=[];if(!Array.isArray(g.workforceProjects))g.workforceProjects=[];if(!g.workforceResultsByDepartmentID||typeof g.workforceResultsByDepartmentID!=='object')g.workforceResultsByDepartmentID={};if(!g.workforceResultsByStoreID||typeof g.workforceResultsByStoreID!=='object')g.workforceResultsByStoreID={};if(!g.workforceSettings||typeof g.workforceSettings!=='object')g.workforceSettings={detailStoreBusinessIDs:['ramen']};g.nextWorkforceTeamSeq=Math.max(1,Math.floor(n(g.nextWorkforceTeamSeq,1)));g.nextCandidateSeq=Math.max(1,Math.floor(n(g.nextCandidateSeq,1)));g.nextTrainingSeq=Math.max(1,Math.floor(n(g.nextTrainingSeq,1)));g.nextProjectSeq=Math.max(1,Math.floor(n(g.nextProjectSeq,1)));g.nextWorkforceEventSeq=Math.max(1,Math.floor(n(g.nextWorkforceEventSeq,1)));return g;}
function normalizeTeam(t,g){const role=roleByID(t.roleID);t.headcount=Math.max(0,Math.floor(n(t.headcount)));t.managerHeadcount=clamp(Math.floor(n(t.managerHeadcount)),0,t.headcount);t.onboardingHeadcount=clamp(Math.floor(n(t.onboardingHeadcount)),0,t.headcount);t.availableHeadcount=clamp(Math.floor(n(t.availableHeadcount,t.headcount-t.onboardingHeadcount)),0,t.headcount);t.averageSkill=clamp(n(t.averageSkill,g.employeeAbility||50),1,100);t.averageExperience=clamp(n(t.averageExperience,20),0,100);t.averageWeeklySalary=Math.max(0,n(t.averageWeeklySalary,role.baseWeeklySalary));t.morale=clamp(n(t.morale,g.organizationCulture?.morale||55),0,100);t.fatigue=clamp(n(t.fatigue,20),0,100);t.engagement=clamp(n(t.engagement,g.employeeSatisfaction||55),0,100);t.trainingLevel=clamp(n(t.trainingLevel,0),0,100);t.remoteRatio=clamp(n(t.remoteRatio,0),0,1);t.weeklyCapacity=Math.max(0,n(t.weeklyCapacity));t.requiredWorkload=Math.max(0,n(t.requiredWorkload));t.utilization=Math.max(0,n(t.utilization));t.overtimeHours=Math.max(0,n(t.overtimeHours));t.backlog=Math.max(0,n(t.backlog));t.turnoverRisk=clamp(n(t.turnoverRisk),0,.8);t.onboardingBatches=Array.isArray(t.onboardingBatches)?t.onboardingBatches:[];t.status=t.status||'active';return t;}
function makeTeam(g,o){ensure(g);const role=roleByID(o.roleID);return normalizeTeam({teamID:o.teamID||`wf-team-${g.nextWorkforceTeamSeq++}`,departmentID:o.departmentID??role.departmentID??null,storeID:o.storeID??null,branchOfficeID:o.branchOfficeID??null,roleID:role.id,headcount:Math.max(0,Math.floor(n(o.headcount))),managerHeadcount:Math.max(0,Math.floor(n(o.managerHeadcount,Math.floor(n(o.headcount)/role.managementSpan)))),averageSkill:n(o.averageSkill,g.employeeAbility||50),averageExperience:n(o.averageExperience,20),averageWeeklySalary:n(o.averageWeeklySalary,role.baseWeeklySalary),morale:n(o.morale,g.organizationCulture?.morale||55),fatigue:n(o.fatigue,20),engagement:n(o.engagement,g.employeeSatisfaction||55),trainingLevel:n(o.trainingLevel,0),onboardingHeadcount:n(o.onboardingHeadcount,0),availableHeadcount:n(o.availableHeadcount,n(o.headcount)-n(o.onboardingHeadcount,0)),remoteRatio:n(o.remoteRatio,0),weeklyCapacity:0,requiredWorkload:0,utilization:0,overtimeHours:0,backlog:0,turnoverRisk:0,status:o.status||'active',onboardingBatches:Array.isArray(o.onboardingBatches)?o.onboardingBatches:[],createdWeek:Math.max(1,Math.floor(n(o.createdWeek,g.week||1))),lastUpdatedWeek:Math.max(1,Math.floor(n(o.lastUpdatedWeek,g.week||1)))},g);}
function legacyDepartmentPayroll(g,departmentID,headcount){const d=(g.departments||{})[departmentID]||deptMaster(departmentID)||{};return Math.max(0,n(d.weeklyCost))+Math.max(0,Math.floor(n(headcount))-1)*65000;}
function createDepartmentTeam(g,departmentID,headcount=1,options={}){ensure(g);const hc=Math.max(0,Math.floor(n(headcount,1)));const d=(g.departments||{})[departmentID]||deptMaster(departmentID);if(!d||hc<=0)return null;let existing=g.workforceTeams.find(t=>t.departmentID===departmentID&&!t.storeID&&t.status!=='removed');if(existing){normalizeTeam(existing,g);return existing;}const role=deptRole(departmentID);const payroll=n(options.averageWeeklySalary,legacyDepartmentPayroll(g,departmentID,hc)/Math.max(1,hc));const team=makeTeam(g,{teamID:options.teamID||`wf-dept-${departmentID}`,departmentID,roleID:role.id,headcount:hc,managerHeadcount:Math.floor(hc/role.managementSpan),averageWeeklySalary:payroll,averageSkill:g.employeeAbility,morale:g.organizationCulture?.morale,engagement:g.employeeSatisfaction,createdWeek:g.week||1,lastUpdatedWeek:g.week||1});g.workforceTeams.push(team);syncDepartmentStaff(g);return team;}
function ensureDepartmentTeam(g,departmentID){const hc=Math.max(0,Math.floor(n((g.departmentStaff||{})[departmentID],(g.departments||{})[departmentID]?1:0)));return createDepartmentTeam(g,departmentID,hc||1);}
function createStoreTeam(g,storeID,options={}){ensure(g);const store=(g.stores||[]).find(s=>s.id===storeID);if(!store||TARGET_BUSINESS_IDS.indexOf(store.businessID)<0)return null;let team=g.workforceTeams.find(t=>t.storeID===storeID&&t.status!=='removed');if(team){normalizeTeam(team,g);return team;}const b=(g.businesses||[]).find(x=>x.id===store.businessID)||{};const hc=Math.max(5,Math.round(n(b.wage,52500)/17500));team=makeTeam(g,{teamID:options.teamID||`wf-store-${storeID}`,storeID,roleID:'store-ops',headcount:n(options.headcount,hc),managerHeadcount:n(options.managerHeadcount,hc>=3?1:0),averageWeeklySalary:n(options.averageWeeklySalary,hc?n(b.wage,52500)/hc:17500),averageSkill:g.employeeAbility,morale:g.organizationCulture?.morale,engagement:g.employeeSatisfaction,createdWeek:g.week||1,lastUpdatedWeek:g.week||1});team.baseHeadcount=Math.max(0,Math.floor(n(options.baseHeadcount,hc)));g.workforceTeams.push(team);return team;}
function syncDepartmentStaff(g){ensure(g);const mirror={};for(const d of Object.keys(g.departments||{}))mirror[d]=0;for(const t of g.workforceTeams){normalizeTeam(t,g);if(t.departmentID&&!t.storeID&&t.status!=='removed')mirror[t.departmentID]=(mirror[t.departmentID]||0)+Math.max(0,Math.floor(n(t.headcount)));}g.departmentStaff=Object.assign(g.departmentStaff||{},mirror);return mirror;}
function migrateV7(g){ensure(g);if(!g.workforceMigrationV7Applied){for(const [id,c] of Object.entries(g.departmentStaff||{})){const hc=Math.max(0,Math.floor(n(c)));if((g.departments||{})[id]&&hc>0)createDepartmentTeam(g,id,hc,{teamID:`wf-dept-${id}`,averageWeeklySalary:legacyDepartmentPayroll(g,id,hc)/Math.max(1,hc)});}for(const st of (g.stores||[]))createStoreTeam(g,st.id);g.workforceMigrationV7Applied=true;}syncDepartmentStaff(g);g.saveVersion=7;return g;}
function officeMetrics(g){ensure(g);let office=0,remoteCompatible=0;for(const t of g.workforceTeams){if(!t.storeID){office+=n(t.headcount);remoteCompatible+=n(t.headcount)*roleByID(t.roleID).remoteWorkCompatibility;}}const remoteEnabled=!!g.remoteWorkEnabled,remoteSeats=remoteEnabled?remoteCompatible*.45:0,cap=n(g.officeCapacity,0)+(g.branchOffices||[]).reduce((a,b)=>a+n(b.capacity),0);const seated=Math.max(0,office-remoteSeats),over=Math.max(0,seated-cap);return {officeHeadcount:r(office),officeCapacity:r(cap),remoteCompatibleHeadcount:r(remoteCompatible),overCapacityHeadcount:r(over),seatUtilization:cap>0?r(seated/cap):0,officeConstraintPenalty:clamp(1-over/Math.max(1,office)*.25,.75,1)};}
function workload(g,dept){const stores=(g.stores||[]).filter(s=>s.status==='open');const ramen=stores.filter(s=>TARGET_BUSINESS_IDS.indexOf(s.businessID)>=0);const supplyOrders=(g.purchaseOrders||[]).filter(o=>o.orderStatus!=='paid'&&o.orderStatus!=='cancelled').length;const supplyReduction=clamp(n(g.workforceSettings?.supplyBacklogReduction),0,.15);const map={operations:stores.length*55+ramen.length*25,marketing:stores.length*30+Object.keys(g.marketResultsByBusinessID||{}).length*20,hr:(g.workforceTeams||[]).reduce((a,t)=>a+n(t.headcount),0)*4+(g.workforceCandidates||[]).filter(c=>c.status==='open').length*18,accounting:stores.length*20+(g.finance?.transactions?.length||0)*.08+Object.keys(g.executives||{}).length*8,dx:stores.length*18+n((g.businesses||[]).reduce((a,b)=>a+n(b.dx),0))*.5,product:(g.productVentures||[]).filter(p=>p.status==='developing').length*55,investment:(g.startups||[]).filter(s=>s.ownedCompany>0).length*20+(g.acquisitionTargets||[]).length*25};map.operations=r(map.operations*(1-supplyReduction*.35));map.procurement=r((ramen.length*50+supplyOrders*14+(g.supplyChainEvents||[]).length*.02)*(1-supplyReduction));return r(map[dept]||0);}
function activeTrainingsFor(g,teamID){return (g.workforceTrainings||[]).filter(x=>x.teamID===teamID&&x.status==='active');}
function recompute(g){ensure(g);const office=officeMetrics(g),deptResults={};for(const t of g.workforceTeams){normalizeTeam(t,g);const role=roleByID(t.roleID);const reqManagers=Math.ceil(Math.max(0,t.headcount-t.managerHeadcount)/Math.max(1,role.managementSpan));const coverage=reqManagers?clamp(t.managerHeadcount/reqManagers,0,1):1;const skill=clamp(.75+n(t.averageSkill,50)/100*.5,.6,1.35),exp=clamp(.85+n(t.averageExperience,20)/200,.75,1.25),training=clamp(1+n(t.trainingLevel,0)/250,.9,1.25),fat=clamp(1-n(t.fatigue,0)/180*role.fatigueSensitivity,.55,1.05),mor=clamp(.75+n(t.morale,55)/220,.7,1.18),mgmt=clamp(.72+coverage*.33,.65,1.05),officeMult=t.storeID?1:office.officeConstraintPenalty;let cap=t.availableHeadcount*role.baseCapacityPerPerson*skill*exp*training*fat*mor*mgmt*officeMult;for(const tr of activeTrainingsFor(g,t.teamID))cap*=clamp(1-n(tr.capacityReductionDuringTraining),.5,1);if(t.managerHeadcount>reqManagers+1)cap*=clamp(1-(t.managerHeadcount-reqManagers-1)*.03,.82,1);t.weeklyCapacity=r(cap);t.managementCoverage=r(coverage);t.requiredManagers=reqManagers;t.availableManagers=t.managerHeadcount;t.spanOfControl=role.managementSpan;t.managementPenalty=r(mgmt);t.lastUpdatedWeek=g.week||1;if(t.departmentID&&!t.storeID){const d=deptResults[t.departmentID]||(deptResults[t.departmentID]={departmentID:t.departmentID,headcount:0,managerHeadcount:0,availableCapacity:0,requiredWorkload:workload(g,t.departmentID),backlog:0,utilization:0,bottleneckLevel:0,managementCoverage:0,fatigue:0,morale:0,effectMultiplier:1,projectCapacity:0});d.headcount+=t.headcount;d.managerHeadcount+=t.managerHeadcount;d.availableCapacity+=t.weeklyCapacity;d.managementCoverage+=coverage*t.headcount;d.fatigue+=t.fatigue*t.headcount;d.morale+=t.morale*t.headcount;}}
 for(const [deptID,d] of Object.entries(deptResults)){const teams=g.workforceTeams.filter(t=>t.departmentID===deptID&&!t.storeID&&t.status!=='removed');const totalCap=teams.reduce((a,t)=>a+n(t.weeklyCapacity),0);let assigned=0;teams.forEach((t,i)=>{const share=totalCap>0?n(t.weeklyCapacity)/totalCap:1/Math.max(1,teams.length);const req=i===teams.length-1?Math.max(0,n(d.requiredWorkload)-assigned):r(n(d.requiredWorkload)*share);assigned+=req;t.requiredWorkload=r(req);t.utilization=r(t.requiredWorkload/Math.max(1,t.weeklyCapacity));t.backlog=r(Math.max(0,t.requiredWorkload-t.weeklyCapacity));});d.managementCoverage=r(d.headcount?d.managementCoverage/d.headcount:1);d.fatigue=r(d.headcount?d.fatigue/d.headcount:0);d.morale=r(d.headcount?d.morale/d.headcount:55);d.utilization=r(d.requiredWorkload/Math.max(1,d.availableCapacity));d.backlog=r(Math.max(0,d.requiredWorkload-d.availableCapacity));d.bottleneckLevel=r(clamp(d.utilization-1,0,2));d.projectCapacity=r(Math.max(0,d.availableCapacity-d.requiredWorkload)*.45);d.effectMultiplier=r(clamp((.96+(1-d.bottleneckLevel)*.04)*(.9+d.managementCoverage*.1)*(1-d.fatigue/500)*(0.85+d.morale/350),.55,1.12));}
 g.workforceResultsByDepartmentID=deptResults;g.workforceOfficeMetrics=office;syncDepartmentStaff(g);aggregate(g);return {departments:deptResults,office};}
function aggregate(g){const teams=g.workforceTeams||[];const total=teams.reduce((a,t)=>a+n(t.headcount),0);const w=(key,fb)=>total?teams.reduce((a,t)=>a+n(t[key],fb)*n(t.headcount),0)/total:fb;g.employeeSatisfaction=clamp(w('engagement',55),0,100);g.employeeAbility=clamp(w('averageSkill',50),0,100);g.organizationCulture=g.organizationCulture||{};g.organizationCulture.morale=clamp(w('morale',55),0,100);g.organizationCulture.turnoverRate=clamp(w('turnoverRisk',.08),0,.8);g.overtimeRisk=clamp(w('overtimeHours',0)/16,0,1);g.workforceKPI={totalHeadcount:r(total),storeHeadcount:r(teams.filter(t=>t.storeID).reduce((a,t)=>a+n(t.headcount),0)),officeHeadcount:r(teams.filter(t=>!t.storeID).reduce((a,t)=>a+n(t.headcount),0)),managerHeadcount:r(teams.reduce((a,t)=>a+n(t.managerHeadcount),0)),trainingHeadcount:r(teams.reduce((a,t)=>a+n(t.onboardingHeadcount),0)),weeklyPayroll:r(weeklyPayroll(g)),averageFatigue:r(w('fatigue',0)),averageMorale:r(w('morale',55)),turnoverRisk:r(g.organizationCulture.turnoverRate)};}
function weeklyPayroll(g){ensure(g);return r((g.workforceTeams||[]).filter(t=>!t.storeID&&t.status!=='removed').reduce((a,t)=>a+n(t.averageWeeklySalary)*n(t.headcount),0));}
function storeExtraPayroll(g,storeID){ensure(g);const t=(g.workforceTeams||[]).find(x=>x.storeID===storeID&&x.status!=='removed');if(!t)return 0;const base=Math.max(0,Math.floor(n(t.baseHeadcount,t.headcount)));return r(Math.max(0,n(t.headcount)-base)*n(t.averageWeeklySalary));}
function departmentEffectMultiplier(g,id){ensure(g);const res=(g.workforceResultsByDepartmentID||{})[id];if(!res)return 1;return clamp(n(res.effectMultiplier,1),.55,1.12);}
function storeAdjustment(g,store,baseCapacity){ensure(g);if(TARGET_BUSINESS_IDS.indexOf(store.businessID)<0)return null;const explicit=Object.prototype.hasOwnProperty.call(store,'capacity')&&store.capacity!==null&&store.capacity!==undefined;const t=createStoreTeam(g,store.id);normalizeTeam(t,g);if(!t.weeklyCapacity){const role=roleByID(t.roleID);t.weeklyCapacity=r(t.availableHeadcount*role.baseCapacityPerPerson);}const needed=Math.max(1,Math.ceil(n(baseCapacity,1)/700)),mgmt=t.headcount>=3&&t.managerHeadcount<1?.92:1,staffRatio=clamp(t.availableHeadcount/needed,.35,1.05),fatigueAdj=clamp(1-n(t.fatigue)/250,.65,1.02),skillAdj=clamp(.9+n(t.averageSkill,50)/500,.85,1.08);const cap=explicit?Math.max(0,n(baseCapacity)):Math.max(0,Math.floor(n(baseCapacity)*staffRatio*mgmt*fatigueAdj));t.requiredWorkload=r(needed*40*([0,.55,.8,1,1.24][store.operatingHours||3]||1));t.utilization=r(t.requiredWorkload/Math.max(1,t.weeklyCapacity));t.backlog=r(Math.max(0,t.requiredWorkload-t.weeklyCapacity));const res={storeID:store.id,requiredStaff:needed,actualStaff:t.headcount,managerHeadcount:t.managerHeadcount,staffLimitedCapacity:cap,staffingUtilization:r(needed/Math.max(1,t.availableHeadcount)),staffLostDemand:Math.max(0,n(baseCapacity)-cap),serviceQualityAdjustment:r((staffRatio>=1&&n(t.fatigue)<=30&&mgmt>=1)?0:(skillAdj*fatigueAdj*mgmt)-1),managementAdjustment:r(mgmt-1),fatigueAdjustment:r(fatigueAdj-1)};g.workforceResultsByStoreID[store.id]=res;return res;}
function processWeekStart(g){ensure(g);let completedOnboarding=0,completedTraining=0;for(const t of g.workforceTeams){normalizeTeam(t,g);for(const b of t.onboardingBatches){if(b.status==='active'&&n(g.week)>=n(b.endWeek)){b.status='completed';b.completedWeek=g.week;completedOnboarding+=Math.max(0,Math.floor(n(b.headcount)));}}t.onboardingHeadcount=Math.max(0,t.onboardingBatches.filter(b=>b.status==='active').reduce((a,b)=>a+n(b.headcount),0));t.availableHeadcount=clamp(t.headcount-t.onboardingHeadcount,0,t.headcount);}for(const tr of g.workforceTrainings){if(tr.status==='active'&&n(g.week)>=n(tr.endWeek)){const t=g.workforceTeams.find(x=>x.teamID===tr.teamID);if(t&&!tr.effectApplied){t.averageSkill=clamp(n(t.averageSkill)+n(tr.skillGain),1,100);t.trainingLevel=clamp(n(t.trainingLevel)+n(tr.trainingGain,0),0,100);if(n(tr.managerGain)>0)t.managerHeadcount=clamp(t.managerHeadcount+n(tr.managerGain),0,t.headcount);tr.effectApplied=true;completedTraining++;}tr.status='completed';tr.completedWeek=g.week;}}if(completedOnboarding>0)g.news?.unshift?.(`第${g.week}週：オンボーディング${completedOnboarding}名が完了しました。`);if(completedTraining>0)g.news?.unshift?.(`第${g.week}週：研修${completedTraining}件が完了しました。`);recompute(g);return {completedOnboarding,completedTraining};}
function updateEndOfWeek(g){ensure(g);if(g.lastWorkforceUpdateWeek===g.week)return g.lastWorkforceUpdateResult||{turnoverCost:0,turnoverHeadcount:0,skipped:true};recompute(g);const complaints=(g.employeeComplaintLog||[]).filter(x=>!x.resolved&&x.status!=='resolved').length;for(const t of g.workforceTeams){const util=n(t.requiredWorkload)/Math.max(1,n(t.weeklyCapacity));t.utilization=r(util);t.backlog=r(Math.max(0,n(t.requiredWorkload)-n(t.weeklyCapacity)));t.overtimeHours=r(clamp((util-1)*12+complaints*.2+(1-n(t.managementCoverage,1))*4,0,18));const fatigueDelta=clamp((util-1)*7+t.overtimeHours*.25+(1-n(t.managementCoverage,1))*2-(g.benefitLevel||1)*.6-(util<.8?1.4:0),-4,8);t.fatigue=clamp(n(t.fatigue)+fatigueDelta,0,100);t.morale=clamp(n(t.morale)+(util<1?.25:-.7)-(t.fatigue>70?.9:0)+(g.remoteWorkEnabled?roleByID(t.roleID).remoteWorkCompatibility*.25:0),0,100);t.engagement=clamp(n(t.engagement)+(t.morale-50)/200-t.fatigue/500,0,100);t.turnoverRisk=clamp(.02+t.fatigue/260+(55-t.morale)/220+(1-n(t.managementCoverage,1))*.08+complaints*.005,0,.35);}const turnover=processTurnover(g);g.lastWorkforceUpdateWeek=g.week;g.workforceUpdateCountForWeek=n(g.workforceUpdateCountForWeek)+1;g.lastWorkforceUpdateResult=turnover;recompute(g);return turnover;}
function processTurnover(g){let cost=0,headcount=0;for(const t of g.workforceTeams){if(t.headcount<=0)continue;const risk=n(t.turnoverRisk),seed=stableHash(`${g.week}:${t.teamID}:turnover`);let leave=Math.floor(t.headcount*risk*.18+seed*.7);leave=Math.min(leave,Math.max(1,Math.ceil(t.headcount*.08)),t.headcount);if(leave>0&&risk>.12){const actualLeave=leave;t.headcount-=actualLeave;t.managerHeadcount=clamp(t.managerHeadcount,0,t.headcount);let remaining=actualLeave;t.onboardingBatches=(t.onboardingBatches||[]).map(b=>{if(b.status!=='active'||remaining<=0)return b;const reduce=Math.min(n(b.headcount),remaining);remaining-=reduce;b.headcount=Math.max(0,n(b.headcount)-reduce);if(b.headcount<=0)b.status='cancelled';return b;});t.onboardingHeadcount=clamp(t.onboardingBatches.filter(b=>b.status==='active').reduce((a,b)=>a+n(b.headcount),0),0,t.headcount);t.availableHeadcount=clamp(t.headcount-t.onboardingHeadcount,0,t.headcount);const severance=r(actualLeave*n(t.averageWeeklySalary)*.5);cost+=severance;headcount+=actualLeave;t.lastTurnoverHeadcount=actualLeave;t.lastTurnoverCost=severance;}else{t.lastTurnoverHeadcount=0;t.lastTurnoverCost=0;}}syncDepartmentStaff(g);return {turnoverCost:r(cost),turnoverHeadcount:headcount};}
function generateCandidates(g){ensure(g);g.workforceCandidates=g.workforceCandidates.filter(c=>c.status==='hired'||c.status==='rejected'||n(c.expiresWeek)>=n(g.week)-4).slice(-24);const open=g.workforceCandidates.filter(c=>c.status==='open'&&n(c.expiresWeek)>=n(g.week)).length;if(open>=6)return g.workforceCandidates;const targetStores=(g.stores||[]).filter(s=>TARGET_BUSINESS_IDS.indexOf(s.businessID)>=0&&s.status!=='closed');const roles=ROLES.filter(x=>x.corporateApplicable&&x.departmentID&&(g.departments||{})[x.departmentID]).concat(targetStores.length?ROLES.filter(x=>x.storeApplicable).slice(0,1):[]);for(let i=open;i<6;i++){const role=roles[i%Math.max(1,roles.length)]||ROLES[0],seed=stableHash(`${g.week}:${i}:${role.id}:candidate`),hc=role.category==='management'?1:1+Math.floor(seed*4),store=role.storeApplicable?targetStores[Math.floor(seed*targetStores.length)%targetStores.length]:null;g.workforceCandidates.push({candidateID:`wf-cand-${g.nextCandidateSeq++}`,roleID:role.id,departmentID:role.departmentID,storeID:store?store.id:null,targetStoreID:store?store.id:null,headcount:hc,averageSkill:r(clamp(role.requiredSkill-8+seed*22,20,92)),averageExperience:r(clamp(seed*55,0,85)),weeklySalaryPerPerson:r(role.baseWeeklySalary*(.9+seed*.35)),recruitmentFee:r(hc*role.baseWeeklySalary*(1.2+seed)),onboardingWeeks:1+Math.floor(role.trainingDifficulty),expectedMorale:r(50+seed*30),remoteCompatibility:role.remoteWorkCompatibility,expiresWeek:(g.week||1)+8,status:'open'});}return g.workforceCandidates;}
function addOnboardingBatch(g,t,headcount,weeks,candidateID=null){const hc=Math.max(0,Math.floor(n(headcount)));if(hc<=0)return null;t.onboardingBatches=Array.isArray(t.onboardingBatches)?t.onboardingBatches:[];const batch={batchID:`wf-onboard-${g.nextWorkforceEventSeq++}`,headcount:hc,startWeek:g.week,endWeek:g.week+Math.max(1,Math.floor(n(weeks,1))),candidateID,status:'active'};t.onboardingBatches.push(batch);t.onboardingHeadcount+=hc;t.availableHeadcount=clamp(t.headcount-t.onboardingHeadcount,0,t.headcount);return batch;}
function weighted(oldVal,oldCount,newVal,newCount){return r((n(oldVal)*Math.max(0,n(oldCount))+n(newVal)*Math.max(0,n(newCount)))/Math.max(1,n(oldCount)+n(newCount)));}
function applyCandidateAverages(t,hc,options){const old=t.headcount;t.averageSkill=weighted(t.averageSkill,old,n(options.averageSkill,t.averageSkill),hc);t.averageExperience=weighted(t.averageExperience,old,n(options.averageExperience,t.averageExperience),hc);t.averageWeeklySalary=weighted(t.averageWeeklySalary,old,n(options.weeklySalaryPerPerson,t.averageWeeklySalary),hc);t.morale=weighted(t.morale,old,n(options.expectedMorale,t.morale),hc);t.engagement=weighted(t.engagement,old,n(options.expectedMorale,t.engagement),hc);t.remoteRatio=weighted(t.remoteRatio,old,n(options.remoteCompatibility,t.remoteRatio),hc);}
function addDepartmentHeadcount(g,departmentID,count=1,options={}){const t=ensureDepartmentTeam(g,departmentID),hc=Math.max(1,Math.floor(n(count,1)));if(!t)return null;applyCandidateAverages(t,hc,options);t.headcount+=hc;addOnboardingBatch(g,t,hc,n(options.onboardingWeeks,1),options.candidateID||null);syncDepartmentStaff(g);recompute(g);return t;}
function addStoreHeadcount(g,storeID,count=1,options={}){const store=(g.stores||[]).find(s=>s.id===storeID);if(!store||TARGET_BUSINESS_IDS.indexOf(store.businessID)<0)return null;const t=createStoreTeam(g,storeID),hc=Math.max(1,Math.floor(n(count,1)));applyCandidateAverages(t,hc,options);t.headcount+=hc;t.managerHeadcount=clamp(t.managerHeadcount+(roleByID(options.roleID).category==='management'?hc:0),0,t.headcount);addOnboardingBatch(g,t,hc,n(options.onboardingWeeks,1),options.candidateID||null);recompute(g);return t;}
function hireCandidate(g,id,finance){ensure(g);const c=g.workforceCandidates.find(x=>x.candidateID===id);if(!c||c.status!=='open')return {ok:false,error:'候補がありません'};if(n(g.companyCash)<n(c.recruitmentFee))return {ok:false,error:'会社資金が不足しています'};const role=roleByID(c.roleID);if(role.storeApplicable){const storeID=c.targetStoreID||c.storeID;if(!storeID)return {ok:false,error:'対象店舗がありません'};const store=(g.stores||[]).find(s=>s.id===storeID);if(!store||TARGET_BUSINESS_IDS.indexOf(store.businessID)<0)return {ok:false,error:'対象店舗がありません'};}const used=(g.workforceTeams||[]).filter(t=>!t.storeID).reduce((a,t)=>a+n(t.headcount),0);if(c.departmentID&&used+n(c.headcount)>n(g.officeCapacity,0)+(g.branchOffices||[]).reduce((a,b)=>a+n(b.capacity),0)+10)return {ok:false,error:'オフィス定員に注意してください'};g.companyCash-=n(c.recruitmentFee);finance?.event?.(g,'payroll',n(c.recruitmentFee),{cashEffect:-n(c.recruitmentFee),profitEffect:-n(c.recruitmentFee),sourceType:'workforceCandidateHire',sourceID:c.candidateID,idempotencyKey:`workforce-hire-${c.candidateID}`,operationID:`workforce-hire-${c.candidateID}`,description:'採用手数料'});c.status='hired';const options={roleID:c.roleID,weeklySalaryPerPerson:c.weeklySalaryPerPerson,onboardingWeeks:c.onboardingWeeks,candidateID:c.candidateID,averageSkill:c.averageSkill,averageExperience:c.averageExperience,expectedMorale:c.expectedMorale,remoteCompatibility:c.remoteCompatibility};if(role.storeApplicable)addStoreHeadcount(g,c.targetStoreID||c.storeID,c.headcount,options);else addDepartmentHeadcount(g,c.departmentID,c.headcount,options);return {ok:true,cost:c.recruitmentFee};}
function startTraining(g,teamID,type,finance){ensure(g);const t=g.workforceTeams.find(x=>x.teamID===teamID);if(!t)return {ok:false,error:'チームがありません'};const def=TRAINING_TYPES[type]||TRAINING_TYPES.basic;if(g.workforceTrainings.some(x=>x.teamID===teamID&&x.trainingType===def.id&&x.status==='active'))return {ok:false,error:'研修中です'};if(n(g.companyCash)<def.cost)return {ok:false,error:'会社資金が不足しています'};g.companyCash-=def.cost;finance?.event?.(g,'headOfficeExpense',def.cost,{cashEffect:-def.cost,profitEffect:-def.cost,sourceType:'workforceTraining',sourceID:`${teamID}-${def.id}-${g.week}`,idempotencyKey:`workforce-training-${teamID}-${def.id}-${g.week}`,operationID:`workforce-training-${teamID}-${def.id}-${g.week}`,description:def.name});const tr={trainingID:`wf-train-${g.nextTrainingSeq++}`,teamID,trainingType:def.id,startWeek:g.week,endWeek:g.week+def.weeks,cost:def.cost,skillGain:def.skillGain,trainingGain:def.trainingGain,managerGain:def.managerGain||0,capacityReductionDuringTraining:def.capacityReduction,status:'active',effectApplied:false};g.workforceTrainings.push(tr);recompute(g);return {ok:true,training:tr};}
function startProject(g,templateID){ensure(g);const t=PROJECT_TEMPLATES.find(x=>x.templateID===templateID);if(!t)return {ok:false,error:'テンプレートがありません'};if(!(g.departments||{})[t.ownerDepartmentID])return {ok:false,error:'担当部門がありません'};if(g.workforceProjects.some(p=>p.templateID===templateID&&['planned','active','blocked','paused'].includes(p.status)))return {ok:false,error:'同じプロジェクトが進行中です'};const projectID=`wf-proj-${g.nextProjectSeq++}`;const p={projectID,templateID:t.templateID,name:t.name,ownerDepartmentID:t.ownerDepartmentID,supportingDepartmentIDs:[],businessID:null,storeID:null,startWeek:g.week,targetWeek:g.week+Math.ceil(t.requiredEffort/10),requiredEffort:t.requiredEffort,completedEffort:0,weeklyBudget:t.weeklyBudget,totalBudget:t.totalBudget,spentBudget:0,requiredSkill:t.requiredSkill,priority:1,dependencies:t.dependencies.slice(),status:'planned',blockedReason:'',benefitType:t.benefitType,benefitValue:t.benefitValue,benefitApplied:false,completedWeek:null,operationID:projectID};g.workforceProjects.push(p);return {ok:true,project:p};}
function setProjectStatus(g,projectID,status){const p=(g.workforceProjects||[]).find(x=>x.projectID===projectID);if(!p)return false;if(status==='paused'&&p.status==='active')p.status='paused';else if(status==='active'&&p.status==='paused')p.status='active';else if(status==='cancelled'&&!['completed','failed'].includes(p.status))p.status='cancelled';return true;}
function setProjectPriority(g,projectID,delta){const p=(g.workforceProjects||[]).find(x=>x.projectID===projectID);if(!p)return false;p.priority=clamp(n(p.priority,1)+n(delta),1,5);return true;}
function advanceProjects(g){ensure(g);recompute(g);let projectCost=0,progressed=0;const active=g.workforceProjects.filter(p=>!['completed','cancelled','failed'].includes(p.status)).sort((a,b)=>n(b.priority)-n(a.priority)||String(a.projectID).localeCompare(String(b.projectID)));for(const p of active){if(p.status==='planned')p.status='active';if(p.status==='paused'){p.blockedReason='一時停止中';continue;}if((p.dependencies||[]).some(id=>!g.workforceProjects.some(x=>x.projectID===id&&x.status==='completed'))){p.status='blocked';p.blockedReason='依存プロジェクト未完了';continue;}const d=g.workforceResultsByDepartmentID[p.ownerDepartmentID];if(!d){p.status='blocked';p.blockedReason='担当部門なし';continue;}const remainingBudget=Math.max(0,n(p.totalBudget)-n(p.spentBudget));const budget=Math.min(n(p.weeklyBudget),remainingBudget);if(budget<=0){p.status='paused';p.blockedReason='予算上限';continue;}p.status='active';p.blockedReason='';const progress=clamp(n(d.projectCapacity)*(.8+n(d.managementCoverage)*.2)*(1-n(d.fatigue)/220),0,n(p.requiredEffort)-n(p.completedEffort));if(progress<=0)continue;p.completedEffort=r(n(p.completedEffort)+progress);p.spentBudget=r(n(p.spentBudget)+budget);projectCost+=budget;progressed++;if(p.completedEffort>=p.requiredEffort&&!p.benefitApplied){p.status='completed';p.completedWeek=g.week;p.benefitApplied=true;applyProjectBenefit(g,p);}}return {projectCost:r(projectCost),progressed};}
function applyProjectBenefit(g,p){if(p.benefitType==='departmentEffect'&&g.departments[p.ownerDepartmentID])g.departments[p.ownerDepartmentID].phase4ABonus=clamp(n(g.departments[p.ownerDepartmentID].phase4ABonus)+n(p.benefitValue,.02),0,.15);if(p.benefitType==='morale')for(const t of g.workforceTeams)t.morale=clamp(n(t.morale)+n(p.benefitValue),0,100);if(p.benefitType==='supplyBacklog'){g.workforceSettings=g.workforceSettings||{detailStoreBusinessIDs:['ramen']};g.workforceSettings.supplyBacklogReduction=clamp(n(g.workforceSettings.supplyBacklogReduction)+n(p.benefitValue,.03),0,.12);}}
function validate(g){const errors=[],seen={teamID:new Set(),candidateID:new Set(),trainingID:new Set(),projectID:new Set()};if(!Array.isArray(g.workforceTeams))errors.push('workforceTeamsがありません');if(!Array.isArray(g.workforceCandidates))errors.push('workforceCandidatesがありません');if(!Array.isArray(g.workforceTrainings))errors.push('workforceTrainingsがありません');if(!Array.isArray(g.workforceProjects))errors.push('workforceProjectsがありません');if(!g.workforceSettings||typeof g.workforceSettings!=='object')errors.push('workforceSettingsがありません');function checkID(kind,obj){const id=obj[kind];if(!id)errors.push(`${kind}なし`);else if(seen[kind].has(id))errors.push(`${kind}重複 ${id}`);seen[kind].add(id);}for(const t of (Array.isArray(g.workforceTeams)?g.workforceTeams:[])){checkID('teamID',t);for(const k of ['headcount','managerHeadcount','averageWeeklySalary','fatigue','morale','engagement','weeklyCapacity','requiredWorkload','utilization','backlog'])if(!Number.isFinite(n(t[k])))errors.push(`非有限 ${t.teamID}.${k}`);if(t.headcount<0)errors.push(`負の人数 ${t.teamID}`);if(t.availableHeadcount>t.headcount)errors.push(`available超過 ${t.teamID}`);if(t.managerHeadcount>t.headcount)errors.push(`管理職超過 ${t.teamID}`);if(t.roleID==='store-ops'&&!t.storeID)errors.push(`store-ops店舗未配置 ${t.teamID}`);if(t.departmentID&&!(g.departments||{})[t.departmentID])errors.push(`存在しない部門 ${t.departmentID}`);if(t.storeID&&!(g.stores||[]).some(s=>s.id===t.storeID))errors.push(`存在しない店舗 ${t.storeID}`);for(const b of t.onboardingBatches||[])if(b.status==='active'&&n(b.headcount)<=0)errors.push(`空オンボーディング ${t.teamID}`);}for(const c of (Array.isArray(g.workforceCandidates)?g.workforceCandidates:[])){checkID('candidateID',c);if(c.roleID==='store-ops'&&c.status==='open'&&!c.targetStoreID&&!c.storeID)errors.push(`店舗候補に対象店舗なし ${c.candidateID}`);}for(const tr of (Array.isArray(g.workforceTrainings)?g.workforceTrainings:[])){checkID('trainingID',tr);if(tr.status==='completed'&&!tr.effectApplied)errors.push(`研修効果未適用 ${tr.trainingID}`);}for(const p of (Array.isArray(g.workforceProjects)?g.workforceProjects:[])){checkID('projectID',p);if(p.operationID!==p.projectID)errors.push(`operationID不一致 ${p.projectID}`);if(p.benefitApplied&&p.status!=='completed')errors.push(`未完了効果適用 ${p.projectID}`);if(n(p.spentBudget)>n(p.totalBudget)+.01)errors.push(`予算超過 ${p.projectID}`);}const mirror={};for(const t of (Array.isArray(g.workforceTeams)?g.workforceTeams:[]))if(t.departmentID&&!t.storeID)mirror[t.departmentID]=(mirror[t.departmentID]||0)+t.headcount;for(const id of Object.keys(g.departments||{}))if(Math.abs(n(g.departmentStaff?.[id])-n(mirror[id]))>.001)errors.push(`departmentStaff不一致 ${id}`);return {ok:errors.length===0,errors,checkedWeek:g.week};}
Object.assign(exports,{ROLES,TRAINING_TYPES,PROJECT_TEMPLATES,TARGET_BUSINESS_IDS,ensure,migrateV7,createDepartmentTeam,ensureDepartmentTeam,createStoreTeam,addDepartmentHeadcount,addStoreHeadcount,recompute,aggregate,syncDepartmentStaff,weeklyPayroll,storeExtraPayroll,departmentEffectMultiplier,storeAdjustment,processWeekStart,updateEndOfWeek,generateCandidates,hireCandidate,startTraining,startProject,setProjectStatus,setProjectPriority,advanceProjects,validate,officeMetrics,workload,legacyDepartmentPayroll});
})(__modules.workforce={},__modules.data);
})();
