const { spawnSync } = require('node:child_process');

const commands = [
  'test:syntax','test:static','test:save','test:migration','test:save-v9',
  'test:player-crisis','test:player-crisis-actions','test:player-crisis-ui','test:player-crisis-restructuring','test:player-crisis-restructuring-ui','test:player-debt-service','test:player-turnaround-plan',
  'test:load','test:week','test:transaction','test:long','test:css','test:javascript','test:modules','test:stock',
  'test:market','test:player-media-advertising','test:market-migration','test:market-ui','test:market-capacity','test:market-cannibalization','test:market-calibration','test:market-order','test:market-opening','test:market-rng',
  'test:finance','test:store-weekly-integer-yen','test:statements','test:cashflow','test:working-capital','test:finance-migration','test:finance-ui','test:accounting-invariants','test:finance-advanced','test:finance-history','test:finance-rng','test:finance-user-action-snapshot','test:finance-cash-mutation-coverage','test:finance-book-value','test:finance-working-capital-integration','test:finance-archive-rollforward','test:finance-migrated-advanced-save','test:finance-product-venture','test:finance-startup-subsidiary','test:finance-subsidiary-ipo','test:finance-ma-accounting','test:finance-working-capital-rollforward','test:finance-store-close-deposit','test:finance-property-building-disposal',
  'test:vertical-integration-determinism','test:supply','test:inventory','test:procurement','test:supply-finance','test:supply-migration','test:supply-ui','test:supply-rng','test:supply-calibration','test:supplier-coverage','test:supply-procurement-cash','test:supply-store-close','test:supply-spoilage-profit','test:supply-multi-store-spoilage','test:supply-long',
  'test:workforce','test:workforce-long',
  'test:competitor','test:competitor-market','test:competitor-finance','test:competitor-ai','test:competitor-entry-exit','test:competitor-migration','test:competitor-ui','test:competitor-rng','test:competitor-calibration','test:competitor-history','test:competitor-multi-presence','test:competitor-projects','test:competitor-market-entry','test:competitor-credit','test:competitor-distress-lifecycle','test:competitor-terminal-compat','test:competitor-media','test:competitor-parity','test:competitor-dashboard','test:competitor-long',
  'test:product-innovation','test:ceo-dashboard','test:ma-acquisition-financing','test:weekly-impact','test:founding-tutorial','test:ma-deal-room','test:ma-integration','test:ma-portfolio-summary','test:ma-portfolio-summary-ui','test:ma-board-approval'

];

for (const command of commands) {
  const result = spawnSync('npm', ['run', command, '--silent'], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    shell: false
  });
  if (result.status) {
    console.error(`::error title=Test suite failed::${command}`);
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.status || 1);
  }
}

for (const [name, file] of [
  ['bank-loans-covenants-accounting', 'tests/bank-loans-covenants-accounting-test.js'],
  ['exploration-infrastructure', 'tests/exploration-infrastructure-test.js'],
  ['founder-retirement', 'tests/founder-retirement-test.js'],
  ['venture-investment-outcome', 'tests/venture-investment-outcome-test.js'],
  ['competitor-group-allocation', 'tests/competitor-group-allocation-test.js'],
  ['competitor-product-counter', 'tests/competitor-product-counter-test.js'],
  ['save-storage-compaction', 'tests/save-storage-compaction-test.js'],
  ['competitor-product-counter-reachability', 'tests/competitor-product-counter-reachability-test.js'],
  ['competitor-group-allocation-reachability', 'tests/competitor-group-allocation-reachability-test.js'],
  ['venture-investment-reachability', 'tests/venture-investment-reachability-test.js'],
  ['founder-retirement-reachability', 'tests/founder-retirement-reachability-test.js'],
  ['bank-loans-covenants', 'tests/bank-loans-covenants-test.js'],
  ['boot-recovery', 'tests/boot-recovery-test.js'],
  ['competitor-price-direction-guard', 'tests/competitor-price-direction-guard-test.js'],
  ['competitor-process-week-fallback', 'tests/competitor-process-week-fallback-test.js'],
  ['convertible-bonds-dilution', 'tests/convertible-bonds-dilution-test.js'],
  ['corporate-bonds-ratings', 'tests/corporate-bonds-ratings-test.js'],
  ['d-ui-reference-fidelity', 'tests/d-ui-reference-fidelity-test.js'],
  ['d-ui-shell', 'tests/d-ui-shell-test.js'],
  ['deterministic-economic-foundation', 'tests/deterministic-economic-foundation-test.js'],
  ['executive-dismissal-governance', 'tests/executive-dismissal-governance-test.js'],
  ['executive-retirement-succession', 'tests/executive-retirement-succession-test.js'],
  ['executive-reviews-succession-board', 'tests/executive-reviews-succession-board-test.js'],
  ['executives-department-assignments', 'tests/executives-department-assignments-test.js'],
  ['global-company-ranking-goals', 'tests/global-company-ranking-goals-test.js'],
  ['group-capital-allocation-execution', 'tests/group-capital-allocation-execution-test.js'],
  ['group-capital-allocation-plan', 'tests/group-capital-allocation-plan-test.js'],
  ['group-holding-governance', 'tests/group-holding-governance-test.js'],
  ['hall-of-fame-generations', 'tests/hall-of-fame-generations-test.js'],
  ['industry-event-response-plans', 'tests/industry-event-response-plans-test.js'],
  ['industry-specific-events', 'tests/industry-specific-events-test.js'],
  ['iphone-playtest-remediation', 'tests/iphone-playtest-remediation-test.js'],
  ['long-run-guidance', 'tests/long-run-guidance-test.js'],
  ['ma-investment-committee', 'tests/ma-investment-committee-test.js'],
  ['new-business-commercialization', 'tests/new-business-commercialization-test.js'],
  ['new-business-market-analysis', 'tests/new-business-market-analysis-test.js'],
  ['new-business-research-projects', 'tests/new-business-research-projects-test.js'],
  ['normal-start-ipo-balance-audit', 'tests/normal-start-ipo-balance-audit-test.js'],
  ['playtest-report-ui', 'tests/playtest-report-ui-test.js'],
  ['pmi-100-day-plan', 'tests/pmi-100-day-plan-test.js'],
  ['preferred-shares-dividends', 'tests/preferred-shares-dividends-test.js'],
  ['rc-manual-smoke-gate', 'tests/rc-manual-smoke-gate-test.js'],
  ['real-estate-capex-actuals', 'tests/real-estate-capex-actuals-test.js'],
  ['real-estate-capex-roi', 'tests/real-estate-capex-roi-test.js'],
  ['real-estate-complete-cycle', 'tests/real-estate-complete-cycle-test.js'],
  ['real-estate-development', 'tests/real-estate-development-test.js'],
  ['real-estate-foundation', 'tests/real-estate-foundation-test.js'],
  ['real-estate-insurance-claims', 'tests/real-estate-insurance-claims-test.js'],
  ['real-estate-insurance-risk', 'tests/real-estate-insurance-risk-test.js'],
  ['real-estate-maintenance-reserves', 'tests/real-estate-maintenance-reserves-test.js'],
  ['real-estate-mortgage-refinancing', 'tests/real-estate-mortgage-refinancing-test.js'],
  ['real-estate-portfolio-dashboard', 'tests/real-estate-portfolio-dashboard-test.js'],
  ['real-estate-property-disposals', 'tests/real-estate-property-disposals-test.js'],
  ['real-estate-property-insurance', 'tests/real-estate-property-insurance-test.js'],
  ['real-estate-property-maintenance', 'tests/real-estate-property-maintenance-test.js'],
  ['real-estate-property-management', 'tests/real-estate-property-management-test.js'],
  ['real-estate-property-taxes', 'tests/real-estate-property-taxes-test.js'],
  ['real-estate-redevelopment-projects', 'tests/real-estate-redevelopment-projects-test.js'],
  ['real-estate-rent-guarantee', 'tests/real-estate-rent-guarantee-test.js'],
  ['real-estate-rent-performance', 'tests/real-estate-rent-performance-test.js'],
  ['real-estate-rent-pricing', 'tests/real-estate-rent-pricing-test.js'],
  ['real-estate-risk-mitigation', 'tests/real-estate-risk-mitigation-test.js'],
  ['real-estate-safety-certification', 'tests/real-estate-safety-certification-test.js'],
  ['real-estate-security-deposits', 'tests/real-estate-security-deposits-test.js'],
  ['real-estate-tenant-collections', 'tests/real-estate-tenant-collections-test.js'],
  ['real-estate-tenant-contracts', 'tests/real-estate-tenant-contracts-test.js'],
  ['real-estate-tenant-leasing', 'tests/real-estate-tenant-leasing-test.js'],
  ['real-estate-tenant-operations', 'tests/real-estate-tenant-operations-test.js'],
  ['real-estate-tenant-renewals', 'tests/real-estate-tenant-renewals-test.js'],
  ['release-attestation-issue', 'tests/release-attestation-issue-test.js'],
  ['release-candidate-contract', 'tests/release-candidate-contract-test.js'],
  ['runtime-recovery-ui', 'tests/runtime-recovery-ui-test.js'],
  ['save-import-atomic-guard', 'tests/save-import-atomic-guard-test.js'],
  ['save-storage-ui', 'tests/save-storage-ui-test.js'],
  ['strategy-balance-calibration', 'tests/strategy-balance-calibration-test.js'],
  ['subsidiary-budget-kpi', 'tests/subsidiary-budget-kpi-test.js'],
  ['subsidiary-ipo-secondary-sale', 'tests/subsidiary-ipo-secondary-sale-test.js'],
  ['subsidiary-mandate-apply', 'tests/subsidiary-mandate-apply-test.js'],
  ['subsidiary-performance-review', 'tests/subsidiary-performance-review-test.js'],
  ['exploration-smoke', 'tests/exploration-smoke-test.js'],
  ['exploration-style', 'tests/exploration-style-test.js'],
  ['board-governance-resolution', 'tests/board-governance-resolution-test.js'],
  ['business-record-sanitizer', 'tests/business-record-sanitizer-test.js'],
  ['crisis-ui-observer-contract', 'tests/crisis-ui-observer-contract-test.js'],
  ['game-over-settings-ui', 'tests/game-over-settings-ui-test.js'],
  ['macro-cycle', 'tests/macro-cycle-test.js'],
  ['player-turnaround-plan-ui', 'tests/player-turnaround-plan-ui-test.js'],
  ['product-lifecycle-determinism', 'tests/product-lifecycle-determinism-test.js'],
  ['store-equipment', 'tests/store-equipment-test.js'],
  ['store-specific-pricing', 'tests/store-specific-pricing-test.js'],
  ['store-multiple-menu', 'tests/store-multiple-menu-test.js'],
  ['pe-value-creation', 'tests/pe-value-creation-test.js'],
  ['pe-dual-ownership', 'tests/pe-dual-ownership-test.js'],
  ['save-storage-budget', 'tests/save-storage-budget-test.js'],
  ['storage-history-contract', 'tests/storage-history-contract-test.js'],
  ['setup-recovery-ui', 'tests/setup-recovery-ui-test.js'],
  ['save-storage-quota', 'tests/save-storage-quota-test.js'],
  ['save-storage-recovery-actions', 'tests/save-storage-recovery-actions-test.js'],
  ['difficulty-scenario-balance', 'tests/difficulty-scenario-balance-test.js'],
  ['competitor-dashboard-ui', 'tests/competitor-dashboard-ui-test.js'],
  ['d-ui-context-tabs', 'tests/d-ui-context-tabs-test.js'],
  ['stage-3-3-observer-migration', 'tests/stage-3-3-observer-migration-test.js'],
  ['stage-3-4-startup-observer-migration', 'tests/stage-3-4-startup-observer-migration-test.js'],
  ['stage-3-5a-observer-stability', 'tests/stage-3-5a-observer-stability-test.js'],
  ['observer-threshold-guard', 'tests/observer-threshold-guard-test.js'],
  ['startup-side-effects', 'tests/startup-side-effects-test.js'],
  ['startup-runtime-budget', 'tests/startup-runtime-budget-test.js'],
  ['physical-iphone-playtest', 'tests/physical-iphone-playtest-test.js'],
  ['stage-3-ui-screen-scope-regression', 'tests/stage-3-ui-screen-scope-regression-test.js'],
  ['v1-progression-gate', 'tests/v1-progression-gate-test.js'],
  ['treasury-prepayment', 'tests/treasury-prepayment-test.js'],
  ['treasury-refinancing-policy', 'tests/treasury-refinancing-policy-test.js'],
  ['shareholder-returns', 'tests/shareholder-returns-test.js'],
  ['shareholder-activism', 'tests/shareholder-activism-test.js'],
  ['shareholder-activism-incidence-matrix', 'tests/shareholder-activism-incidence-matrix-test.js'],
  ['shareholder-value-destruction', 'tests/shareholder-value-destruction-test.js'],
  ['shareholder-value-destruction-incidence-matrix', 'tests/shareholder-value-destruction-incidence-matrix-test.js'],
  ['executive-dismissal-reachability', 'tests/executive-dismissal-reachability-test.js'],
  ['industry-specific-events-reachability', 'tests/industry-specific-events-reachability-test.js'],
  ['industry-event-response-plans-reachability', 'tests/industry-event-response-plans-reachability-test.js'],
  ['capital-allocation-score', 'tests/capital-allocation-score-test.js'],
  ['capital-allocation-policy', 'tests/capital-allocation-policy-test.js'],
  ['capital-allocation-comparison', 'tests/capital-allocation-comparison-test.js'],
  ['capital-allocation-actions', 'tests/capital-allocation-actions-test.js'],
  ['capital-allocation-breakdown', 'tests/capital-allocation-breakdown-test.js'],
  ['capital-allocation-recovery', 'tests/capital-allocation-recovery-test.js'],
  ['capital-allocation-decision-memo', 'tests/capital-allocation-decision-memo-test.js'],
  ['capital-allocation-stress-test', 'tests/capital-allocation-stress-test-test.js'],
  ['capital-allocation-resilience-memo', 'tests/capital-allocation-resilience-memo-test.js'],
  ['capital-allocation-recovery-audit', 'tests/capital-allocation-recovery-audit-test.js'],
  ['capital-allocation-recovery-funding', 'tests/capital-allocation-recovery-funding-test.js'],
  ['capital-allocation-recovery-funding-options', 'tests/capital-allocation-recovery-funding-options-test.js'],
  ['capital-allocation-recovery-funding-readiness', 'tests/capital-allocation-recovery-funding-readiness-test.js'],
  ['capital-allocation-recovery-funding-reconciliation', 'tests/capital-allocation-recovery-funding-reconciliation-test.js'],
  ['capital-allocation-recovery-target-selector', 'tests/capital-allocation-recovery-target-selector-test.js'],
  ['capital-allocation-recovery-funding-outcome', 'tests/capital-allocation-recovery-funding-outcome-test.js'],
  ['capital-allocation-management-guide', 'tests/capital-allocation-management-guide-test.js'],
  ['capital-allocation-section-nav', 'tests/capital-allocation-section-nav-test.js'],
  ['capital-allocation-recovery-save-reload', 'tests/capital-allocation-recovery-save-reload-test.js'],
  ['capital-allocation-production-wiring', 'tests/capital-allocation-production-wiring-test.js'],
  ['ma-exit-readiness', 'tests/ma-exit-readiness-test.js'],
  ['internal-venture-business', 'tests/internal-venture-business-test.js'],
  ['subsidiary-ipo-preparation', 'tests/subsidiary-ipo-preparation-test.js'],
  ['listed-subsidiary-market', 'tests/listed-subsidiary-market-test.js'],
  ['listed-subsidiary-portfolio-dashboard', 'tests/listed-subsidiary-portfolio-dashboard-test.js'],
  ['listed-subsidiary-control-actions', 'tests/listed-subsidiary-control-actions-test.js'],
  ['subsidiary-integration-synergy', 'tests/subsidiary-integration-synergy-test.js'],
  ['inter-subsidiary-synergy-allocation', 'tests/inter-subsidiary-synergy-allocation-test.js'],
  ['inter-subsidiary-synergy-performance', 'tests/inter-subsidiary-synergy-performance-test.js'],
  ['group-capital-allocation-actions', 'tests/group-capital-allocation-actions-test.js'],
  ['group-restructuring-candidates', 'tests/group-restructuring-candidates-test.js'],
  ['group-restructuring-progress', 'tests/group-restructuring-progress-test.js'],
  ['subsidiary-relisting-options', 'tests/subsidiary-relisting-options-test.js'],
  ['listed-subsidiary-follow-on-offering', 'tests/listed-subsidiary-follow-on-offering-test.js'],
  ['executive-secretary', 'tests/executive-secretary-test.js'],
  ['executive-secretary-ui', 'tests/executive-secretary-ui-test.js'],
  ['executive-secretary-purity', 'tests/executive-secretary-purity-test.js'],
  ['stock-trade-panel', 'tests/stock-trade-panel-test.js'],
  ['game-date-display', 'tests/game-date-display-test.js']
]) {
  const result = spawnSync('node', [file], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    shell: false
  });
  if (result.status) {
    console.error(`::error title=Test suite failed::${name}`);
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.status || 1);
  }
}

console.log(`all ${commands.length} test commands including registration backfill, save storage quota recovery, save storage recovery actions, M&A board approval, M&A deal room, M&A integration, M&A portfolio summary, M&A exit readiness, internal venture funding and spin-off, staged subsidiary IPO preparation, listed subsidiary market operations, listed subsidiary portfolio dashboard, listed subsidiary TOB and squeeze-out control actions, wholly owned subsidiary integration synergy investments, inter-subsidiary synergy allocation and performance, group capital allocation actions, subsidiary relisting strategies, listed subsidiary follow-on offering capital policy, vertical integration determinism, difficulty/scenario balance, competitor dashboard UI, D UI context tabs, provisional v1 progression gate, treasury prepayment, refinancing policy, shareholder returns, shareholder activism incidence matrix, executive dismissal reachability, industry event reachability, industry event response plan reachability, capital allocation score, capital allocation policy, capital allocation comparison, capital allocation actions, capital allocation score breakdown, capital allocation recovery targets, capital allocation board decision memo, capital allocation board stress test, capital allocation resilience memo, capital allocation recovery audit, capital allocation recovery funding, capital allocation recovery funding options, capital allocation recovery funding readiness, capital allocation recovery funding reconciliation, capital allocation recovery target selector, capital allocation recovery funding outcome, capital allocation management guide, capital allocation recovery save reload, capital allocation production wiring, executive secretary, executive secretary UI, executive secretary purity, stock trade panel, game date display, and CEO dashboard passed`);
console.log('Weekly Impact recap is registered in run-all and all tests passed');
